/**
 * The people on the demo board.
 *
 * Three of them have a published password and are the ones a visitor logs in as.
 * The rest exist to write the content — they have no password anybody knows,
 * because a member account nobody can reach is still a member account, and a
 * board where every author is also a door is a board with forty doors.
 *
 * The cast is the kind of membership the software is actually for: a committee,
 * a juvenile section, players, a crew who play online on a Tuesday night, and
 * the people who turn up for the social side and never the sport. The ones who
 * meet in a room have a town. The ones who meet on a headset have a timezone.
 */

export type DemoGroupKey =
  | 'administrators'
  | 'superModerators'
  | 'moderators'
  | 'registered'
  | 'awaitingActivation'

export interface DemoAccount {
  /** Stable handle used by the content to refer to an author. */
  readonly key: string
  readonly username: string
  readonly email: string
  /** `null` means no published password: the account cannot be logged into. */
  readonly password: string | null
  readonly group: DemoGroupKey
  /** Days before the reset that this account registered. */
  readonly joinedDaysAgo: number
  readonly location: string | null
  readonly website: string | null
  readonly bio: string | null
}

/**
 * `admin` is five characters, and the board's own policy wants eight. That is
 * not a contradiction to paper over: the seed writes the hash directly rather
 * than going through registration, so the policy stays honest for every account
 * created after the seed — including the one a visitor makes themselves. What a
 * demo needs is a password somebody can retype from a banner without a paste
 * buffer, and `admin` is that password.
 */
export const DEMO_LOGINS = {
  admin: { username: 'admin', password: 'admin' },
  moderator: { username: 'moderator', password: 'moderator' },
  member: { username: 'member', password: 'member' },
} as const

export const DEMO_ACCOUNTS: readonly DemoAccount[] = [
  {
    key: 'admin',
    username: DEMO_LOGINS.admin.username,
    email: 'admin@demo.invalid',
    password: DEMO_LOGINS.admin.password,
    group: 'administrators',
    joinedDaysAgo: 640,
    location: 'Carrigmore',
    website: 'https://meith.dev',
    bio: 'Club secretary, and the one who set this board up when the group chat hit its limit. Log in as me to see the admin panel — every screen in it is live.',
  },
  {
    key: 'moderator',
    username: DEMO_LOGINS.moderator.username,
    email: 'moderator@demo.invalid',
    password: DEMO_LOGINS.moderator.password,
    group: 'moderators',
    joinedDaysAgo: 604,
    location: 'Carrigmore',
    website: null,
    bio: 'Reads the reports queue so you do not have to. There is something in it right now.',
  },
  {
    key: 'member',
    username: DEMO_LOGINS.member.username,
    email: 'member@demo.invalid',
    password: DEMO_LOGINS.member.password,
    group: 'registered',
    joinedDaysAgo: 96,
    location: null,
    website: null,
    bio: 'An ordinary account, with ordinary permissions. Useful for seeing what a member cannot do.',
  },

  {
    key: 'siobhan',
    username: 'siobhan.k',
    email: 'siobhan@demo.invalid',
    password: null,
    group: 'administrators',
    joinedDaysAgo: 638,
    location: 'Carrigmore',
    website: null,
    bio: 'Chairperson. Twenty-two years on the committee, four of them willingly.',
  },
  {
    key: 'dara',
    username: 'dara_pro',
    email: 'dara@demo.invalid',
    password: null,
    group: 'superModerators',
    joinedDaysAgo: 631,
    location: 'Carrigmore',
    website: null,
    bio: 'Club PRO. Match reports, fixture changes, and the photo album nobody else will keep.',
  },
  {
    key: 'vex',
    username: 'vexation',
    email: 'vex@demo.invalid',
    password: null,
    group: 'superModerators',
    joinedDaysAgo: 519,
    location: 'UTC+1',
    website: null,
    bio: 'Runs the gaming side. Started as five of us on a Tuesday night. It is not five any more.',
  },
  {
    key: 'mairead',
    username: 'mairead.b',
    email: 'mairead@demo.invalid',
    password: null,
    group: 'moderators',
    joinedDaysAgo: 596,
    location: 'Carrigmore',
    website: null,
    bio: 'Juvenile section secretary. If it involves a child, a pitch and a Saturday, it comes through me.',
  },
  {
    key: 'kev',
    username: 'kev_mc',
    email: 'kev@demo.invalid',
    password: null,
    group: 'moderators',
    joinedDaysAgo: 468,
    location: 'Carrigmore',
    website: null,
    bio: 'Minds the noticeboard and the buy-and-sell. Mark it sold and I will leave you alone.',
  },
  {
    key: 'tinker',
    username: 'tinkerdruid',
    email: 'tinker@demo.invalid',
    password: null,
    group: 'moderators',
    joinedDaysAgo: 441,
    location: 'UTC-5',
    website: null,
    bio: 'Raid officer. Keeps the roster and the wipe count. One of those is longer.',
  },

  {
    key: 'gerry',
    username: 'gerry.o',
    email: 'gerry@demo.invalid',
    password: null,
    group: 'registered',
    joinedDaysAgo: 639,
    location: 'Carrigmore',
    website: null,
    bio: 'Groundsman. The pitch is fine. The pitch is not fine. Ask me on the day.',
  },
  {
    key: 'bernie',
    username: 'bernie_c',
    email: 'bernie@demo.invalid',
    password: null,
    group: 'registered',
    joinedDaysAgo: 620,
    location: 'Carrigmore',
    website: null,
    bio: 'Two in the U12s, one in the U16s, and a car that is never empty.',
  },
  {
    key: 'paudie',
    username: 'paudie_w',
    email: 'paudie@demo.invalid',
    password: null,
    group: 'registered',
    joinedDaysAgo: 637,
    location: 'Carrigmore',
    website: null,
    bio: 'Over-35s. Retired from the firsts in 2011 and from the seconds every October since.',
  },
  {
    key: 'hana',
    username: 'hana.t',
    email: 'hana@demo.invalid',
    password: null,
    group: 'registered',
    joinedDaysAgo: 574,
    location: 'Carrigmore',
    website: null,
    bio: 'Captain, ladies firsts. Started the team with nine players and a borrowed set of bibs.',
  },
  {
    key: 'deco',
    username: 'deco23',
    email: 'deco@demo.invalid',
    password: null,
    group: 'registered',
    joinedDaysAgo: 551,
    location: 'Carrigmore',
    website: null,
    bio: 'Keeper. Every goal is a defensive error and I have the footage.',
  },
  {
    key: 'oisin',
    username: 'oisin_09',
    email: 'oisin@demo.invalid',
    password: null,
    group: 'registered',
    joinedDaysAgo: 508,
    location: 'Carrigmore',
    website: null,
    bio: null,
  },
  {
    key: 'noelle',
    username: 'noelle_mc',
    email: 'noelle@demo.invalid',
    password: null,
    group: 'registered',
    joinedDaysAgo: 486,
    location: 'Carrigmore',
    website: null,
    bio: 'Treasurer. I would love it if the subs went through the website instead of my kitchen table.',
  },
  {
    key: 'jt',
    username: 'jt_physio',
    email: 'jt@demo.invalid',
    password: null,
    group: 'registered',
    joinedDaysAgo: 455,
    location: 'Ennis',
    website: null,
    bio: 'Physio, two nights a week. Not your physio on a Sunday morning at 8am.',
  },
  {
    key: 'luca',
    username: 'luca.rossi',
    email: 'luca@demo.invalid',
    password: null,
    group: 'registered',
    joinedDaysAgo: 322,
    location: 'Carrigmore',
    website: null,
    bio: 'Moved here for work, joined the seconds for something to do on a Saturday. Best decision of the year.',
  },
  {
    key: 'tomas',
    username: 'tomasq',
    email: 'tomas@demo.invalid',
    password: null,
    group: 'registered',
    joinedDaysAgo: 471,
    location: 'Carrigmore',
    website: 'https://example.invalid/carrigmore-cycles',
    bio: 'Sponsor liaison and kit. Also runs the cycling club, which has its own board and its own arguments.',
  },
  {
    key: 'fiadh',
    username: 'fiadh_ny',
    email: 'fiadh@demo.invalid',
    password: null,
    group: 'registered',
    joinedDaysAgo: 268,
    location: 'Carrigmore',
    website: null,
    bio: null,
  },
  {
    key: 'donal',
    username: 'big_donal',
    email: 'donal@demo.invalid',
    password: null,
    group: 'registered',
    joinedDaysAgo: 203,
    location: 'Carrigmore',
    website: null,
    bio: 'Under-16s manager. Volunteer, which is a word that means "does three jobs".',
  },

  {
    key: 'marty',
    username: 'marty.kane',
    email: 'marty@demo.invalid',
    password: null,
    group: 'registered',
    joinedDaysAgo: 634,
    location: 'Carrigmore',
    website: null,
    bio: 'Manages the seconds. Team sheet goes up Thursday and changes twice before Saturday.',
  },
  {
    key: 'shay',
    username: 'shay_92',
    email: 'shay@demo.invalid',
    password: null,
    group: 'registered',
    joinedDaysAgo: 480,
    location: 'Carrigmore',
    website: null,
    bio: null,
  },
  {
    key: 'una',
    username: 'una_r',
    email: 'una@demo.invalid',
    password: null,
    group: 'registered',
    joinedDaysAgo: 401,
    location: 'Ennis',
    website: null,
    bio: 'Ladies firsts, centre half. Also the one who counts the bibs back in.',
  },
  {
    key: 'zoe',
    username: 'zoe.mills',
    email: 'zoe@demo.invalid',
    password: null,
    group: 'registered',
    joinedDaysAgo: 372,
    location: 'Carrigmore',
    website: null,
    bio: 'Coaches the U10s. Nineteen children, one ball each, no survivors.',
  },
  {
    key: 'frank',
    username: 'frank_the_tank',
    email: 'frank@demo.invalid',
    password: null,
    group: 'registered',
    joinedDaysAgo: 633,
    location: 'Carrigmore',
    website: null,
    bio: 'Over-35s and the social committee, in that order of ability.',
  },
  {
    key: 'nia',
    username: 'nia.p',
    email: 'nia@demo.invalid',
    password: null,
    group: 'registered',
    joinedDaysAgo: 246,
    location: 'Ballyquin',
    website: null,
    bio: null,
  },
  {
    key: 'cormac',
    username: 'cormacm',
    email: 'cormac@demo.invalid',
    password: null,
    group: 'registered',
    joinedDaysAgo: 180,
    location: 'Carrigmore',
    website: null,
    bio: 'U16s. Here for the clips.',
  },
  {
    key: 'ellie',
    username: 'ellie.d',
    email: 'ellie@demo.invalid',
    password: null,
    group: 'registered',
    joinedDaysAgo: 262,
    location: 'Carrigmore',
    website: null,
    bio: null,
  },

  {
    key: 'pixel',
    username: 'pixelpanic',
    email: 'pixel@demo.invalid',
    password: null,
    group: 'registered',
    joinedDaysAgo: 498,
    location: 'UTC+0',
    website: null,
    bio: 'Healer main. Will not tank. Have asked me before.',
  },
  {
    key: 'wraith',
    username: 'wraithmode',
    email: 'wraith@demo.invalid',
    password: null,
    group: 'registered',
    joinedDaysAgo: 462,
    location: 'UTC-8',
    website: null,
    bio: 'Awake at odd hours. Sorry about the 4am pings.',
  },
  {
    key: 'nova',
    username: 'nova_k',
    email: 'nova@demo.invalid',
    password: null,
    group: 'registered',
    joinedDaysAgo: 430,
    location: 'UTC+2',
    website: null,
    bio: 'Runs the Sunday ranked block. Bring a mic or bring a good attitude, ideally both.',
  },
  {
    key: 'mango',
    username: 'mangosalt',
    email: 'mango@demo.invalid',
    password: null,
    group: 'registered',
    joinedDaysAgo: 388,
    location: 'UTC+8',
    website: null,
    bio: null,
  },
  {
    key: 'keeg',
    username: 'keegan_hp',
    email: 'keegan@demo.invalid',
    password: null,
    group: 'registered',
    joinedDaysAgo: 341,
    location: 'UTC-3',
    website: null,
    bio: 'Writes the guides nobody asked for and everybody reads.',
  },
  {
    key: 'sunny',
    username: 'sunnyside_up',
    email: 'sunny@demo.invalid',
    password: null,
    group: 'registered',
    joinedDaysAgo: 274,
    location: 'UTC+1',
    website: null,
    bio: 'Casual. Two nights a week, never Wednesdays.',
  },
  {
    key: 'bolt',
    username: 'boltcaster',
    email: 'bolt@demo.invalid',
    password: null,
    group: 'registered',
    joinedDaysAgo: 154,
    location: 'UTC+5:30',
    website: null,
    bio: null,
  },
  {
    key: 'rook',
    username: 'rook.exe',
    email: 'rook@demo.invalid',
    password: null,
    group: 'registered',
    joinedDaysAgo: 71,
    location: 'UTC+1',
    website: null,
    bio: 'Joined for the tournament, stayed for the Tuesday nonsense.',
  },

  {
    key: 'glitch',
    username: 'glitchwitch',
    email: 'glitch@demo.invalid',
    password: null,
    group: 'registered',
    joinedDaysAgo: 210,
    location: 'UTC+2',
    website: null,
    bio: 'Second-team roster, first-team mouth.',
  },
  {
    key: 'otter',
    username: 'otterly',
    email: 'otter@demo.invalid',
    password: null,
    group: 'registered',
    joinedDaysAgo: 160,
    location: 'UTC+10',
    website: null,
    bio: null,
  },
  {
    key: 'bram',
    username: 'bramble_',
    email: 'bram@demo.invalid',
    password: null,
    group: 'registered',
    joinedDaysAgo: 96,
    location: 'UTC+0',
    website: 'https://example.invalid/bramble',
    bio: 'Streams the Tuesday runs. Badly.',
  },

  {
    key: 'rosa',
    username: 'rosa_p',
    email: 'rosa@demo.invalid',
    password: null,
    group: 'registered',
    joinedDaysAgo: 587,
    location: 'Carrigmore',
    website: null,
    bio: 'Community centre committee. Moved a decade of notices onto this board last spring and lived to tell it.',
  },
  {
    key: 'mira',
    username: 'mira_t',
    email: 'mira@demo.invalid',
    password: null,
    group: 'registered',
    joinedDaysAgo: 602,
    location: 'Ballyquin',
    website: null,
    bio: 'Tidy Towns, the flower rota, and whatever else nobody else volunteered for.',
  },
  {
    key: 'olu',
    username: 'oluwaseun',
    email: 'oluwaseun@demo.invalid',
    password: null,
    group: 'registered',
    joinedDaysAgo: 356,
    location: 'Carrigmore',
    website: null,
    bio: 'Organises the Thursday five-a-side. Fourteen people, one pitch, no drama.',
  },
  {
    key: 'petra',
    username: 'petra.k',
    email: 'petra@demo.invalid',
    password: null,
    group: 'registered',
    joinedDaysAgo: 288,
    location: 'Carrigmore',
    website: null,
    bio: null,
  },
  {
    key: 'ken',
    username: 'kenji',
    email: 'kenji@demo.invalid',
    password: null,
    group: 'registered',
    joinedDaysAgo: 601,
    location: 'Carrigmore',
    website: null,
    bio: 'Board games night in the back room, second Friday of the month. Yes, that kind of board.',
  },
  {
    key: 'dev',
    username: 'devinder',
    email: 'devinder@demo.invalid',
    password: null,
    group: 'registered',
    joinedDaysAgo: 197,
    location: 'Carrigmore',
    website: 'https://example.invalid/devinder-photos',
    bio: 'Takes the match photos. Will not take the team photo in the rain again.',
  },
  {
    key: 'sam',
    username: 'samthedog',
    email: 'sam@demo.invalid',
    password: null,
    group: 'registered',
    joinedDaysAgo: 214,
    location: 'Carrigmore',
    website: null,
    bio: null,
  },
  {
    key: 'aoife',
    username: 'aoife.byrne',
    email: 'aoife@demo.invalid',
    password: null,
    group: 'registered',
    joinedDaysAgo: 44,
    location: 'Carrigmore',
    website: null,
    bio: null,
  },
  {
    key: 'newcomer',
    username: 'first_timer',
    email: 'first.timer@demo.invalid',
    password: null,
    group: 'registered',
    joinedDaysAgo: 3,
    location: null,
    website: null,
    bio: null,
  },
  {
    // Writes the spam. One post held in the moderation queue, one that got
    // through and has been reported — so both staff screens have a real row in
    // them, from a real account, that a visitor can act on.
    key: 'spambot',
    username: 'ticket_deals_2026',
    email: 'ticket.deals@demo.invalid',
    password: null,
    group: 'registered',
    joinedDaysAgo: 1,
    location: null,
    website: null,
    bio: null,
  },
  {
    key: 'pending',
    username: 'not_activated_yet',
    email: 'pending@demo.invalid',
    password: null,
    // Sits in the awaiting-activation group so the admin panel's user filters
    // have something to find, and so "approve this account" is a real button
    // with a real row under it.
    group: 'awaitingActivation',
    joinedDaysAgo: 1,
    location: null,
    website: null,
    bio: null,
  },
]

/**
 * The accounts a visitor is invited to log in as. Their password and email are
 * frozen for the life of the demo — see `packages/demo/src/protected.ts`.
 */
export const DEMO_LOGIN_USERNAMES: readonly string[] = Object.values(DEMO_LOGINS).map(
  (login) => login.username,
)

export function demoAccount(key: string): DemoAccount {
  const found = DEMO_ACCOUNTS.find((account) => account.key === key)
  if (found === undefined) {
    throw new Error(`The demo content refers to an author "${key}" that no account defines.`)
  }
  return found
}
