import type { PluginMigration } from '@meith/plugin-kit'

export const CALENDAR_MIGRATIONS: readonly PluginMigration[] = [
  {
    id: '0001_events_and_organisers',
    statements: [
      `create table if not exists plugin_calendar_event (
         id                  bigint generated by default as identity primary key,
         title               text        not null,
         starts_at           timestamptz not null,
         ends_at             timestamptz,
         location            text        not null default '',
         thread_id           integer,
         created_by_user_id  integer,
         created_at          timestamptz not null default now()
       )`,
      `create index if not exists plugin_calendar_event_starts
         on plugin_calendar_event (starts_at)`,
      `create index if not exists plugin_calendar_event_thread
         on plugin_calendar_event (thread_id)
         where thread_id is not null`,
      `create table if not exists plugin_calendar_organiser (
         user_id            integer     not null primary key,
         added_by_user_id   integer,
         added_at           timestamptz not null default now()
       )`,
    ],
  },
]
