import type { PluginMigration } from '@meith/plugin-kit'

export const CALENDAR_MIGRATIONS: readonly PluginMigration[] = [
  {
    id: '0001_events_and_organisers',
    statements: [
      `create table if not exists plugin_calendar_event (
         id                  bigint generated by default as identity primary key,
         title               text        not null,
         starts_at           timestamptz not null,
         ends_at             timestamptz,
         location            text        not null default '',
         thread_id           integer,
         created_by_user_id  integer,
         created_at          timestamptz not null default now()
       )`,
      `create index if not exists plugin_calendar_event_starts
         on plugin_calendar_event (starts_at)`,
      `create index if not exists plugin_calendar_event_thread
         on plugin_calendar_event (thread_id)
         where thread_id is not null`,
      `create table if not exists plugin_calendar_organiser (
         user_id            integer     not null primary key,
         added_by_user_id   integer,
         added_at           timestamptz not null default now()
       )`,
    ],
  },
  {
    id: '0002_event_link',
    statements: [
      `alter table plugin_calendar_event
         add column if not exists link_url text not null default ''`,
      `alter table plugin_calendar_event
         add column if not exists link_label text not null default ''`,
    ],
  },
  {
    id: '0003_recurrence_and_rsvps',
    statements: [
      `alter table plugin_calendar_event
         add column repeat text not null default 'none'
           check (repeat in ('none', 'weekly', 'fortnightly', 'monthly')),
         add column repeat_until date`,
      `create table plugin_calendar_rsvps (
         event_id bigint not null references plugin_calendar_event(id) on delete cascade,
         occurrence_date date not null,
         user_id integer not null,
         status text not null check (status in ('yes', 'no', 'maybe')),
         updated_at timestamptz not null default now(),
         primary key (event_id, occurrence_date, user_id)
       )`,
    ],
  },
  {
    id: '0004_reminder_deliveries',
    statements: [
      `create table plugin_calendar_reminders (
         event_id bigint not null references plugin_calendar_event(id) on delete cascade,
         occurrence_date date not null,
         user_id integer not null,
         processed_at timestamptz not null default now(),
         primary key (event_id, occurrence_date, user_id)
       )`,
    ],
  },
]
