/**
 * A real Postgres, in memory, for adapter tests.
 *
 * PGlite is Postgres compiled to WASM, so the generated migration SQL runs
 * verbatim — `GENERATED BY DEFAULT AS IDENTITY`, `timestamptz`, conditional
 * `UPDATE ... RETURNING`, partial unique indexes and all. That is the whole
 * point: the single-use `consume` guard and the actor group-combine are SQL
 * semantics, and only a genuine Postgres proves them. A hand-rolled mock would
 * "pass" while telling us nothing.
 *
 * This is test-support (`.fixture.ts`, excluded from the orphan rule); it never
 * ships. The drizzle handle is cast to `Database`: the app's is
 * `PostgresJsDatabase` and this is `PgliteDatabase`, but both are
 * `PgDatabase<typeof schema>` and the repositories only use the shared
 * query-builder surface, so the cast is sound for exercising them.
 */
import { PGlite } from '@electric-sql/pglite'
import { drizzle } from 'drizzle-orm/pglite'
import { readFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import type { Database } from './client'
import * as schema from './schema'

/**
 * Counts SQL statements actually sent to the database.
 *
 * Wrapping the *driver* rather than drizzle's logger is deliberate: the budget
 * a list page has to meet is round trips, and drizzle's logger reports what it
 * intended to run. Anything that reaches Postgres — a raw `execute`, a lazily
 * awaited builder, a query drizzle issues on your behalf — is counted here and
 * would be missed there.
 */
export interface QueryLog {
  /** Statements since the last `reset()`. */
  readonly count: number
  /** The SQL itself, for a failure message that says *what* ran. */
  readonly statements: readonly string[]
  reset(): void
}

export interface TestDb {
  readonly db: Database
  readonly queries: QueryLog
  close(): Promise<void>
}

/**
 * Every migration, in journal order.
 *
 * Reads the journal rather than globbing or naming one file: the journal is
 * what the real runner applies, so a migration that is checked in but never
 * registered fails here exactly as it would in production, instead of being
 * silently picked up by a glob and passing.
 */
function migrationSql(): string {
  const here = path.dirname(fileURLToPath(import.meta.url))
  const dir = path.resolve(here, '..', 'migrations')

  const journal = JSON.parse(
    readFileSync(path.join(dir, 'meta', '_journal.json'), 'utf8'),
  ) as { entries: { idx: number; tag: string }[] }

  return [...journal.entries]
    .sort((a, b) => a.idx - b.idx)
    .map((entry) => readFileSync(path.join(dir, `${entry.tag}.sql`), 'utf8'))
    .join('\n')
}

/**
 * Boot a fresh in-memory database with the full schema applied. Each call is a
 * clean instance, so tests are isolated without a truncate dance.
 */
export async function createTestDb(): Promise<TestDb> {
  const client = new PGlite()

  // drizzle-kit separates statements with this marker. PGlite's `exec` runs a
  // semicolon-delimited script in order; the generated SQL creates tables first
  // and adds foreign keys afterward, so sequential execution satisfies deps.
  const sql = migrationSql().split('--> statement-breakpoint').join('\n')
  await client.exec(sql)

  const statements: string[] = []

  /*
   * Installed after the migration so schema setup does not count against a
   * test's budget. Only `query` is wrapped: `exec` runs multi-statement scripts
   * and is used for setup, never by drizzle's query builder.
   */
  const originalQuery = client.query.bind(client)
  ;(client as unknown as { query: typeof originalQuery }).query = ((
    sqlText: string,
    ...rest: unknown[]
  ) => {
    statements.push(sqlText)
    return (originalQuery as (...a: unknown[]) => unknown)(sqlText, ...rest)
  }) as typeof originalQuery

  const db = drizzle(client, {
    schema,
    casing: 'snake_case',
  }) as unknown as Database

  return {
    db,
    queries: {
      get count() {
        return statements.length
      },
      get statements() {
        return [...statements]
      },
      reset() {
        statements.length = 0
      },
    },
    async close() {
      await client.close()
    },
  }
}
