/**
 * A real Postgres, in memory, for adapter tests.
 *
 * PGlite is Postgres compiled to WASM, so the generated migration SQL runs
 * verbatim — `GENERATED BY DEFAULT AS IDENTITY`, `timestamptz`, conditional
 * `UPDATE ... RETURNING`, partial unique indexes and all. That is the whole
 * point: the single-use `consume` guard and the actor group-combine are SQL
 * semantics, and only a genuine Postgres proves them. A hand-rolled mock would
 * "pass" while telling us nothing.
 *
 * This is test-support (`.fixture.ts`, excluded from the orphan rule); it never
 * ships. The drizzle handle is cast to `Database`: the app's is
 * `PostgresJsDatabase` and this is `PgliteDatabase`, but both are
 * `PgDatabase<typeof schema>` and the repositories only use the shared
 * query-builder surface, so the cast is sound for exercising them.
 */
import { PGlite } from '@electric-sql/pglite'
import { drizzle } from 'drizzle-orm/pglite'
import { readFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import type { Database } from './client'
import * as schema from './schema'

export interface TestDb {
  readonly db: Database
  close(): Promise<void>
}

function migrationSql(): string {
  const here = path.dirname(fileURLToPath(import.meta.url))
  const file = path.resolve(here, '..', 'migrations', '0000_initial_schema.sql')
  return readFileSync(file, 'utf8')
}

/**
 * Boot a fresh in-memory database with the full schema applied. Each call is a
 * clean instance, so tests are isolated without a truncate dance.
 */
export async function createTestDb(): Promise<TestDb> {
  const client = new PGlite()

  // drizzle-kit separates statements with this marker. PGlite's `exec` runs a
  // semicolon-delimited script in order; the generated SQL creates tables first
  // and adds foreign keys afterward, so sequential execution satisfies deps.
  const sql = migrationSql().split('--> statement-breakpoint').join('\n')
  await client.exec(sql)

  const db = drizzle(client, {
    schema,
    casing: 'snake_case',
  }) as unknown as Database

  return {
    db,
    async close() {
      await client.close()
    },
  }
}
