import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

export interface RuntimeInstallInfo {
  binDir: string;
  cliBinPath: string;
  cliEntryPath: string;
  appPath?: string;
}

export interface RuntimeInstallOptions {
  home: string;
  appVersion: string;
  appPath?: string;
  cliEntryPath?: string;
}

/**
 * Expose a predictable `meith` launcher under `~/.meith/bin`.
 *
 * The launcher is deliberately small and overwritten on every startup. That is
 * the CLI update path: when the desktop app updates, the shim points at the CLI
 * bundle that shipped with that app version and exports `MEITH_APP_BIN` so
 * `meith`, `meith .`, and `meith new` can relaunch the same desktop build.
 */
export function installRuntimeCli(
  options: RuntimeInstallOptions,
): RuntimeInstallInfo | undefined {
  const cliEntryPath = options.cliEntryPath ?? findCliEntryPath();
  if (!cliEntryPath) return undefined;

  const binDir = join(options.home, "bin");
  const cliBinPath =
    process.platform === "win32" ? join(binDir, "meith.cmd") : join(binDir, "meith");
  mkdirSync(binDir, { recursive: true });

  const content =
    process.platform === "win32"
      ? windowsLauncher(cliEntryPath, options)
      : posixLauncher(cliEntryPath, options);

  if (!existsSync(cliBinPath) || readFileSync(cliBinPath, "utf8") !== content) {
    writeFileSync(cliBinPath, content, "utf8");
    if (process.platform !== "win32") chmodSync(cliBinPath, 0o755);
  }

  return { binDir, cliBinPath, cliEntryPath, appPath: options.appPath };
}

/** Locate the CLI entry in dev, tests, and packaged resources. */
export function findCliEntryPath(): string | undefined {
  const fromEnv = process.env.MEITH_CLI_ENTRY;
  if (fromEnv && existsSync(fromEnv)) return resolve(fromEnv);

  const candidates: string[] = [];
  const resourcesPath = (process as NodeJS.Process & { resourcesPath?: string })
    .resourcesPath;
  if (resourcesPath) {
    candidates.push(join(resourcesPath, "cli", "bin", "meith.mjs"));
  }

  let start: string;
  try {
    start = dirname(fileURLToPath(import.meta.url));
  } catch {
    start = process.cwd();
  }

  for (const root of [start, process.cwd()]) {
    let cur = root;
    for (let i = 0; i < 10; i++) {
      candidates.push(
        join(cur, "packages", "cli", "bin", "meith.mjs"),
        join(cur, "cli", "bin", "meith.mjs"),
      );
      const parent = dirname(cur);
      if (parent === cur) break;
      cur = parent;
    }
  }

  return candidates.find((candidate) => existsSync(candidate));
}

function posixLauncher(cliEntryPath: string, options: RuntimeInstallOptions): string {
  const appExport = options.appPath
    ? `export MEITH_APP_BIN=${shQuote(options.appPath)}\n`
    : "";
  return `#!/bin/sh
# Auto-generated by meith ${options.appVersion}. Do not edit.
${appExport}exec node ${shQuote(cliEntryPath)} "$@"
`;
}

function windowsLauncher(cliEntryPath: string, options: RuntimeInstallOptions): string {
  const appExport = options.appPath ? `set "MEITH_APP_BIN=${options.appPath}"\r\n` : "";
  return `@echo off\r\nrem Auto-generated by meith ${options.appVersion}. Do not edit.\r\n${appExport}node "${cliEntryPath}" %*\r\n`;
}

function shQuote(value: string): string {
  return `'${value.replace(/'/g, "'\\''")}'`;
}
