import { definePlugin } from '@meith/plugin-kit'

export const helloPlugin = definePlugin({
  key: 'hello',
  name: 'Hello',
  version: '0.1.0',
  description:
    'The worked example from examples/hello-plugin: a footer link, a greeting ' +
    'on the board index, one setting, one migration, one task and an admin page.',
  apiVersion: '0',

  settings: [
    {
      key: 'greeting',
      label: 'Greeting',
      default: 'Hello from the Hello plugin!',
      description: 'Shown on the status page under Admin → Plugins → Hello.',
    },
  ],

  migrations: [
    {
      id: '0001_create_wave_table',
      statements: [
        `create table if not exists plugin_hello_wave (
           id integer generated by default as identity primary key,
           waved_at timestamptz not null default now()
         )`,
      ],
    },
  ],

  tasks: [
    {
      id: 'wave',
      intervalSeconds: 3600,
      run: (context) => {
        context.logger.info('hello plugin: waving', {
          greeting: context.settings.greeting,
        })
      },
    },
  ],

  adminPages: [
    {
      path: 'status',
      title: 'Hello plugin',
      render: (context) => (
        <div className="flex flex-col gap-2 text-sm">
          <p>{String(context.settings.greeting)}</p>
          <p className="text-muted-foreground">
            This page is rendered by the plugin itself. Edit the greeting on the plugin&rsquo;s
            settings screen and reload to see the resolved value arrive in{' '}
            <code className="text-xs">context.settings</code>.
          </p>
        </div>
      ),
    },
  ],

  contributions: [
    {
      region: 'index.footer',
      render: (context) => {
        const key = context.viewer.isGuest ? 'hello.footer.guest' : 'hello.footer.member'
        const fallback = context.viewer.isGuest
          ? 'Hello, guest — this line comes from the example plugin.'
          : 'Hello, member — this line comes from the example plugin.'
        return (
          <p className="text-xs text-muted-foreground" data-plugin="hello">
            {context.t.has(key) ? context.t.t(key) : fallback}
          </p>
        )
      },
    },
  ],

  hooks: {
    'view.footer': (footer) => ({
      ...footer,
      links: [
        ...footer.links,
        {
          label: 'Hello plugin',
          href: 'https://github.com/meith-dev/meith/tree/main/examples/hello-plugin',
        },
      ],
    }),

    'post.created': () => {},
  },
})
