import type { PluginMigration } from '@meith/plugin-kit'

export const WEBHOOKS_MIGRATIONS: readonly PluginMigration[] = [
  {
    id: '0001_delivery_queue',
    statements: [
      `create table if not exists plugin_webhooks_delivery (
         id              bigint generated by default as identity primary key,
         event           text        not null,
         body            text        not null,
         attempts        integer     not null default 0,
         next_attempt_at timestamptz not null default now(),
         delivered_at    timestamptz,
         dead_at         timestamptz,
         last_error      text,
         created_at      timestamptz not null default now()
       )`,
      `create index if not exists plugin_webhooks_delivery_due
         on plugin_webhooks_delivery (next_attempt_at)
         where delivered_at is null and dead_at is null`,
    ],
  },
]
