import type { PluginMigration } from '@meith/plugin-kit'

export const DUES_MIGRATIONS: readonly PluginMigration[] = [
  {
    id: '0001_customers_orders',
    statements: [
      `create table if not exists plugin_dues_customer (
         user_id            integer     not null,
         stripe_customer_id text        not null,
         created_at         timestamptz not null default now(),
         primary key (user_id)
       )`,
      `create unique index if not exists plugin_dues_customer_stripe_key
         on plugin_dues_customer (stripe_customer_id)`,
      `create table if not exists plugin_dues_order (
         id                       bigint generated by default as identity primary key,
         buyer_user_id            integer     not null,
         recipient_user_id        integer     not null,
         plan_key                 text        not null,
         plan_name                text        not null,
         group_key                text        not null,
         amount_minor             integer     not null,
         currency                 text        not null,
         billing_mode             text        not null,
         period_spec              text,
         status                   text        not null default 'created',
         needs_attention          text,
         idempotency_key          text        not null,
         stripe_session_id        text,
         stripe_subscription_id   text,
         stripe_payment_intent_id text,
         checkout_url             text,
         created_at               timestamptz not null default now(),
         settled_at               timestamptz
       )`,
      `create unique index if not exists plugin_dues_order_idem_key
         on plugin_dues_order (idempotency_key)`,
      `create unique index if not exists plugin_dues_order_session_key
         on plugin_dues_order (stripe_session_id)
         where stripe_session_id is not null`,
      `create index if not exists plugin_dues_order_pending_idx
         on plugin_dues_order (created_at)
         where status in ('created', 'pending')`,
      `create index if not exists plugin_dues_order_buyer_idx
         on plugin_dues_order (buyer_user_id)`,
    ],
  },
  {
    id: '0002_memberships_events_ledger',
    statements: [
      `create table if not exists plugin_dues_membership (
         id                     bigint generated by default as identity primary key,
         user_id                integer     not null,
         group_key              text        not null,
         plan_key               text        not null,
         status                 text        not null,
         renewal_mode           text        not null,
         current_period_end     timestamptz not null,
         grace_until            timestamptz not null,
         needs_attention        text,
         stripe_subscription_id text,
         last_order_id          bigint,
         created_at             timestamptz not null default now(),
         updated_at             timestamptz not null default now()
       )`,
      `create unique index if not exists plugin_dues_membership_live_key
         on plugin_dues_membership (user_id, group_key)
         where status in ('active', 'grace', 'closing')`,
      `create index if not exists plugin_dues_membership_subscription_idx
         on plugin_dues_membership (stripe_subscription_id)
         where stripe_subscription_id is not null`,
      `create index if not exists plugin_dues_membership_due_idx
         on plugin_dues_membership (grace_until)
         where status in ('active', 'grace', 'closing')`,
      `create table if not exists plugin_dues_event (
         id              bigint generated by default as identity primary key,
         stripe_event_id text        not null,
         type            text        not null,
         payload         jsonb       not null,
         received_at     timestamptz not null default now(),
         processed_at    timestamptz,
         outcome         text
       )`,
      `create unique index if not exists plugin_dues_event_stripe_key
         on plugin_dues_event (stripe_event_id)`,
      `create index if not exists plugin_dues_event_unprocessed_idx
         on plugin_dues_event (received_at)
         where processed_at is null`,
      `create table if not exists plugin_dues_ledger (
         id            bigint generated by default as identity primary key,
         occurred_at   timestamptz not null default now(),
         kind          text        not null,
         user_id       integer     not null,
         membership_id bigint,
         order_id      bigint,
         amount_minor  integer     not null,
         currency      text        not null,
         stripe_ref    text,
         note          text
       )`,
      `create index if not exists plugin_dues_ledger_time_idx
         on plugin_dues_ledger (occurred_at)`,
    ],
  },
  {
    id: '0003_discount_codes',
    statements: [
      `create table if not exists plugin_dues_code (
         id                 bigint generated by default as identity primary key,
         code               text        not null,
         percent_off        integer     not null,
         plan_key           text,
         max_redemptions    integer,
         redeemed_count     integer     not null default 0,
         expires_at         timestamptz,
         disabled           boolean     not null default false,
         created_by_user_id integer     not null,
         stripe_coupon_id   text,
         created_at         timestamptz not null default now()
       )`,
      `create unique index if not exists plugin_dues_code_key
         on plugin_dues_code (lower(code))`,
      `alter table plugin_dues_order add column if not exists code_id bigint`,
      `alter table plugin_dues_order add column if not exists discount_minor integer not null default 0`,
    ],
  },
  {
    id: '0004_plans',
    statements: [
      `create table if not exists plugin_dues_plan (
         id                bigint generated by default as identity primary key,
         plan_key          text        not null,
         name              text        not null,
         description       text,
         group_key         text        not null,
         price_minor       integer     not null,
         currency          text        not null,
         mode              text        not null,
         period_spec       text,
         billing_interval  text,
         stripe_price_id   text,
         stripe_product_id text,
         giftable          boolean     not null default true,
         hidden            boolean     not null default false,
         archived          boolean     not null default false,
         created_at        timestamptz not null default now(),
         updated_at        timestamptz not null default now()
       )`,
      `create unique index if not exists plugin_dues_plan_key
         on plugin_dues_plan (plan_key)`,
    ],
  },
  {
    id: '0005_code_reservations',
    statements: [
      `create table if not exists plugin_dues_code_reservation (
         id         bigint generated by default as identity primary key,
         code_id    bigint      not null,
         order_id   bigint      not null,
         status     text        not null default 'held',
         created_at timestamptz not null default now(),
         updated_at timestamptz not null default now()
       )`,
      `create unique index if not exists plugin_dues_code_reservation_order_key
         on plugin_dues_code_reservation (order_id)`,
      `create index if not exists plugin_dues_code_reservation_active_idx
         on plugin_dues_code_reservation (code_id)
         where status in ('held', 'consumed')`,
    ],
  },
]
