/**
 * A real Postgres for the browser suite, with no service to install.
 *
 * ## The gap this closes
 *
 * Since F39 the browser suite has covered **reading only**. `next dev` ran
 * against `DATA_SOURCE=fixture`, which serves sample data from memory and has
 * no writer for anything — so posting, inline moderation, private messages,
 * reputation, the UserCP and now attachments have had no browser-level proof at
 * all. Every feature since has widened that hole, and `plan-status.md` has said
 * so, feature after feature, without it moving.
 *
 * The reason it never moved is that the obvious fix — "run the e2e suite
 * against Postgres" — meant a service somebody has to install, so it would have
 * been a CI-only capability. A test path that only exists in CI is one nobody
 * runs before pushing.
 *
 * ## What this is
 *
 * PGlite is Postgres compiled to WebAssembly, and the integration suite has
 * trusted it for a hundred-odd files: the checked-in migration SQL runs
 * verbatim, partial unique indexes and conditional `UPDATE ... RETURNING`
 * included. What it could not do was serve a *separate process* — and
 * `@electric-sql/pglite-socket` puts the Postgres wire protocol in front of it,
 * so `next dev` connects with an ordinary `DATABASE_URL` and does not know the
 * difference.
 *
 * The honest limit, stated once: **PGlite is not the driver production uses.**
 * D54 is in this repository precisely because a write path PGlite accepted was
 * rejected by every real Postgres. This narrows the gap enormously and does not
 * close it, which is why `client.pg.test.ts` still exists and CI still runs a
 * job against a real server.
 *
 * ## The board it seeds is the fixture board
 *
 * Deliberately the *same* rows — `SEED_FORUM_ROWS`, `SEED_THREAD_ROWS`,
 * `SEED_POST_ROWS` — inserted into real tables. One board definition, two
 * stores. Two consequences worth having: the specs written against fixture mode
 * keep passing unchanged, and a divergence between what the fixture serves and
 * what the schema can hold becomes a startup failure here rather than a
 * mystery later.
 *
 * Run directly (`tsx e2e/support/database.ts`); `playwright.config.ts` starts it
 * as the first `webServer`, so the port is open and the data is in before the
 * app is even launched.
 */
import { readFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { PGlite } from '@electric-sql/pglite'
import { PGLiteSocketServer } from '@electric-sql/pglite-socket'

import { E2E_DATABASE_URL, E2E_DB_PORT } from './config'

import {
  SEED_FORUM_ROWS,
  SEED_MEMBER_PROFILES,
  SEED_POST_ROWS,
  SEED_THREAD_ROWS,
} from '../../apps/forum/src/server/seed-board'

const here = path.dirname(fileURLToPath(import.meta.url))
const MIGRATIONS = path.resolve(here, '../../packages/db/migrations')

/**
 * Every migration, in journal order.
 *
 * The journal rather than a glob, for the reason `pglite.fixture.ts` gives: the
 * journal is what the real runner applies, so a migration that is checked in
 * and never registered fails here exactly as it would in production.
 */
function migrationSql(): string {
  const journal = JSON.parse(
    readFileSync(path.join(MIGRATIONS, 'meta', '_journal.json'), 'utf8'),
  ) as { entries: { idx: number; tag: string }[] }

  return [...journal.entries]
    .sort((a, b) => a.idx - b.idx)
    .map((entry) => readFileSync(path.join(MIGRATIONS, `${entry.tag}.sql`), 'utf8'))
    .join('\n')
    .replaceAll('--> statement-breakpoint', '')
}

/** SQL-quote a value. Test support, and the inputs are checked-in constants. */
function literal(value: unknown): string {
  if (value === null || value === undefined) return 'null'
  if (typeof value === 'number') return String(value)
  if (typeof value === 'boolean') return value ? 'true' : 'false'
  if (value instanceof Date) return `'${value.toISOString()}'`
  return `'${String(value).replaceAll("'", "''")}'`
}

function insert(table: string, rows: readonly Record<string, unknown>[]): string {
  if (rows.length === 0) return ''
  const columns = Object.keys(rows[0] as Record<string, unknown>)
  const values = rows
    .map((row) => `(${columns.map((column) => literal(row[column])).join(', ')})`)
    .join(',\n       ')

  return `insert into ${table} (${columns.join(', ')}) values\n       ${values};`
}

/**
 * The fixture board, as rows.
 *
 * The authors come first because everything references them, and the sequences
 * are moved past the seeded ids at the end — every table uses
 * `GENERATED BY DEFAULT AS IDENTITY`, so inserting explicit ids leaves the
 * sequence at 1 and the first row the *browser* creates would collide.
 */
function seedSql(): string {
  const authors = new Map<number, string>()
  for (const post of SEED_POST_ROWS) {
    if (post.authorUserId !== null) authors.set(post.authorUserId, post.authorUsername)
  }
  for (const thread of SEED_THREAD_ROWS) {
    if (thread.authorUserId !== null) authors.set(thread.authorUserId, thread.authorUsername)
  }

  const profiles = new Map(SEED_MEMBER_PROFILES.map((profile) => [profile.id, profile]))

  const users = [...authors].map(([id, username]) => {
    const profile = profiles.get(id)
    return {
      id,
      username,
      username_lower: username.toLowerCase(),
      email: `${username.toLowerCase()}@example.test`,
      email_lower: `${username.toLowerCase()}@example.test`,
      /*
       * A hash nothing can match. These accounts exist to own content, not to
       * be signed into — a spec that needs a session registers through the
       * form, which is the path worth exercising anyway.
       */
      password_hash: 'x',
      password_algo: 'argon2id',
      primary_group_id: id === 1 ? 3 : 2,
      post_count: profile?.postCount ?? 0,
      created_at: profile?.createdAt ?? new Date('2026-01-01T00:00:00Z'),
      location: profile?.location ?? null,
      website: profile?.website ?? null,
      bio: profile?.bio ?? null,
    }
  })

  const forums = SEED_FORUM_ROWS.map((forum) => ({
    id: forum.id,
    type: forum.type,
    title: forum.title,
    slug: forum.slug,
    description: forum.description,
    parent_id: forum.parentId,
    path: forum.path,
    depth: forum.depth,
    display_order: forum.displayOrder,
    link_url: forum.linkUrl,
    thread_count: forum.threadCount,
    post_count: forum.postCount,
    /*
     * The denormalised last post. The fixture repository carries it as a nested
     * object and the index renders it as the "latest" column; in Postgres it is
     * six columns on `forums`, maintained on the write path. Seeding it is what
     * makes the two boards the same board — without it the index renders with
     * no latest-post link and every spec that clicks one fails for a reason
     * that has nothing to do with the code under test.
     */
    last_post_id: forum.lastPost?.postId ?? null,
    last_post_thread_id: forum.lastPost?.threadId ?? null,
    last_post_thread_title: forum.lastPost?.threadTitle ?? null,
    last_post_user_id: forum.lastPost?.userId ?? null,
    last_post_username: forum.lastPost?.username ?? null,
    last_post_at: forum.lastPost?.at ?? null,
  }))

  const threads = SEED_THREAD_ROWS.map((thread) => ({
    id: thread.id,
    forum_id: thread.forumId,
    title: thread.title,
    slug: thread.slug,
    author_user_id: thread.authorUserId,
    author_username: thread.authorUsername,
    reply_count: thread.replyCount,
    view_count: thread.viewCount,
    visibility: thread.visibility,
    is_sticky: thread.isSticky,
    is_locked: thread.isLocked,
    first_post_id: SEED_POST_ROWS.find((p) => p.threadId === thread.id && p.isFirstPost)?.id ?? null,
    last_post_id: thread.lastPost?.postId ?? null,
    last_post_at: thread.lastPost?.at ?? null,
    last_post_user_id: thread.lastPost?.userId ?? null,
    last_post_username: thread.lastPost?.username ?? null,
    created_at: SEED_POST_ROWS.find((p) => p.threadId === thread.id && p.isFirstPost)?.createdAt
      ?? new Date('2026-07-29T09:00:00Z'),
  }))

  const posts = SEED_POST_ROWS.map((post) => ({
    id: post.id,
    thread_id: post.threadId,
    forum_id: post.forumId,
    author_user_id: post.authorUserId,
    author_username: post.authorUsername,
    message: post.message,
    /*
     * Left unrendered on purpose. F36 falls back to rendering live when the
     * stored HTML is missing or stale, and the existing specs assert on markup
     * the *live* path produced — a seeder that pre-rendered would quietly stop
     * testing that.
     */
    message_html: null,
    render_version: 0,
    is_first_post: post.isFirstPost,
    visibility: post.visibility,
    created_at: post.createdAt,
  }))

  /*
   * `admin` needs to be a real administrator for the ACP and moderation specs,
   * and group membership is a join table rather than the primary group alone.
   */
  const memberships = users.map((user) => ({
    user_id: user.id,
    group_id: user.primary_group_id,
  }))

  return [
    insert('users', users),
    insert('user_group_memberships', memberships),
    insert('forums', forums),
    insert('threads', threads),
    insert('posts', posts),
    /* Past every seeded id, so the first row a browser creates does not collide. */
    "select setval(pg_get_serial_sequence('users', 'id'), (select max(id) from users));",
    "select setval(pg_get_serial_sequence('forums', 'id'), (select max(id) from forums));",
    "select setval(pg_get_serial_sequence('threads', 'id'), (select max(id) from threads));",
    "select setval(pg_get_serial_sequence('posts', 'id'), (select max(id) from posts));",
  ]
    .filter((statement) => statement !== '')
    .join('\n')
}

export async function startDatabase(): Promise<{ stop: () => Promise<void> }> {
  const db = await PGlite.create()
  await db.exec(migrationSql())
  await db.exec(seedSql())

  const server = new PGLiteSocketServer({
    db,
    port: E2E_DB_PORT,
    host: '127.0.0.1',
    /*
     * **One backend, therefore one connection.** This is not a tuning choice.
     *
     * A real Postgres gives every connection its own backend process, and with
     * it its own *unnamed prepared statement* — which is what `prepare: false`
     * (the setting `client.ts` uses, and must) makes every query go through.
     * PGlite is a single backend behind however many sockets, so two
     * connections using the unnamed statement clobber each other's parameter
     * lists. The error that comes back is
     * `bind message supplies 1 parameters, but prepared statement "" requires 2`
     * — which looks like a driver bug and is really two clients sharing one
     * backend.
     *
     * A second connection is therefore *queued* rather than served in parallel,
     * which is fine: the suite runs one worker, and `DATABASE_POOL_MAX=1` in
     * `playwright.config.ts` means the app asks for one anyway.
     */
    maxConnections: 1,
  })
  await server.start()

  return {
    async stop() {
      await server.stop()
      await db.close()
    },
  }
}

/* Run as a process: start, and stay up until asked to stop. */
const invokedDirectly = process.argv[1] !== undefined &&
  path.resolve(process.argv[1]).startsWith(path.resolve(here, 'database'))

if (invokedDirectly) {
  /*
   * Not top-level `await`: the workspace root is CommonJS, so `tsx` transforms
   * this file to CJS and top-level await does not compile. An IIFE costs
   * nothing and keeps the file runnable both ways.
   */
  void (async () => {
    const { stop } = await startDatabase()
    // eslint-disable-next-line no-console -- this is a process; its output is its status
    console.log(`e2e database listening on ${E2E_DATABASE_URL}`)

    for (const signal of ['SIGINT', 'SIGTERM'] as const) {
      process.on(signal, () => {
        void stop().finally(() => process.exit(0))
      })
    }
  })()
}
