export {
  checkUpgradeSpan,
  compareVersions,
  type OrderFailure,
  orderPlugins,
  type PluginUpgrade,
  parseVersion,
  planUpgrade,
  SUPPORTED_MAJOR_SPAN,
  type UpgradePlan,
  type UpgradeRefusal,
  type UpgradeState,
  type UpgradeStep,
  upgradeNotice,
  type Version,
} from './plan'
