import type { DemoForum, DemoPrefix } from './types'

export const DEMO_FORUMS: readonly DemoForum[] = [
  {
    key: 'cat-committee',
    type: 'category',
    title: 'Committee room',
    slug: 'committee-room',
    parent: null,
    access: 'staff',
  },
  {
    key: 'committee',
    type: 'forum',
    title: 'Committee business',
    slug: 'committee-business',
    description:
      'Agendas, minutes, money before it is decided, and the things that need a decision before they need a thread.',
    parent: 'cat-committee',
    access: 'staff',
  },
  {
    key: 'staffdesk',
    type: 'forum',
    title: 'Moderation desk',
    slug: 'moderation-desk',
    description:
      'The queue, the reports, and the members who need a conversation rather than a warning.',
    parent: 'cat-committee',
    access: 'staff',
  },
  {
    key: 'welfare',
    type: 'forum',
    title: 'Welfare and safeguarding',
    slug: 'welfare-and-safeguarding',
    description:
      'Vetting, training, and anything involving a child. Nothing in here leaves the room without the welfare officer.',
    parent: 'cat-committee',
    access: 'staff',
  },
  {
    key: 'staffroom',
    type: 'forum',
    title: 'Staff room',
    slug: 'staff-room',
    description: 'Rotas, handovers, cover, and complaining about the rotas.',
    parent: 'cat-committee',
    access: 'staff',
  },

  {
    key: 'cat-supporters',
    type: 'category',
    title: "Supporters' club",
    slug: 'supporters-club',
    parent: null,
    access: 'supporters',
  },
  {
    key: 'supporters',
    type: 'forum',
    title: "Supporters' lounge",
    slug: 'supporters-lounge',
    description:
      'The main room for members on the plan. No agenda, no committee, and no vote the rest of the club does not have.',
    parent: 'cat-supporters',
    access: 'supporters',
  },
  {
    key: 'accounts',
    type: 'forum',
    title: 'Where the money goes',
    slug: 'where-the-money-goes',
    description:
      'Every euro the plan brings in, itemised, a week before the rest of the club sees it.',
    parent: 'cat-supporters',
    access: 'supporters',
  },
  {
    key: 'firstlook',
    type: 'forum',
    title: 'First look',
    slug: 'first-look',
    description:
      'Kit designs, fixtures, plans and AGM papers, early enough that saying something about them still changes them.',
    parent: 'cat-supporters',
    access: 'supporters',
  },
  {
    key: 'draw',
    type: 'forum',
    title: "The supporters' draw",
    slug: 'supporters-draw',
    description:
      'Drawn on the first of the month. One number, one winner, and a photograph of the hat.',
    parent: 'cat-supporters',
    access: 'supporters',
  },

  { key: 'cat-start', type: 'category', title: 'Start here', slug: 'start-here', parent: null },
  {
    key: 'announcements',
    type: 'forum',
    title: 'Announcements',
    slug: 'announcements',
    description:
      'Notices, closures, changes of plan, and anything the committee needs everyone to have read.',
    parent: 'cat-start',
  },
  {
    key: 'introductions',
    type: 'forum',
    title: 'Introductions',
    slug: 'introductions',
    description: 'New here? Say who you are and what you turned up for.',
    parent: 'cat-start',
  },

  {
    key: 'cat-community',
    type: 'category',
    title: 'The community',
    slug: 'the-community',
    parent: null,
  },
  {
    key: 'general',
    type: 'forum',
    title: 'General discussion',
    slug: 'general-discussion',
    description: 'The main forum. Anything to do with the club, the crew, or the week just gone.',
    parent: 'cat-community',
  },
  {
    key: 'events',
    type: 'forum',
    title: 'Events and fixtures',
    slug: 'events-and-fixtures',
    description: 'Matches, raid nights, tournaments, socials. Sign-ups before, results after.',
    parent: 'cat-community',
  },
  {
    key: 'media',
    type: 'forum',
    title: 'Photos and clips',
    slug: 'photos-and-clips',
    description: 'Match photos, screenshots, highlight reels, and the team photo nobody likes.',
    parent: 'cat-community',
  },
  {
    key: 'noticeboard',
    type: 'forum',
    title: 'Noticeboard',
    slug: 'noticeboard',
    description:
      'Lifts, lost property, volunteers wanted, and the small stuff that still needs saying.',
    parent: 'cat-community',
  },
  {
    key: 'market',
    type: 'forum',
    title: 'Buy, sell and swap',
    slug: 'buy-sell-and-swap',
    description: 'Kit, gear, tickets, hardware. Mark it sold and everyone thanks you.',
    parent: 'cat-community',
  },
  {
    key: 'offtopic',
    type: 'forum',
    title: 'Anything else',
    slug: 'anything-else',
    description: 'The other forum.',
    parent: 'cat-community',
  },

  {
    key: 'cat-running',
    type: 'category',
    title: 'Running the place',
    slug: 'running-the-place',
    parent: null,
  },
  {
    key: 'membership',
    type: 'forum',
    title: 'Membership and subs',
    slug: 'membership-and-subs',
    description: 'Joining, renewing, fees, fundraising, and where the money went.',
    parent: 'cat-running',
  },
  {
    key: 'support',
    type: 'forum',
    title: 'Help with the board',
    slug: 'help-with-the-board',
    description: 'Cannot log in, cannot upload, notifications gone quiet. Say what you are on.',
    parent: 'cat-running',
  },
  {
    key: 'feedback',
    type: 'forum',
    title: 'Feedback and ideas',
    slug: 'feedback-and-ideas',
    description: 'Suggestions for the board and for how we do things. Somebody does read them.',
    parent: 'cat-running',
  },
  {
    key: 'moderation',
    type: 'forum',
    title: 'Moderation and rules',
    slug: 'moderation-and-rules',
    description: 'How this place is run, in the open.',
    parent: 'cat-running',
  },
]

export const DEMO_PREFIXES: readonly DemoPrefix[] = [
  { key: 'notice', label: 'Notice', token: 'thread-pinned', scope: 'announcements' },
  { key: 'fixture', label: 'Fixture', token: null, scope: 'events' },
  { key: 'signup', label: 'Sign-up', token: 'moderation-pending', scope: 'events' },
  { key: 'result', label: 'Result', token: 'moderation-approved', scope: 'events' },
  { key: 'forsale', label: 'For sale', token: null, scope: 'market' },
  { key: 'wanted', label: 'Wanted', token: 'thread-moved', scope: 'market' },
  { key: 'sold', label: 'Sold', token: 'thread-locked', scope: 'market' },
  { key: 'solved', label: 'Solved', token: 'moderation-approved', scope: 'support' },
]
