import type { DemoThread } from './types'

/**
 * Photos, the noticeboard, the buy-and-sell and the off-topic forum: the four
 * that decide whether a board feels lived in. A club board with no lost gear
 * bag and nothing for sale is a website.
 */
export const NOTICEBOARD_THREADS: readonly DemoThread[] = [
  {
    forum: 'media',
    author: 'mango',
    title: 'Screenshot thread: post yours',
    daysAgo: 150,
    message: [
      'No theme, no rules, nothing has to be impressive. Post the thing you took a picture of because it looked good at the time.',
      '',
      'Starting with the one from Tuesday where four of us ended up standing in a perfect line by accident and it looks entirely staged.',
    ].join('\n'),
    replies: [
      { author: 'pixel', hoursAfter: 3, message: 'Mine is a screenshot of the exact frame before it all went wrong, which is the only kind I seem to take.' },
      { author: 'otter', hoursAfter: 14, message: 'Sunrise over the thing, taken at what was 5am for me and mid-afternoon for the rest of you.' },
      { author: 'bolt', hoursAfter: 40, message: 'Posted three. One is genuinely good and two are of Wraith falling.' },
      { author: 'wraith', hoursAfter: 47, message: 'Delete two of those.' },
      { author: 'cormac', hoursAfter: 200, message: 'Scrolled the whole thread instead of doing homework. Worth it.' },
      { author: 'glitch', hoursAfter: 900, message: 'Reviving this because I got a genuinely lovely one last night and there is nowhere else for it to go.' },
    ],
  },
  {
    forum: 'media',
    author: 'dev',
    title: 'Team photo, take four',
    daysAgo: 90,
    message: [
      'Fourth attempt. The first was in the rain, the second had nine players, the third had a bin in it.',
      '',
      'This one has everybody, no bin, and Frank blinking. I have decided that is the one.',
    ].join('\n'),
    replies: [
      { author: 'frank', hoursAfter: 1, message: 'I was not blinking, that is my face.' },
      { author: 'siobhan', hoursAfter: 5, message: 'It is going on the clubhouse wall beside the 1996 one, so Frank will be blinking for twenty years.' },
      { author: 'una', hoursAfter: 11, message: 'Can we do a ladies squad one on a Thursday? We have never had one and there are nineteen of us now.' },
      { author: 'dev', hoursAfter: 12, quotes: 3, message: 'Thursday after training, ten minutes, no rain or I will not do it. Booked.' },
      { author: 'hana', hoursAfter: 30, message: 'Nineteen of us and one of them was a bin in 2019, so we have come a long way.' },
    ],
  },
  {
    forum: 'media',
    author: 'mairead',
    title: 'Summer camp photos — parents, read the first post before you scroll',
    daysAgo: 80,
    message: [
      'Photos from the camp are up. Before anybody asks why their child is not in them: **only children whose parents ticked the photo box on the form are in here.** Eleven did not, and that is completely fine and nobody needs a reason.',
      '',
      'If you ticked it and want a specific photo taken down, message me and it is gone within the hour. No explanation needed, ever.',
    ].join('\n'),
    replies: [
      { author: 'ellie', hoursAfter: 4, message: 'Thank you for doing it this way round. The last place we were in put everything up and asked afterwards.' },
      { author: 'bernie', hoursAfter: 9, message: 'Mine are in there having the time of their lives and one of them is eating a sandwich in every single photo.' },
      { author: 'zoe', hoursAfter: 20, message: 'Eighty children and the photo with all of them in it took twenty-five minutes. Devinder earned his tea.' },
      { author: 'dev', hoursAfter: 26, message: 'It took twenty-five minutes because a child kept lying down. Great week though.' },
    ],
  },
  {
    forum: 'media',
    author: 'rosa',
    title: 'The 1996 team photo, scanned, and we cannot name four of them',
    daysAgo: 25,
    message: [
      'First of the box. 1996 squad photo, in colour, in remarkably good condition given where it has been living.',
      '',
      'We have names for fourteen of the eighteen. Four we cannot get: back row second from left, back row far right, and the two lads sitting on the ground at the front.',
      '',
      'Ask your parents. Somebody knows.',
    ].join('\n'),
    replies: [
      { author: 'paudie', hoursAfter: 2, message: 'Back row far right is my uncle. He will be thrilled and he will also tell you he was man of the match in the county final, which he was not.' },
      { author: 'siobhan', hoursAfter: 6, message: 'The one on the left at the front went to Boston in 1998 and I think his sister is still in the village. I will ask.' },
      { author: 'frank', hoursAfter: 14, message: 'Second from left is Mattie. Certain of it. He had that jacket for a decade.' },
      { author: 'rosa', hoursAfter: 30, message: 'Three of four named in a day and a half. This is why the box is worth doing.' },
      { author: 'dev', hoursAfter: 50, message: 'Forty more scanned this weekend. There is one of a pitch with actual grass on it that will upset Gerry.' },
      { author: 'gerry', hoursAfter: 55, message: 'That was 1996. Nothing has drained since.' },
    ],
  },
  {
    forum: 'media',
    author: 'deco',
    title: 'Clip: the save at 1-1 that nobody believes',
    daysAgo: 13,
    message: [
      'Somebody on the sideline got it on their phone, which is the only reason this exists.',
      '',
      'Watch the second one. The first one is fine. The second one is off my elbow and I have no idea how it stayed out.',
    ].join('\n'),
    replies: [
      { author: 'oisin', hoursAfter: 1, message: 'It hit you.' },
      { author: 'deco', hoursAfter: 2, quotes: 1, message: 'It hit me because I was there, which is the job.' },
      { author: 'marty', hoursAfter: 5, message: 'It is a very good save and he will be showing it at the awards night.' },
      { author: 'bram', hoursAfter: 9, message: 'Cut it to nine seconds and put it up properly, it deserves better than a shaky wide shot.' },
      { author: 'cormac', hoursAfter: 20, message: 'This has been sent to me by four different people, one of whom was Deco.' },
    ],
  },
  {
    forum: 'media',
    author: 'dev',
    title: 'Photos from Saturday, all four hundred of them',
    daysAgo: 13,
    message: [
      'Both games. The away one is mostly action and the seconds one is mostly the crowd, because the crowd was the story.',
      '',
      'Full resolution ones are there if you want to print anything. If you are in one and would rather not be, tell me and it is gone, no questions.',
    ].join('\n'),
    replies: [
      { author: 'bernie', hoursAfter: 2, message: 'The one of the bus is going in a frame. Fourteen faces and every one of them roaring.' },
      { author: 'cormac', hoursAfter: 5, message: 'There are eleven photos of my goal. It went in off my shin in all eleven.' },
      { author: 'hana', hoursAfter: 9, message: 'Sequence of the save is unbelievable. Four frames and you can see the ball change direction.' },
      { author: 'luca', hoursAfter: 14, message: 'Sent one home to my parents and my mother has asked whether this is a professional club. I did not correct her.' },
      { author: 'dev', hoursAfter: 30, message: 'Four hundred and twelve, culled to a hundred and ninety, and it still took me two evenings.' },
      { author: 'dara', hoursAfter: 44, message: 'They are on the club social accounts too, credited. This lad does it for nothing and has done for two years.' },
    ],
  },
  {
    forum: 'media',
    author: 'bram',
    title: 'Clipped the last round of week six',
    daysAgo: 5,
    message: [
      'Ninety seconds, no commentary, just the last round from Sunday.',
      '',
      'Sunny\'s face at the end is the whole clip. Everything else is context.',
    ].join('\n'),
    replies: [
      { author: 'sunny', hoursAfter: 2, message: 'I am asking, formally, for the right to be forgotten.' },
      { author: 'nova', hoursAfter: 4, message: 'Denied.' },
      { author: 'glitch', hoursAfter: 8, message: 'This is the best thing on the board and it is ninety seconds long.' },
      { author: 'wraith', hoursAfter: 20, message: 'Watched it four times. Still do not know how that was allowed to happen.' },
    ],
  },

  {
    forum: 'noticeboard',
    author: 'mira',
    title: 'Shoebox appeal: collection point is the clubhouse until the 30th',
    daysAgo: 55,
    message: [
      'Same as every year. Boxes in the clubhouse porch, anything at all is welcome, and there is a list of what they actually need on the wall beside them.',
      '',
      'Last year the club sent seventy-one boxes, which was the most in the parish by a distance and nobody made a fuss about it.',
    ].join('\n'),
    replies: [
      { author: 'nia', hoursAfter: 9, message: 'The U10 parents did fourteen between them last year. I will put it in the team thread.' },
      { author: 'ken', hoursAfter: 26, message: 'Board games night will do a box. We will overthink what goes in it, that is our contribution.' },
      { author: 'mira', hoursAfter: 300, message: 'Eighty-eight boxes. Thank you, all of you. The porch was unusable for a fortnight and it was worth it.' },
    ],
  },
  {
    forum: 'noticeboard',
    author: 'jt',
    title: 'Defibrillator and first aid training: two dates, everyone welcome',
    daysAgo: 42,
    message: [
      'Two sessions, two hours each, free, and you do not need to be a coach or a player or anything at all.',
      '',
      'There is a defibrillator on the clubhouse wall. Nineteen people in this club know how to use it. That number should be a hundred and it costs us nothing to make it so.',
      '',
      'Reply with which date suits and I will put you down.',
    ].join('\n'),
    replies: [
      { author: 'bernie', hoursAfter: 1, message: 'The first date. Should have done this years ago.' },
      { author: 'zoe', hoursAfter: 3, message: 'First date for me too, and I will bring two of the other juvenile coaches.' },
      { author: 'gerry', hoursAfter: 8, message: 'Second one. I am at that pitch on my own most mornings, which I have thought about more than once.' },
      { author: 'aoife', hoursAfter: 20, message: 'Second. I am not even a member yet, is that all right?' },
      { author: 'jt', hoursAfter: 21, quotes: 4, message: 'Especially all right. Come.' },
      { author: 'jt', hoursAfter: 200, message: 'Forty-six people across the two nights. That is a genuinely different club to the one that had nineteen.' },
    ],
  },
  {
    forum: 'noticeboard',
    author: 'admin',
    title: 'Clubhouse wifi has a new password',
    daysAgo: 29,
    message: [
      'It is on the card behind the bar and on the notice by the door. Not posting it here because this board is public and the wifi is not.',
      '',
      'The old one had been the same since 2019 and was known to at least one entire opposing team.',
    ].join('\n'),
    replies: [
      { author: 'frank', hoursAfter: 4, message: 'It was known to the whole village. My son has never asked me for it once.' },
      { author: 'cormac', hoursAfter: 20, message: 'Everyone in my year knows the old one. Nobody has ever been in the clubhouse.' },
    ],
  },
  {
    forum: 'noticeboard',
    author: 'kev',
    title: 'Lost: navy gear bag, initials on the strap',
    daysAgo: 22,
    message: [
      'Left in the far dressing room two Saturdays ago. Navy, initials D.M. written on the strap in marker, boots and a set of gloves in it.',
      '',
      'Not mine — I am posting it for somebody who is not on here. If it turned up in your car after the away game, that is where it came from.',
    ].join('\n'),
    replies: [
      { author: 'oisin', hoursAfter: 20, message: 'There is a navy bag in the boot of the minibus that is not anybody\'s. Will check the strap tonight.' },
      { author: 'oisin', hoursAfter: 30, message: 'D.M. on the strap. Found. It has been in the minibus for a fortnight.' },
      { author: 'kev', hoursAfter: 33, message: 'Reunited. That is the second thing the minibus has quietly eaten this season.' },
    ],
  },
  {
    forum: 'noticeboard',
    author: 'nia',
    title: 'Anyone driving to Ennis on Saturday morning?',
    daysAgo: 21,
    message: [
      'Looking for a lift for the blitz — my car is in the garage until Monday and mine is playing.',
      '',
      'Happy to pay for the diesel and happy to bring the flask that everyone pretends they do not want.',
    ].join('\n'),
    replies: [
      { author: 'donal', hoursAfter: 2, message: 'I am going and I have two seats. Flask is compulsory.' },
      { author: 'nia', hoursAfter: 3, message: 'Perfect, thank you. Flask is a promise.' },
      { author: 'bernie', hoursAfter: 9, message: 'For future reference there is a lifts thread for every juvenile fixture in Events — you will get an answer in ten minutes in there.' },
    ],
  },
  {
    forum: 'noticeboard',
    author: 'siobhan',
    title: 'Volunteers: two hours on a Saturday morning, and that is the whole ask',
    daysAgo: 17,
    message: [
      'We need four people for two hours on Saturday mornings, on a rota, so it works out at about once every six weeks.',
      '',
      'It is: open up, put the nets up, make tea, take the money at the gate, close the shutter. It is not skilled and it is not a committee position and nobody will ask you to do anything else, which I know is the fear.',
    ].join('\n'),
    replies: [
      { author: 'petra', hoursAfter: 3, message: 'I will do it. I have been coming to games for a year and doing nothing and feeling slightly guilty about it.' },
      { author: 'sam', hoursAfter: 6, message: 'Me. I am there anyway.' },
      { author: 'luca', hoursAfter: 9, message: 'Me, on the weeks I am not playing.' },
      { author: 'aoife', hoursAfter: 26, message: 'And me. That is four in a day, which I suspect says something about how the ask was worded.' },
      { author: 'siobhan', hoursAfter: 30, quotes: 4, message: 'It does. Twelve years of "we need volunteers" got us nothing. "Two hours, once every six weeks, here is exactly what it is" got us four in a day.' },
    ],
  },
  {
    forum: 'noticeboard',
    author: 'tomas',
    title: 'Anyone with a trailer free on Sunday?',
    daysAgo: 12,
    message: [
      'Need to shift the old goals to the recycling centre and they will not go in anything I own.',
      '',
      'Half an hour of work, two people, and I will buy the lunch.',
    ].join('\n'),
    replies: [
      { author: 'gerry', hoursAfter: 3, message: 'I have a trailer and I want those goals gone more than you do.' },
      { author: 'frank', hoursAfter: 8, message: 'I will be the second pair of hands. Lunch is non-negotiable.' },
      { author: 'tomas', hoursAfter: 30, message: 'Done in forty minutes and the far corner of the car park is a car park again.' },
    ],
  },
  {
    forum: 'noticeboard',
    author: 'petra',
    title: 'Found: keys with a bottle opener on the ring',
    daysAgo: 10,
    message: [
      'On the wall outside the clubhouse after the quiz. Two house keys, a car key, and a bottle opener with a crest on it that I do not recognise.',
      '',
      'Behind the bar now. Describe the crest and they are yours.',
    ].join('\n'),
    replies: [
      { author: 'frank', hoursAfter: 2, message: 'It is a darts crest and they are mine and I have been going out of my mind since Friday.' },
      { author: 'petra', hoursAfter: 4, message: 'Correct. Collect them from Marie behind the bar.' },
      { author: 'ken', hoursAfter: 20, message: 'A man who loses his keys at a table quiz and does not notice until Sunday is a man who enjoyed the table quiz.' },
    ],
  },
  {
    forum: 'noticeboard',
    author: 'gerry',
    title: 'The bins after Saturday. Please.',
    daysAgo: 3,
    message: [
      'Three bins, all of them empty at two o\'clock, all of them overflowing by five, and about forty cups on the ground behind the far goal.',
      '',
      'I am not going to give out. I am going to point out that the same six people tidy up after every single home game and none of them played in it.',
    ].join('\n'),
    replies: [
      { author: 'marty', hoursAfter: 1, message: 'Squad will do the far side after the game on Saturday. It should never have been anybody else\'s job.' },
      { author: 'hana', hoursAfter: 3, message: 'Ladies squad will do the near side and the clubhouse. Ten minutes with twenty of us.' },
      { author: 'cormac', hoursAfter: 6, message: 'The U16s will do the car park. Some of us are the ones dropping the cups, in fairness.' },
      { author: 'gerry', hoursAfter: 9, message: 'Well now I feel like a curmudgeon and the place will be spotless. Both of those are fine.' },
      { author: 'siobhan', hoursAfter: 26, message: 'Every club has this thread and most of them have it as a row. This one took nine hours and three teams volunteered. Noted for the AGM.' },
    ],
  },

  {
    forum: 'market',
    author: 'tomas',
    title: 'Club shop clear-out: last season\'s training tops, €10',
    daysAgo: 60,
    prefix: 'sold',
    message: [
      'Thirty-odd training tops from last season\'s design, all sizes from small to XXL, €10 each and every cent goes to the pitch fund.',
      '',
      'They are perfectly good tops. The only thing wrong with them is that they say last season on the sleeve.',
    ].join('\n'),
    replies: [
      { author: 'paudie', hoursAfter: 2, message: 'Two XL. I do not care what the sleeve says.' },
      { author: 'bernie', hoursAfter: 5, message: 'Three smalls for the children, who do care what the sleeve says, and will get over it.' },
      { author: 'luca', hoursAfter: 11, message: 'One medium. It is the first club top I have ever owned and I am delighted with it.' },
      { author: 'frank', hoursAfter: 26, message: 'Take the last of them and put them in the raffle at the quiz, they will go for more than a tenner.' },
      { author: 'tomas', hoursAfter: 74, message: 'All gone. €340 to the pitch fund, and four went in the raffle for €15 each, so Frank was right and I hate it.' },
    ],
  },
  {
    forum: 'market',
    author: 'pixel',
    title: 'Graphics card, works fine, upgrading',
    daysAgo: 44,
    prefix: 'sold',
    message: [
      'Selling because I upgraded, not because there is anything wrong with it. Three years old, never overclocked, and it has been in a case with actual airflow.',
      '',
      '€120 and I will drop it anywhere within an hour of the clubhouse, or post it at cost.',
    ].join('\n'),
    replies: [
      { author: 'glitch', hoursAfter: 2, message: 'Is it enough for the Tuesday runs at 1440? That is my whole use case.' },
      { author: 'pixel', hoursAfter: 3, quotes: 1, message: 'Comfortably. It is what I have been doing them on for three years.' },
      { author: 'cormac', hoursAfter: 8, message: 'If Glitch does not take it, I will, and I will need three weeks to convince my father.' },
      { author: 'glitch', hoursAfter: 20, message: 'Taking it. Sorry Cormac.' },
      { author: 'pixel', hoursAfter: 30, message: 'Sold and posted. Cormac, I have a spare cooler you can have for nothing when you get one.' },
    ],
  },
  {
    forum: 'market',
    author: 'frank',
    title: 'Half a home gym, collection only, and I mean collection',
    daysAgo: 35,
    prefix: 'forsale',
    message: [
      'Bench, a bar, and about 80kg of plates. €90 the lot.',
      '',
      'It is in a shed at the back of the house and it weighs what 80kg of plates weighs. Bring somebody who lifts, which was the plan when I bought it.',
    ].join('\n'),
    replies: [
      { author: 'shay', hoursAfter: 4, message: 'Interested. Can collect Sunday with the van.' },
      { author: 'jt', hoursAfter: 9, message: 'If nobody takes it, the club could do with a bench in the gym room. I will ask the committee.' },
      { author: 'shay', hoursAfter: 26, message: 'Took it. Two of us and it still took forty minutes.' },
      { author: 'frank', hoursAfter: 30, message: 'And that is how a home gym works. Six weeks of use, four years of storage, one afternoon of regret for somebody else.' },
    ],
  },
  {
    forum: 'market',
    author: 'oisin',
    title: 'Boots, size 9, worn twice',
    daysAgo: 30,
    prefix: 'forsale',
    message: [
      'Bought them, wore them twice, they are not for me. Firm ground studs, no marks on them at all.',
      '',
      '€45 or nearest. In the clubhouse most Tuesdays and Thursdays.',
    ].join('\n'),
    replies: [
      { author: 'cormac', hoursAfter: 6, message: 'What are they like on the far pitch when it is soft? That is all I care about.' },
      { author: 'oisin', hoursAfter: 8, quotes: 1, message: 'Useless. That is why I wore them twice.' },
      { author: 'luca', hoursAfter: 20, message: 'I will take them for the hall on Thursdays. €45 is fine.' },
      { author: 'oisin', hoursAfter: 30, message: 'Gone. Sold to a man who has understood exactly what he is buying.' },
    ],
  },
  {
    forum: 'market',
    author: 'olu',
    title: 'Wanted: five-a-side goals that are not falling apart',
    daysAgo: 27,
    prefix: 'wanted',
    message: [
      'The two we have in the hall are held together with cable ties and hope. Looking for a pair of freestanding ones, secondhand is completely fine.',
      '',
      'Thursday group would go halves with the club if the club is interested.',
    ].join('\n'),
    replies: [
      { author: 'gerry', hoursAfter: 5, message: 'The old juvenile ones are in the container and they are sound. They just need new nets.' },
      { author: 'olu', hoursAfter: 8, quotes: 1, message: 'That is a much better answer than buying anything. Can I get at them Saturday?' },
      { author: 'gerry', hoursAfter: 9, message: 'I will open the container at ten.' },
      { author: 'olu', hoursAfter: 74, message: 'Two goals, two new nets, €38 total. Cancelling the whole fundraising plan I had in my head.' },
    ],
  },
  {
    forum: 'market',
    author: 'bernie',
    title: 'Child\'s bike, 20 inch, grown out of',
    daysAgo: 18,
    prefix: 'forsale',
    message: [
      'Twenty inch wheels, blue, one careful owner and one careless one. Brakes are good, tyres are good, there is a sticker on the frame that is not coming off.',
      '',
      '€40, or free to anyone who needs it for a child and would rather not say so publicly — message me and it is yours, no questions.',
    ].join('\n'),
    replies: [
      { author: 'mira', hoursAfter: 5, message: 'That last line is a lovely thing to put in a for-sale post and more people should do it.' },
      { author: 'nia', hoursAfter: 20, message: 'Took it. Thank you Bernie.' },
      { author: 'bernie', hoursAfter: 26, message: 'Gone to a good home. There are two more bikes in my shed if anyone is in the same boat.' },
    ],
  },
  {
    forum: 'market',
    author: 'sunny',
    title: 'Wanted: a decent mic, under €60',
    daysAgo: 12,
    prefix: 'wanted',
    message: [
      'Mine has been described on the Tuesday call as "a man shouting into a biscuit tin", which is fair.',
      '',
      'Under €60, secondhand is fine, does not need to be fancy. Just needs to not be a biscuit tin.',
    ].join('\n'),
    replies: [
      { author: 'bram', hoursAfter: 2, message: 'I have a spare that is genuinely fine and you can have it for nothing. It is in a box under the desk doing no good to anybody.' },
      { author: 'sunny', hoursAfter: 4, message: 'That is very kind. Are you sure?' },
      { author: 'bram', hoursAfter: 5, quotes: 2, message: 'Completely. The condition is that you stop apologising for your audio every single week.' },
      { author: 'wraith', hoursAfter: 20, message: 'Seconded, and I would have paid the €60 myself to make that happen.' },
      { author: 'sunny', hoursAfter: 48, message: 'Arrived, plugged in, and apparently I have a voice. Thanks Bram.' },
    ],
  },
  {
    forum: 'market',
    author: 'petra',
    title: 'Two tickets for the final, face value only',
    daysAgo: 5,
    prefix: 'forsale',
    message: [
      'Two together, face value, because we cannot go any more and I am not having them wasted.',
      '',
      '**Face value.** If you message me offering more I will give them to the next person who does not.',
    ].join('\n'),
    replies: [
      { author: 'shay', hoursAfter: 2, message: 'Would take them at face value if they are still going. Can collect tonight.' },
      { author: 'petra', hoursAfter: 3, message: 'They are yours. See you at the clubhouse at eight.' },
      { author: 'frank', hoursAfter: 9, message: 'Face value only is the correct way to do this and I wish every club in the country would copy it.' },
      {
        author: 'spambot',
        hoursAfter: 106,
        message:
          'BEST TICKETS AVAILABLE ALL MATCHES cheap price guaranteed delivery visit our store now http://example.invalid/tickets',
      },
    ],
  },
  {
    forum: 'market',
    author: 'spambot',
    title: 'cheap replica jerseys all clubs best price fast shipping',
    daysAgo: 0,
    visibility: 'unapproved',
    message:
      'official quality replica jerseys all clubs all sizes cheapest price online fast worldwide shipping order now http://example.invalid/jerseys',
  },

  {
    forum: 'offtopic',
    author: 'ken',
    title: 'Board games night, second Friday, and yes that kind of board',
    daysAgo: 70,
    message: [
      'Back room of the clubhouse, second Friday of the month, half seven. No skill required and there is always something short for anyone who arrives late.',
      '',
      'It started with four of us and a box of games from my attic and there were nineteen people at the last one, which is more than the seconds got the same weekend.',
    ].join('\n'),
    replies: [
      { author: 'petra', hoursAfter: 4, message: 'Can confirm. I came once to be polite and I have not missed one since.' },
      { author: 'cormac', hoursAfter: 11, message: 'Is there an age thing? Two of us from the U16s would come.' },
      { author: 'ken', hoursAfter: 12, quotes: 2, message: 'No age thing at all, and the fourteen-year-old who came in October beat everybody at everything.' },
      { author: 'rook', hoursAfter: 30, message: 'This is what I mean about this place. There is a chess ladder, a games night, a quiz and a five-a-side and none of them are the actual sport.' },
      { author: 'siobhan', hoursAfter: 50, message: 'The actual sport pays for the room the rest of them happen in, and the rest of them are why the room is full. Both halves matter.' },
    ],
  },
  {
    forum: 'offtopic',
    author: 'mira',
    title: 'Storm damage around the village — post what you see',
    daysAgo: 60,
    message: [
      'Tree down on the Ballyquin road just past the bridge, and the wall by the pitch has lost about four metres.',
      '',
      'If you are out and about, post what you find and I will pass the list to the council in one go rather than fourteen phone calls.',
    ].join('\n'),
    replies: [
      { author: 'gerry', hoursAfter: 1, message: 'Wall at the pitch is my problem and it is already blocked off. Nobody go near the far corner.' },
      { author: 'sam', hoursAfter: 3, message: 'Two trees down in the lane behind the school, passable on foot, not in a car.' },
      { author: 'nia', hoursAfter: 6, message: 'Power out on the whole terrace since half four. Reported it, they say Tuesday.' },
      { author: 'rosa', hoursAfter: 20, message: 'Sent the list in. Nine items, one phone call, and they were genuinely grateful to get it in one go.' },
      { author: 'mira', hoursAfter: 90, message: 'Tree gone, lane clear, wall is still a wall-shaped suggestion. Two out of three.' },
    ],
  },
  {
    forum: 'offtopic',
    author: 'tomas',
    title: 'What is everyone else paying for a set of jerseys?',
    daysAgo: 50,
    poll: {
      question: 'Per set of 16, printed, what does your club pay?',
      options: [
        { label: 'Under €400', voters: ['olu', 'ken'] },
        { label: '€400–600', voters: ['tomas', 'marty', 'hana', 'donal'] },
        { label: '€600–800', voters: ['siobhan', 'noelle', 'zoe'] },
        { label: 'Over €800', voters: ['mairead'] },
        { label: 'No idea, somebody else does it', voters: ['paudie', 'frank', 'deco', 'shay', 'sam', 'member'] },
      ],
      closesInDays: null,
    },
    message: [
      'Asking because we have just changed supplier and I genuinely do not know if we are being done or getting a deal.',
      '',
      'Include printing and numbers, exclude the goalkeeper set, and if you are in a different sport entirely, say so — I am curious whether the rest of you get the same treatment.',
    ].join('\n'),
    replies: [
      { author: 'olu', hoursAfter: 4, message: 'The five-a-side lot bought sixteen plain ones online for €310 and printed the numbers ourselves badly. It shows and we do not care.' },
      { author: 'mairead', hoursAfter: 9, message: 'Over €800 for the juveniles, because sixteen children is actually four different sizes and two reorders.' },
      { author: 'hana', hoursAfter: 20, message: 'Ladies set was €540 and the sponsor covered €400 of it. Ask your sponsors — ours offered before we did.' },
      { author: 'tomas', hoursAfter: 30, message: 'So we are mid-table and the honest answer is nobody knows what anybody pays, which is exactly how it stays expensive.' },
      { author: 'nova', hoursAfter: 50, message: 'For contrast: our tournament "kit" is a shared colour on a website and costs nothing. I am aware this is not the same problem.' },
    ],
  },
  {
    forum: 'offtopic',
    author: 'deco',
    title: 'The chipper after the match: a definitive ranking',
    daysAgo: 42,
    message: [
      'Four chippers within reach of the away games we play. This is the ranking and it is not up for debate, though I accept it will be.',
      '',
      '1. The one in Ennis, no contest.',
      '2. The one on the Ballyquin road.',
      '3. The one at the roundabout, which is fine and knows it.',
      '4. The one by the pitch, which I love and which is objectively the worst.',
    ].join('\n'),
    replies: [
      { author: 'oisin', hoursAfter: 1, message: 'The one at the roundabout is second and you know it is second.' },
      { author: 'frank', hoursAfter: 3, message: 'Putting the local one last while saying you love it is the most club thing anyone has ever posted.' },
      { author: 'shay', hoursAfter: 8, message: 'Ennis first is correct and it is the only away trip anyone volunteers for.' },
      { author: 'cormac', hoursAfter: 14, message: 'The bus stopped at the roundabout one after the cup game and it was the best night of the season.' },
      { author: 'una', hoursAfter: 26, message: 'Nobody has mentioned the one that does the curry chips, which tells me none of you have been to the Thursday games.' },
      { author: 'deco', hoursAfter: 30, quotes: 5, message: 'I have made a mistake and I am amending the list.' },
    ],
  },
  {
    forum: 'offtopic',
    author: 'sam',
    title: 'Is anyone else\'s dog at every single home game',
    daysAgo: 33,
    message: [
      'Mine has been to more home games than most of the squad and knows exactly when half time is, because that is when the sandwiches happen.',
      '',
      'There were five dogs on the near side on Saturday. I think that is a club record.',
    ].join('\n'),
    replies: [
      { author: 'gerry', hoursAfter: 2, message: 'Five dogs, all on leads, all on the near side, no complaints from me. It is the ones off leads on the pitch that will start a war.' },
      { author: 'petra', hoursAfter: 6, message: 'Mine is terrified of the whistle and we have to stand behind the clubhouse for the first ten minutes.' },
      { author: 'bernie', hoursAfter: 14, message: 'The dogs are half the atmosphere. Do not let anyone tell you otherwise.' },
      { author: 'frank', hoursAfter: 20, message: 'Proposal: a dog of the year award at the awards night.' },
      { author: 'dara', hoursAfter: 26, quotes: 4, message: 'Denied by the committee, immediately reinstated by public demand. Nominations open.' },
    ],
  },
  {
    forum: 'offtopic',
    author: 'pixel',
    title: 'The tea in the clubhouse is a scandal',
    daysAgo: 24,
    message: [
      'I travelled four hours to be at the quiz and the tea was made in an urn that I believe predates the club.',
      '',
      'I am not asking for a coffee machine. I am asking for the urn to be looked at by a professional.',
    ].join('\n'),
    replies: [
      { author: 'frank', hoursAfter: 1, message: 'The urn is older than the club and it is staying.' },
      { author: 'rosa', hoursAfter: 4, message: 'The urn was donated in 1981 and there is a plaque. You are arguing with a plaque.' },
      { author: 'pixel', hoursAfter: 6, quotes: 2, message: 'I withdraw the complaint and I would like a photograph of the plaque.' },
      { author: 'ken', hoursAfter: 20, message: 'There is a real coffee machine in the back room on games night. This is a well-kept secret and I have just ruined it.' },
      { author: 'sam', hoursAfter: 30, message: 'The tea is bad and it is part of it. It would be worse if it were good.' },
    ],
  },
  {
    forum: 'offtopic',
    author: 'bernie',
    title: 'Recommend me a podcast for the drive to away games',
    daysAgo: 16,
    message: [
      'Two hours each way to Ennis and back with a car full of twelve-year-olds who have their own opinions about this.',
      '',
      'Needs to survive a back seat and not require concentration.',
    ].join('\n'),
    replies: [
      { author: 'ken', hoursAfter: 3, message: 'Anything with a quiz format. The children join in and it is over in twenty-minute chunks.' },
      { author: 'nia', hoursAfter: 9, message: 'We do audiobooks and the twelve-year-olds pretend to hate it for the first ten minutes every time.' },
      { author: 'luca', hoursAfter: 20, message: 'I put on a language one for the drive and now three of the seconds can order a coffee in Italian, badly.' },
      { author: 'bernie', hoursAfter: 44, message: 'Went with the quiz one. Two hours passed without a single argument about the radio. Revolutionary.' },
    ],
  },
  {
    forum: 'offtopic',
    author: 'glitch',
    title: 'There is a chess ladder now and I do not know how it happened',
    daysAgo: 8,
    message: [
      'Somebody made a joke about a chess ladder on Tuesday. There are now twenty-two people in it, a spreadsheet, and an argument about time controls.',
      '',
      'Two of them are the U16s and one of them is Gerry, who has beaten everybody.',
    ].join('\n'),
    replies: [
      { author: 'gerry', hoursAfter: 2, message: 'I played for the county at seventeen. Nobody asked.' },
      { author: 'ken', hoursAfter: 4, message: 'Gerry, the games night is the second Friday and I am begging you.' },
      { author: 'cormac', hoursAfter: 8, message: 'I have lost to a man who cuts grass for a living and I have never been so comprehensively beaten at anything.' },
      { author: 'wraith', hoursAfter: 14, message: 'This club has a football team, a gaming crew, a quiz, a games night and now a chess ladder, and the chess ladder was invented by accident three days ago.' },
      { author: 'vex', hoursAfter: 26, message: 'It gets its own thread in Events next week and that is how everything here starts.' },
    ],
  },
]
