import type { DemoThread } from './types'

/**
 * Membership, support, feedback and moderation: the forums where the club talks
 * about itself. They are also where the board's own features get demonstrated
 * by somebody using them rather than by a paragraph in a document.
 */
export const RUNNING_THREADS: readonly DemoThread[] = [
  {
    forum: 'membership',
    author: 'noelle',
    title: 'How subs work, in plain English',
    daysAgo: 90,
    sticky: true,
    message: [
      'Pinned because I answer this eleven times every January.',
      '',
      '**Adult playing** covers the league registration, insurance, pitch hire and referees. It is the biggest one and roughly two-thirds of it goes straight back out to the league before we see it.',
      '',
      '**Adult social** is the same membership without the playing registration. You get a vote at the AGM, the clubhouse, and every event we run.',
      '',
      '**Juvenile** covers a child for a full season, including the camp week at a reduced rate. **Family** covers everybody in a household and works out cheaper from the second child.',
      '',
      '**Supporters** is the optional one on top. It is not a membership — it is people choosing to put a few euro a month in, and it is currently paying for the juvenile jerseys.',
      '',
      'Nobody has ever been turned away for not being able to pay. If that is you, message me and it is dealt with quietly and nobody else knows.',
    ].join('\n'),
    replies: [
      { author: 'bernie', hoursAfter: 5, message: 'That last line should be in bold and on the front page. It is the single most important sentence this club has written down.' },
      { author: 'siobhan', hoursAfter: 9, message: 'It has been true for fifty years and written down for one. That is on us.' },
      { author: 'luca', hoursAfter: 26, message: 'Joining a club in a country you have just moved to and not knowing what any of it costs is genuinely stressful. This post would have saved me a fortnight of wondering.' },
      { author: 'member', hoursAfter: 74, message: 'What is the actual difference between Supporters and just paying more? Is it a badge?' },
      {
        author: 'noelle',
        hoursAfter: 80,
        quotes: 4,
        message:
          'It is a badge, honestly. And a coloured name, and the knowledge that the juveniles have jerseys. It buys nothing you cannot already do — we deliberately kept it that way, because a club where the people who pay more can see more is not a club.',
      },
    ],
  },
  {
    forum: 'membership',
    author: 'tomas',
    title: 'Kit order: sizes, form and the deadline I will actually enforce',
    daysAgo: 130,
    message: [
      'Order form is open until the end of the month. Sizes run small — if you are between two, take the bigger one, and I say that every year and every year eleven people ignore me.',
      '',
      'Numbers are €4 extra and names are €6. Juvenile sets come with the number included because the alternative is chaos.',
    ].join('\n'),
    replies: [
      { author: 'shay', hoursAfter: 4, message: 'Took the bigger one. Learned my lesson in 2023.' },
      { author: 'zoe', hoursAfter: 9, message: 'Nineteen U10s, nineteen forms, all in by Friday. I have made it a competition and they do not know.' },
      { author: 'oisin', hoursAfter: 20, message: 'Can I get the same number as last year or is that a whole thing?' },
      { author: 'tomas', hoursAfter: 22, quotes: 3, message: 'It is not a whole thing. It is a spreadsheet and you are on it. Nine, as always.' },
      { author: 'paudie', hoursAfter: 50, message: 'Ordered a medium out of hope. Will report back in shame.' },
      { author: 'tomas', hoursAfter: 200, message: 'Order in, and eleven people ordered too small. Same eleven as last year, near enough.' },
    ],
  },
  {
    forum: 'membership',
    author: 'bernie',
    title: 'Can we do a family rate?',
    daysAgo: 240,
    poll: {
      question: 'Should a family rate replace per-child juvenile subs?',
      options: [
        { label: 'Yes, and cap it at two children', voters: ['noelle', 'zoe', 'donal'] },
        { label: 'Yes, uncapped for a household', voters: ['bernie', 'mairead', 'ellie', 'nia', 'siobhan', 'hana', 'jt'] },
        { label: 'No, keep it per child', voters: ['frank'] },
        { label: 'No strong view, whatever the treasurer says', voters: ['paudie', 'gerry', 'tomas', 'marty', 'ken', 'member'] },
      ],
      closesInDays: null,
    },
    message: [
      'Three children playing costs me more than my own membership, my husband\'s and the two of us going to everything for a year.',
      '',
      'I am not pleading poverty and we will pay it. I am saying that the family down the road with three children looked at the number and did not join, and that is the club\'s loss more than theirs.',
    ].join('\n'),
    replies: [
      { author: 'noelle', hoursAfter: 6, message: 'The maths, honestly: a household cap costs us about €1,400 a year at current numbers. It is not nothing and it is not fatal.' },
      { author: 'frank', hoursAfter: 11, message: 'I voted no and I will say why rather than sulking: the same argument gets made for the social membership every year and we cannot discount everything. Happy to be outvoted.' },
      { author: 'siobhan', hoursAfter: 20, message: 'That is exactly how to disagree with something. Noted, and it will get said at the AGM by me rather than being a rumour.' },
      { author: 'mairead', hoursAfter: 30, message: 'Four families in the juvenile section have more than two playing. Four. This is not a flood.' },
      { author: 'ellie', hoursAfter: 74, message: 'We are one of the four and we joined in spite of the price rather than because it was fine.' },
      { author: 'noelle', hoursAfter: 700, message: 'Passed at the AGM, uncapped, in for this season. Eleven households on it already and two of them are new members.' },
    ],
  },
  {
    forum: 'membership',
    author: 'siobhan',
    title: 'Where the pitch fund money went, in numbers',
    daysAgo: 88,
    message: [
      'Because "the pitch fund" has become a thing people put money into without ever being told where it goes.',
      '',
      '- Quiz nights, two of them: **€2,310**',
      '- The July friendly gate: **€160**',
      '- Club shop clear-out: **€340**',
      '- Supporters memberships: **€1,180**',
      '- Straight donations, including one anonymous €500: **€890**',
      '',
      'Out: **€1,900** on the far-corner drainage patch that lasted one winter, **€680** on the mower service, and **€240** on nets.',
      '',
      'Sitting at **€6,200**, and the full drainage job is €14,000. That is the whole picture and it is why the AGM matters this year.',
    ].join('\n'),
    replies: [
      { author: 'gerry', hoursAfter: 3, message: 'The €1,900 patch was my call and it did not work. Worth saying out loud so nobody repeats it.' },
      { author: 'frank', hoursAfter: 8, message: 'A committee that posts a failed €1,900 spend in public is a committee I will keep giving money to.' },
      { author: 'noelle', hoursAfter: 14, message: 'Every figure in that post comes off the same account and I will show the statements to anybody who asks, at any time.' },
      { author: 'tomas', hoursAfter: 26, message: 'The grant application closes in April and would cover half of the fourteen. I am doing it with Noelle and we could use a third pair of eyes.' },
      { author: 'rosa', hoursAfter: 30, message: 'I have written eleven of these for the community centre. Send it to me before you submit it.' },
      { author: 'siobhan', hoursAfter: 50, message: 'And that reply is worth more than the anonymous €500. Thank you.' },
    ],
  },
  {
    forum: 'membership',
    author: 'tomas',
    title: 'Sponsorship: the shirt is spoken for, the shorts are not',
    daysAgo: 70,
    message: [
      'The garage has taken the shirt front for another two seasons, which is the eleventh year and they have never once asked for anything in return.',
      '',
      'Still available: shorts, the juvenile set, the sideline board, and the seconds\' shirt. Prices are on the sheet in the clubhouse and they are negotiable, especially for anything that keeps a local business going.',
      '',
      'If you work somewhere that might, ask them. It is a much easier conversation from an employee than from me.',
    ].join('\n'),
    replies: [
      { author: 'luca', hoursAfter: 9, message: 'My employer does community sponsorship and nobody has ever asked them. I will bring it to them Monday.' },
      { author: 'hana', hoursAfter: 20, message: 'The hairdresser did the ladies set for two years and got more business out of it than she expected. Worth mentioning to anyone hesitating.' },
      { author: 'luca', hoursAfter: 200, message: 'They said yes. Seconds\' shirt, two seasons, and they are sending someone to the awards night.' },
      { author: 'tomas', hoursAfter: 210, message: 'Eleven years of me asking and the new lad gets one in a fortnight. Delighted and mildly insulted.' },
    ],
  },
  {
    forum: 'membership',
    author: 'member',
    title: 'What does the Supporters thing actually get you?',
    daysAgo: 26,
    message: [
      'Saw it on the subs page. It is a few euro a month and I cannot work out from the description whether I am buying something or just donating.',
      '',
      'Happy to donate. Would just like to know which one it is.',
    ].join('\n'),
    replies: [
      {
        author: 'noelle',
        hoursAfter: 2,
        message:
          'You are donating, with a badge attached. Concretely: your name is a different colour, there is a badge beside it, and the money is ring-fenced for the juvenile section. That is the whole of it — no forums you cannot otherwise see, no queue you skip.',
      },
      { author: 'admin', hoursAfter: 4, message: 'And it stops on its own when you stop paying, without anybody having to remember to take it off you. That was the part that made it worth doing at all.' },
      { author: 'member', hoursAfter: 9, message: 'That is a straight answer, thank you. I will do it when the subs come round in January.' },
      { author: 'frank', hoursAfter: 26, message: 'Do. Everybody I know who signed up said it was only for the badge and then quietly kept paying for two years.' },
    ],
  },
  {
    forum: 'membership',
    author: 'admin',
    title: 'Some of you got two renewal reminders. Sorry.',
    daysAgo: 40,
    message: [
      'If you got the renewal email twice on Tuesday, that was me. I ran the reminder task by hand after it had already run on schedule, because I did not check whether it had already run on schedule.',
      '',
      'Nobody was charged twice. Nothing is wrong with your membership. It was two emails and one red face.',
    ].join('\n'),
    replies: [
      { author: 'paudie', hoursAfter: 1, message: 'I got three.' },
      { author: 'admin', hoursAfter: 2, quotes: 1, message: 'You got three because you are also in the juvenile parents list. That one is on the list, not on me, and I have fixed it.' },
      { author: 'petra', hoursAfter: 9, message: 'Two emails from a club that is chasing €40 is not a scandal. Two emails from anywhere else and I would have unsubscribed.' },
      { author: 'noelle', hoursAfter: 20, message: 'Renewals are at 84% which is the highest we have ever been at this point in the year, so the emails are doing their job even when they do it twice.' },
    ],
  },
  {
    forum: 'membership',
    author: 'noelle',
    title: 'Lapsed members: we are not chasing you, but the door is open',
    daysAgo: 15,
    message: [
      'Thirty-one people who were members last year have not renewed. I am not going to ring any of you, because being rung about money is horrible.',
      '',
      'What I will say once, here: if you stopped because of the cost, see the pinned post. If you stopped because you stopped playing, the social membership is €25 and gets you the same clubhouse and the same vote.',
      '',
      'And if you stopped because something happened here that put you off, I would genuinely like to know, and you can message me or Siobhán and it goes no further.',
    ].join('\n'),
    replies: [
      { author: 'siobhan', hoursAfter: 4, message: 'That third one is not a formality. Two people told us last year and both of them were right, and one of the things they raised is why the match thread rules exist now.' },
      { author: 'frank', hoursAfter: 11, message: 'Renewed three lads from the over-35s by forwarding this to them. None of them had realised the social one existed.' },
      { author: 'noelle', hoursAfter: 74, message: 'Nine of the thirty-one renewed in a week and one of them is back playing. Worth writing.' },
    ],
  },

  {
    forum: 'support',
    author: 'admin',
    title: 'People were getting logged out every couple of hours. Fixed.',
    daysAgo: 45,
    prefix: 'solved',
    message: [
      'Four people told me they were being logged out during the day and I could not reproduce it on my own account, which is the worst kind of bug.',
      '',
      'Cause: I put a second web container in when the board got busy on match days, and the two of them did not share the same signing secret. A session made by one was gibberish to the other, so every second request looked like a stranger.',
      '',
      'Same secret on both, redeployed, gone. Writing it down because it took me two evenings and the symptom points nowhere near the cause.',
    ].join('\n'),
    replies: [
      { author: 'paudie', hoursAfter: 3, message: 'I thought I was doing something wrong and had stopped mentioning it. That is the real cost of a bug like that.' },
      { author: 'rosa', hoursAfter: 9, message: 'Same, and I had started keeping the tab open all day so I would not have to log in again.' },
      { author: 'admin', hoursAfter: 11, quotes: 2, message: 'That is exactly the behaviour that hides it — the people it affects stop reporting it and work around it. Please always tell me, even when you assume it is you.' },
      { author: 'vex', hoursAfter: 30, message: 'Two containers on match day is a nice problem for a club board to have, in fairness.' },
    ],
  },
  {
    forum: 'support',
    author: 'rosa',
    title: 'Search finds nothing for a thread I am looking straight at',
    daysAgo: 34,
    prefix: 'solved',
    message: [
      'Searching for "shoebox" gives me nothing, and the shoebox thread is right there on the noticeboard with my name on it.',
      '',
      'Everything else about the site is completely normal. It is only search.',
    ].join('\n'),
    replies: [
      {
        author: 'admin',
        hoursAfter: 1,
        message:
          'That will be me. I moved the board to the new server on Sunday and restored from a dump, and the search index does not always come across in one — the posts are all there, the thing that makes them findable is not.\n\nRunning the reindex now. It works through the whole board in the background, so it will start finding things again gradually rather than all at once.',
      },
      { author: 'rosa', hoursAfter: 3, message: 'Shoebox thread is back. So are the minutes from 2019, which I could not find last week either and had assumed I had imagined.' },
      { author: 'admin', hoursAfter: 5, message: 'Ninety thousand posts in about twelve minutes. Everything is findable again, including the things you had given up on.' },
      { author: 'mira', hoursAfter: 26, message: 'Worth knowing that search covers the old parish notices too. I found a 2017 hall booking argument that I would rather have left buried.' },
    ],
  },
  {
    forum: 'support',
    author: 'paudie',
    title: 'Cannot log in on the phone, grand on the laptop',
    daysAgo: 20,
    prefix: 'solved',
    message: [
      'Same password. Works on the laptop every time, fails on the phone every time. I have typed it slowly. I have typed it very slowly.',
    ].join('\n'),
    replies: [
      { author: 'moderator', hoursAfter: 1, message: 'Is the phone putting a capital on the first letter? It does that in the username box and the username is not the problem, the capital is.' },
      { author: 'paudie', hoursAfter: 2, message: 'It is putting a capital on it.' },
      { author: 'paudie', hoursAfter: 2, message: 'I am in. Twenty-five years of technology and I am beaten by an automatic capital letter.' },
      { author: 'moderator', hoursAfter: 4, quotes: 2, message: 'You are the fourth. It is the single most common thing anyone asks me here.' },
      { author: 'admin', hoursAfter: 20, message: 'Fourth is enough. Names are matched without case now, so the capital does not matter any more.' },
      { author: 'frank', hoursAfter: 30, message: 'A support thread that ends with the software changing is a good day for everybody.' },
    ],
  },
  {
    forum: 'support',
    author: 'cormac',
    title: 'Is there an app?',
    daysAgo: 17,
    message: [
      'Not complaining, the site is fine on the phone. Just asking whether there is an app I am missing.',
    ].join('\n'),
    replies: [
      {
        author: 'admin',
        hoursAfter: 4,
        message:
          'There is not, and there will not be. What there is: add it to your home screen from the browser menu and it opens like one, full screen, no address bar. That gets you 95% of an app for none of the maintenance.',
      },
      { author: 'cormac', hoursAfter: 6, message: 'Did that. It is an app now as far as I am concerned.' },
      { author: 'bernie', hoursAfter: 20, message: 'Somebody should put those five words in the pinned post because I did not know you could do that.' },
      { author: 'admin', hoursAfter: 26, quotes: 3, message: 'Added, with a screenshot for both kinds of phone.' },
    ],
  },
  {
    forum: 'support',
    author: 'bernie',
    title: 'My notifications have gone quiet',
    daysAgo: 14,
    message: [
      'I used to get an email when the U12 thread got a reply and I have had none for about a fortnight. The thread is definitely getting replies.',
      '',
      'Have I turned something off by accident?',
    ].join('\n'),
    replies: [
      { author: 'moderator', hoursAfter: 2, message: 'Check the subscription on the thread first — it is at the top of the thread and it will say "watching" or "not watching". A reply from a phone sometimes gets sent with the box unticked.' },
      { author: 'bernie', hoursAfter: 3, message: 'It says not watching. I did not do that on purpose.' },
      { author: 'admin', hoursAfter: 5, message: 'You did, though not knowingly — replying with "subscribe" unticked replaces the old setting. It is a bad default and I have changed it: replying now leaves an existing subscription alone.' },
      { author: 'bernie', hoursAfter: 9, message: 'Back to normal, and I now know what that box does after a year of ignoring it.' },
      { author: 'mairead', hoursAfter: 26, message: 'Two other parents have said the same thing this month. That change will save me a lot of "did you not see the thread".' },
    ],
  },
  {
    forum: 'support',
    author: 'sam',
    title: 'How do I turn the emails off without leaving?',
    daysAgo: 9,
    message: [
      'I am on here every day. I do not need to be told by email that a thread I read an hour ago has a reply.',
      '',
      'I do want the ones about my own account and the fixture cancellations. Is that a setting or is it all or nothing?',
    ].join('\n'),
    replies: [
      { author: 'moderator', hoursAfter: 2, message: 'It is a setting, in your account under notifications, and it splits about six ways. Turn off thread replies, leave the account and announcement ones on.' },
      { author: 'sam', hoursAfter: 4, message: 'Found it. Six switches and I have flicked four. Perfect.' },
      { author: 'petra', hoursAfter: 20, message: 'I did the opposite last month — turned everything on and it is far too much. Somewhere in the middle is the answer and it took me a while to find it.' },
      { author: 'admin', hoursAfter: 30, message: 'The middle is going to be the default for new accounts from now on. Nobody\'s first week should be forty emails.' },
    ],
  },
  {
    forum: 'support',
    author: 'dev',
    title: 'Photos upload fine and then are not on the post',
    daysAgo: 6,
    prefix: 'solved',
    message: [
      'Progress bar goes all the way, post saves, and there is no photo on it. Happened with about sixty from Saturday.',
      '',
      'Started after the server move. Working on a laptop and on the phone, so it is not me.',
    ].join('\n'),
    replies: [
      {
        author: 'admin',
        hoursAfter: 2,
        message:
          'Photos are resized in the background rather than while you wait — that is why a hundred of them do not lock the page up. So this is almost always the background worker not running rather than the upload failing. Checking the tasks screen now.',
      },
      { author: 'admin', hoursAfter: 3, message: 'The worker is not in the new setup at all. It never got copied across in the move. That is entirely my fault and nothing is lost — everything queued is still queued.' },
      { author: 'dev', hoursAfter: 4, message: 'All sixty appeared within a minute of each other just now. That was alarming and then delightful.' },
      { author: 'admin', hoursAfter: 9, quotes: 2, message: 'That is the queue draining. The reminder emails and the membership expiries run on the same thing, which explains two other small mysteries this week.' },
      { author: 'noelle', hoursAfter: 20, message: 'It explains why three renewals did not expire on time. I had assumed I had done something wrong.' },
    ],
  },
  {
    forum: 'support',
    author: 'kev',
    title: 'Can somebody be stopped from opening six threads a day without banning them?',
    daysAgo: 2,
    message: [
      'One person, breaking no rule, being perfectly pleasant, and opening five or six threads a day in Buy, sell and swap where one would do.',
      '',
      'I would like them to be able to reply and not to open new ones, in that one forum. Is that a thing or am I inventing it?',
    ].join('\n'),
    replies: [
      {
        author: 'admin',
        hoursAfter: 2,
        message:
          'It is a thing. Permissions resolve per group per forum, so you make a group with "post threads" off and "post replies" on, put them in it, and apply it to that one forum. They will not notice anywhere else on the board.',
      },
      { author: 'kev', hoursAfter: 4, message: 'Did not know it went per forum. That is exactly the shape of the problem.' },
      { author: 'moderator', hoursAfter: 6, message: 'Talk to them first though. Nine times out of ten "you are posting a lot, could you do one thread" works and nobody has to be quietly restricted.' },
      { author: 'kev', hoursAfter: 20, message: 'Talked to them. They had no idea and were mortified. One thread now, updated as things sell. No permissions needed.' },
      { author: 'admin', hoursAfter: 26, quotes: 3, message: 'That is the right order to do it in and I should have said so first.' },
    ],
  },

  {
    forum: 'feedback',
    author: 'donal',
    title: 'The board on a phone at a pitch with one bar of signal',
    daysAgo: 60,
    message: [
      'Standing in a field in Ennis trying to check whether the second game was 12 or 12:30, on one bar, in the rain.',
      '',
      'It loaded. That is the whole feedback. I have used club websites that would not have loaded on the wifi at home and this one came up in a field.',
    ].join('\n'),
    replies: [
      { author: 'admin', hoursAfter: 4, message: 'That is the thing I care most about and almost nobody ever mentions, so thank you. Pages are plain HTML first and the clever bits come after — which is why it works on one bar.' },
      { author: 'mairead', hoursAfter: 9, message: 'Twelve. It was 12. And I know because I checked it in the same field.' },
      { author: 'zoe', hoursAfter: 26, message: 'The old site needed the app to do anything and the app needed a signal. Two seasons of standing on a wall holding a phone in the air.' },
    ],
  },
  {
    forum: 'feedback',
    author: 'pixel',
    title: 'Dark mode, and can we have the club colours in it',
    daysAgo: 33,
    message: [
      'Half the Tuesday crowd is on this at eleven at night and the board is very white.',
      '',
      'Also, and I say this with love: the default look is fine, but a club with green and white on the crest could have green and white on the site.',
    ].join('\n'),
    replies: [
      { author: 'admin', hoursAfter: 3, message: 'There is a picker at the bottom of every page and it takes a click, no account needed. Try the dark one now and tell me if the greens are wrong on your screen.' },
      { author: 'pixel', hoursAfter: 5, message: 'Found it. Four options. Two of them are genuinely lovely and one of them looks like a raid interface, which I did not expect from a club website.' },
      { author: 'wraith', hoursAfter: 9, message: 'The raid one is the only one I will use and I will hear nothing about it.' },
      { author: 'siobhan', hoursAfter: 20, message: 'And the club colours are in the crest at the top, which is the compromise I am happy with. The whole site in green and white was tried in 2011 and it was unreadable.' },
      { author: 'bram', hoursAfter: 30, message: 'The picker sticking without an account is the good bit. My mother reads the fixtures on here and will never make an account, and she has it on the big-text one.' },
    ],
  },
  {
    forum: 'feedback',
    author: 'mairead',
    title: 'A calendar view would be lovely',
    daysAgo: 25,
    message: [
      'Everything is in Events and it is all findable, but a parent with children in three teams is reading four threads to work out one Saturday.',
      '',
      'A month at a glance would save me the twelve messages I get every Friday.',
    ].join('\n'),
    replies: [
      { author: 'admin', hoursAfter: 5, message: 'Fair, and it is not there. What is there today: subscribe to a team\'s threads and the emails arrive as things change. That is not a calendar and I am not pretending it is.' },
      { author: 'bernie', hoursAfter: 9, message: 'Seconding hard. Three children, three teams, and I keep a paper calendar on the fridge because of this exact thing.' },
      { author: 'nova', hoursAfter: 14, message: 'Same on our side for a completely different reason — the ranked block and the raid night are fixed times and new people cannot see them at a glance anywhere.' },
      { author: 'admin', hoursAfter: 26, message: 'That is two very different groups asking for the same screen, which is usually the sign it is worth building. On the list, honestly rather than politely.' },
      { author: 'mairead', hoursAfter: 50, message: 'Honestly rather than politely is all I ask of any committee.' },
    ],
  },
  {
    forum: 'feedback',
    author: 'dara',
    title: 'A prefix for a called-off fixture',
    daysAgo: 19,
    message: [
      'We have Fixture, Sign-up and Result. When a game is off I edit the title to start with "OFF —" and it looks like shouting.',
      '',
      'A grey "Called off" prefix would do the job and would be visible from the forum list without opening anything.',
    ].join('\n'),
    replies: [
      { author: 'admin', hoursAfter: 4, message: 'Prefixes are a screen in the admin panel, so this is about a minute of work rather than a feature. Adding it tonight, scoped to Events so it does not clutter the rest of the board.' },
      { author: 'marty', hoursAfter: 8, message: 'Can it be a loud colour rather than grey? The whole point is that people see it at a glance from the phone in the car park.' },
      { author: 'dara', hoursAfter: 9, quotes: 2, message: 'Fine. Loud it is. I withdraw grey.' },
      { author: 'gerry', hoursAfter: 26, message: 'I will be the one using it most and I would like it in red, thank you.' },
    ],
  },
  {
    forum: 'feedback',
    author: 'nova',
    title: 'Sign-up threads should close themselves',
    daysAgo: 11,
    message: [
      'Every week somebody signs up for the Sunday block on the Sunday evening, after the teams are drawn, and then wonders why they are not on one.',
      '',
      'If a sign-up thread could lock itself at a time I set when I post it, that solves it without me having to remember to lock fourteen threads.',
    ].join('\n'),
    replies: [
      { author: 'tinker', hoursAfter: 3, message: 'Same for the raid roster. I lock it manually on Monday nights and I have forgotten twice.' },
      { author: 'olu', hoursAfter: 8, message: 'And the five-a-side. Three of us are describing one feature, which I think is the point of this forum.' },
      { author: 'admin', hoursAfter: 14, message: 'It does not exist. What does: locking a thread is one click for a moderator, and all three of you are moderators of your own corner already. Not a solution, an admission.' },
      { author: 'nova', hoursAfter: 20, message: 'An honest "no, and here is the workaround" is worth more than a maybe. Locking manually it is.' },
    ],
  },
  {
    forum: 'feedback',
    author: 'olu',
    title: 'Could Events be the first thing you see?',
    daysAgo: 7,
    message: [
      'Announcements is at the top because it is important, but it changes twice a month. Events changes every day and it is what almost everybody is actually here for.',
      '',
      'Not a complaint about the order. A question about what a first-time visitor sees.',
    ].join('\n'),
    replies: [
      { author: 'admin', hoursAfter: 3, message: 'The order is a number on each forum in the admin panel and I can change it in ten seconds. The question is whether Announcements stops getting read if it moves down.' },
      { author: 'siobhan', hoursAfter: 6, message: 'It will stop getting read. That is not a guess — it is what happened on the old site when the notices went below the fold.' },
      { author: 'kev', hoursAfter: 11, message: 'Compromise: leave the order alone and make the front page show the newest posts across everything. Then the busy forum is at the top by being busy.' },
      { author: 'admin', hoursAfter: 20, quotes: 3, message: 'That already exists, it is just not the landing page. Making it the landing page for logged-in members and leaving the forum list for everybody else. Trying it for a fortnight.' },
      { author: 'olu', hoursAfter: 30, message: 'Two days in and the Thursday sign-up has four more people than usual. Small thing, real difference.' },
    ],
  },

  {
    forum: 'moderation',
    author: 'siobhan',
    title: 'What the staff will and will not do',
    daysAgo: 300,
    sticky: true,
    message: [
      'Written down because "the moderators" being a vague and slightly frightening idea does nobody any good.',
      '',
      '**We will:** take down anything about a child that a parent is not happy with, immediately and without argument. Remove spam. Lock a thread that has stopped being a conversation. Have a private word before we do anything public.',
      '',
      '**We will not:** delete a post because it disagrees with the committee. Take sides in an argument about a referee. Remove a complaint about how the club is run — those stay up, including the ones that are unfair, because a board where the criticism disappears is worth nothing.',
      '',
      '**Who we are:** two administrators, two super moderators, and four moderators who each look after a corner of the board. Names are on the staff page and every one of us is a volunteer with a day job.',
      '',
      'If you think we got something wrong, say so. There is a report button on every post and it comes to all of us, not just the person you are annoyed with.',
    ].join('\n'),
    replies: [
      { author: 'frank', hoursAfter: 9, message: 'The bit about complaints staying up is the one that matters and it is the one most clubs would quietly leave out.' },
      { author: 'rosa', hoursAfter: 20, message: 'It has been tested twice since this was posted and held both times, which is the only reason anybody believes it.' },
      { author: 'moderator', hoursAfter: 44, message: 'Worth adding: a report is not an accusation. Half of what I get is "this is probably fine but you should see it", and that is exactly the right use of it.' },
    ],
  },
  {
    forum: 'moderation',
    author: 'mairead',
    title: 'Photos of children: the rule, and why it is not up for discussion',
    daysAgo: 200,
    sticky: true,
    locked: true,
    message: [
      'One rule, in three parts.',
      '',
      '1. **No photograph of a child goes on this board unless their parent has ticked the box on the membership form.** Not "unless they objected". Ticked.',
      '2. **Any parent can ask for any photo to come down, at any time, without giving a reason**, and it will be gone inside an hour.',
      '3. **No full names of under-18s** beside a photograph. First name only, and only if the parent is happy with that too.',
      '',
      'This is not the committee being nervous. It is the safeguarding policy we are required to have and it is also, separately, just the right way to behave.',
      '',
      'Locked because it is a policy rather than a discussion. Questions to me or to the welfare officer, any time.',
    ].join('\n'),
  },
  {
    forum: 'moderation',
    author: 'dara',
    title: 'Why every new account\'s first post is held',
    daysAgo: 92,
    message: [
      'A new member posted on Saturday, saw "waiting for approval", and messaged me thinking they had done something wrong.',
      '',
      'They had not. Every brand new account has its first post held until somebody looks at it, and it is almost always approved within the hour.',
      '',
      'It exists because it is the single most effective thing we do against spam. The bots that get through registration still cannot get a link onto the board, because a person reads the first thing they write.',
    ].join('\n'),
    replies: [
      { author: 'moderator', hoursAfter: 3, message: 'And the wording on the screen is now much friendlier than it was, because that member was the third person to think they were in trouble.' },
      { author: 'admin', hoursAfter: 26, message: 'It costs the staff about four clicks a week. It has stopped, at a rough count, three hundred spam posts.' },
      { author: 'kev', hoursAfter: 50, message: 'The queue is the least glamorous screen on the board and it is the one that keeps this place readable.' },
      { author: 'rook', hoursAfter: 800, message: 'Mine was held and approved in about twenty minutes, and the message explained why. No complaints at all.' },
    ],
  },
  {
    forum: 'moderation',
    author: 'admin',
    title: 'The spam wave last month, and what actually stopped it',
    daysAgo: 57,
    message: [
      'About nine hundred registration attempts over four days. Roughly thirty got as far as writing a post. Writing it down because two other clubs locally got the same wave the same week.',
      '',
      '**Did not work:** the hidden field that bots are supposed to fill in. Whatever was driving this filled the form like a browser, because it was one.',
      '',
      '**Worked:** the registration question. One line, specific to the club, that you cannot answer by reading the page — ours asks what colour the away jerseys were before the change. Attempts went from about two hundred a day to under five.',
      '',
      '**Worked quietly:** holding first posts. The thirty that got through never became visible, so the board never looked spammed, which matters more than the raw number.',
      '',
      'Cost to real people: two members emailed to say the question was confusing. Both got in the same evening.',
    ].join('\n'),
    replies: [
      { author: 'siobhan', hoursAfter: 4, message: 'The "never looked spammed" part is underrated. A board that looks unmoderated attracts more of it and puts off the members you want.' },
      { author: 'rosa', hoursAfter: 9, message: 'The community centre board got the same wave. Question worked for us too — ours asks what is across the road from the hall.' },
      { author: 'vex', hoursAfter: 15, message: 'Do not make the question too clever. Ours was too clever for a fortnight and three real people failed it.' },
      { author: 'kev', hoursAfter: 20, message: 'What do we do about the one that got through last week into Buy, sell and swap? It is reported and still sitting there.' },
      { author: 'moderator', hoursAfter: 26, quotes: 4, message: 'It is in the queue and I have deliberately left it for whoever is on next, so they can see what one looks like before it disappears.' },
    ],
  },
  {
    forum: 'moderation',
    author: 'moderator',
    title: 'Match threads get heated. Where is the line?',
    daysAgo: 46,
    message: [
      'Saturday\'s thread had four posts about the referee that I would not want the referee to read, and one about an opposition player by name that I took down.',
      '',
      'I am fairly sure I got the second one right and much less sure about the first four. Nobody swore. Nobody was personal about anybody in this club.',
      '',
      'Where do people think the line is, before I have to decide it on my own at eleven at night?',
    ].join('\n'),
    replies: [
      { author: 'siobhan', hoursAfter: 2, message: 'Named opposition player, especially an under-18, is over it every single time. You were right.' },
      { author: 'marty', hoursAfter: 5, message: 'On referees: they are volunteers who get abused for a living and half of them are members of clubs like ours. "The referee had a shocker" is fine. Anything about the person is not.' },
      { author: 'paudie', hoursAfter: 9, message: 'I wrote one of the four. Reading it back I would not have said it to his face, which is probably the whole test.' },
      { author: 'deco', hoursAfter: 14, quotes: 3, message: 'That is the best rule anybody has put in this thread. Would you say it to their face at the club bar afterwards.' },
      { author: 'moderator', hoursAfter: 20, message: 'Taking that as the line and putting it in the pinned post. It is one sentence and everyone will remember it.' },
      { author: 'dara', hoursAfter: 44, message: 'And I will keep writing the match reports so there is somewhere sensible for the frustration to go. Half of it is people with nowhere to put a bad Saturday.' },
    ],
  },
  {
    forum: 'moderation',
    author: 'moderator',
    title: 'How do you handle a member who is technically fine and exhausting?',
    daysAgo: 29,
    message: [
      'Not a rule-breaker. Never rude. Replies to every thread within a minute, at length, usually restating what the post above said.',
      '',
      'Three people have quietly told me they have stopped posting because of it. I have no rule that covers this and I am not sure I want one.',
    ].join('\n'),
    replies: [
      {
        author: 'siobhan',
        hoursAfter: 2,
        message:
          'Talk to them. A private message that says "you are one of the most active people here and I need to ask you to leave some room" works more often than the internet expects. I have done it four times and it worked three.',
      },
      {
        author: 'vex',
        hoursAfter: 6,
        quotes: 1,
        message: 'And the fourth?\n\nAsking seriously — the failure case is the one nobody writes down, and it is the one I would want to know about before trying it.',
      },
      { author: 'siobhan', hoursAfter: 8, message: 'The fourth left in a temper and said a few things about me in the shop. The board was better for it and I would still do it again. It is not free.' },
      { author: 'moderator', hoursAfter: 26, message: 'Sent one this morning. Will report back.' },
      { author: 'moderator', hoursAfter: 74, message: 'Reporting back: went well. They were mortified, which I felt bad about, and have visibly pulled back without going quiet. Recommended, with the warning attached.' },
      { author: 'kev', hoursAfter: 90, message: 'The same conversation works for the six-threads-a-day thing. It is remarkable how often the answer is "nobody has ever told them".' },
    ],
  },
]
