CREATE TABLE "ban_filters" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ban_filters_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"type" text NOT NULL,
	"pattern" text NOT NULL,
	"note" text,
	"created_by_user_id" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "bans" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "bans_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"banned_by_user_id" integer,
	"reason" text,
	"public_reason" text,
	"previous_primary_group_id" integer,
	"expires_at" timestamp with time zone,
	"lifted_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "credential_tokens" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "credential_tokens_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"token_hash" text NOT NULL,
	"user_id" integer NOT NULL,
	"purpose" text NOT NULL,
	"payload" text,
	"consumed_at" timestamp with time zone,
	"expires_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "login_attempts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "login_attempts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"bucket" text NOT NULL,
	"succeeded" boolean NOT NULL,
	"occurred_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "remember_tokens" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "remember_tokens_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"token_hash" text NOT NULL,
	"family_id" text NOT NULL,
	"user_id" integer NOT NULL,
	"used_at" timestamp with time zone,
	"revoked_at" timestamp with time zone,
	"revoked_reason" text,
	"expires_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "sessions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sessions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"token_hash" text NOT NULL,
	"user_id" integer,
	"location_path" text,
	"location_forum_id" integer,
	"location_thread_id" integer,
	"ip_prefix" text,
	"user_agent" text,
	"superseded_by_session_id" integer,
	"last_seen_at" timestamp with time zone DEFAULT now() NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"revoked_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "user_group_memberships" (
	"user_id" integer NOT NULL,
	"group_id" integer NOT NULL,
	"is_display_group" boolean DEFAULT false NOT NULL,
	"granted_by_user_id" integer,
	"granted_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "usergroups" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "usergroups_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"key" text NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"badge_token" text,
	"display_order" integer DEFAULT 0 NOT NULL,
	"is_system" boolean DEFAULT false NOT NULL,
	"is_staff_group" boolean DEFAULT false NOT NULL,
	"can_view" boolean DEFAULT false NOT NULL,
	"can_view_threads" boolean DEFAULT false NOT NULL,
	"can_view_others_threads" boolean DEFAULT false NOT NULL,
	"can_search" boolean DEFAULT false NOT NULL,
	"can_post_threads" boolean DEFAULT false NOT NULL,
	"can_post_replies" boolean DEFAULT false NOT NULL,
	"can_post_polls" boolean DEFAULT false NOT NULL,
	"can_vote_polls" boolean DEFAULT false NOT NULL,
	"can_rate_threads" boolean DEFAULT false NOT NULL,
	"can_edit_own_posts" boolean DEFAULT false NOT NULL,
	"can_delete_own_posts" boolean DEFAULT false NOT NULL,
	"can_delete_own_threads" boolean DEFAULT false NOT NULL,
	"can_edit_others_posts" boolean DEFAULT false NOT NULL,
	"can_delete_others_posts" boolean DEFAULT false NOT NULL,
	"can_soft_delete_posts" boolean DEFAULT false NOT NULL,
	"can_view_unapproved" boolean DEFAULT false NOT NULL,
	"can_view_deleted" boolean DEFAULT false NOT NULL,
	"can_approve_content" boolean DEFAULT false NOT NULL,
	"can_upload_attachments" boolean DEFAULT false NOT NULL,
	"can_download_attachments" boolean DEFAULT false NOT NULL,
	"can_subscribe" boolean DEFAULT false NOT NULL,
	"can_view_profiles" boolean DEFAULT false NOT NULL,
	"can_view_member_list" boolean DEFAULT false NOT NULL,
	"can_use_private_messages" boolean DEFAULT false NOT NULL,
	"can_use_signature" boolean DEFAULT false NOT NULL,
	"can_upload_avatar" boolean DEFAULT false NOT NULL,
	"can_report_content" boolean DEFAULT false NOT NULL,
	"can_view_board_offline" boolean DEFAULT false NOT NULL,
	"can_bypass_flood_check" boolean DEFAULT false NOT NULL,
	"can_access_mod_cp" boolean DEFAULT false NOT NULL,
	"is_super_moderator" boolean DEFAULT false NOT NULL,
	"is_administrator" boolean DEFAULT false NOT NULL,
	"can_access_admin_cp" boolean DEFAULT false NOT NULL,
	"max_posts_per_day" integer DEFAULT 0 NOT NULL,
	"edit_time_limit_minutes" integer DEFAULT 0 NOT NULL,
	"max_attachments_per_post" integer DEFAULT 0 NOT NULL,
	"max_attachment_size_kb" integer DEFAULT 0 NOT NULL,
	"max_private_messages_per_day" integer DEFAULT 0 NOT NULL,
	"max_signature_length" integer DEFAULT 0 NOT NULL,
	"requires_thread_approval" boolean DEFAULT true NOT NULL,
	"requires_post_approval" boolean DEFAULT true NOT NULL,
	"requires_approval_on_edit" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"username" text NOT NULL,
	"username_lower" text NOT NULL,
	"email" text NOT NULL,
	"email_lower" text NOT NULL,
	"password_hash" text,
	"password_algo" text,
	"password_changed_at" timestamp with time zone,
	"primary_group_id" integer NOT NULL,
	"display_group_id" integer,
	"state" text DEFAULT 'active' NOT NULL,
	"post_count" integer DEFAULT 0 NOT NULL,
	"thread_count" integer DEFAULT 0 NOT NULL,
	"reputation" integer DEFAULT 0 NOT NULL,
	"warning_points" smallint DEFAULT 0 NOT NULL,
	"registration_ip_prefix" text,
	"last_ip_prefix" text,
	"last_active_at" timestamp with time zone,
	"email_verified_at" timestamp with time zone,
	"deleted_at" timestamp with time zone,
	"legacy_mybb_uid" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "forum_moderators" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "forum_moderators_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"forum_id" integer NOT NULL,
	"user_id" integer,
	"group_id" integer,
	"cascade_to_subforums" boolean DEFAULT false NOT NULL,
	"can_edit_posts" boolean DEFAULT false NOT NULL,
	"can_soft_delete_posts" boolean DEFAULT false NOT NULL,
	"can_restore_posts" boolean DEFAULT false NOT NULL,
	"can_hard_delete_posts" boolean DEFAULT false NOT NULL,
	"can_approve_content" boolean DEFAULT false NOT NULL,
	"can_open_close_threads" boolean DEFAULT false NOT NULL,
	"can_stick_threads" boolean DEFAULT false NOT NULL,
	"can_move_threads" boolean DEFAULT false NOT NULL,
	"can_merge_threads" boolean DEFAULT false NOT NULL,
	"can_split_threads" boolean DEFAULT false NOT NULL,
	"can_manage_polls" boolean DEFAULT false NOT NULL,
	"can_view_ips" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "forum_password_grants" (
	"session_id" integer NOT NULL,
	"forum_id" integer NOT NULL,
	"granted_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "forum_permissions" (
	"forum_id" integer NOT NULL,
	"group_id" integer NOT NULL,
	"can_view" boolean,
	"can_view_threads" boolean,
	"can_view_others_threads" boolean,
	"can_search" boolean,
	"can_post_threads" boolean,
	"can_post_replies" boolean,
	"can_post_polls" boolean,
	"can_vote_polls" boolean,
	"can_rate_threads" boolean,
	"can_edit_own_posts" boolean,
	"can_delete_own_posts" boolean,
	"can_delete_own_threads" boolean,
	"can_edit_others_posts" boolean,
	"can_delete_others_posts" boolean,
	"can_soft_delete_posts" boolean,
	"can_view_unapproved" boolean,
	"can_view_deleted" boolean,
	"can_approve_content" boolean,
	"can_upload_attachments" boolean,
	"can_download_attachments" boolean,
	"can_subscribe" boolean,
	"edit_time_limit_minutes" integer,
	"max_attachments_per_post" integer,
	"max_attachment_size_kb" integer,
	"requires_thread_approval" boolean,
	"requires_post_approval" boolean,
	"requires_approval_on_edit" boolean,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "forum_subscriptions" (
	"user_id" integer NOT NULL,
	"forum_id" integer NOT NULL,
	"notify_via" text DEFAULT 'notification' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "forums" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "forums_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"type" text DEFAULT 'forum' NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"slug" text NOT NULL,
	"parent_id" integer,
	"path" text NOT NULL,
	"depth" integer DEFAULT 0 NOT NULL,
	"display_order" integer DEFAULT 0 NOT NULL,
	"link_url" text,
	"link_hits" integer DEFAULT 0 NOT NULL,
	"is_open" boolean DEFAULT true NOT NULL,
	"allow_threads" boolean DEFAULT true NOT NULL,
	"allow_replies" boolean DEFAULT true NOT NULL,
	"allow_polls" boolean DEFAULT true NOT NULL,
	"allow_attachments" boolean DEFAULT true NOT NULL,
	"requires_prefix" boolean DEFAULT false NOT NULL,
	"moderate_new_threads" boolean DEFAULT false NOT NULL,
	"moderate_new_posts" boolean DEFAULT false NOT NULL,
	"password_hash" text,
	"thread_count" integer DEFAULT 0 NOT NULL,
	"post_count" integer DEFAULT 0 NOT NULL,
	"last_post_id" integer,
	"last_post_thread_id" integer,
	"last_post_thread_title" text,
	"last_post_user_id" integer,
	"last_post_username" text,
	"last_post_at" timestamp with time zone,
	"legacy_mybb_fid" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "forums_read" (
	"user_id" integer NOT NULL,
	"forum_id" integer NOT NULL,
	"read_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "post_revisions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "post_revisions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"post_id" integer NOT NULL,
	"revision" smallint NOT NULL,
	"message" text NOT NULL,
	"subject" text,
	"edited_by_user_id" integer,
	"edit_reason" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "posts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "posts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"thread_id" integer NOT NULL,
	"forum_id" integer NOT NULL,
	"author_user_id" integer,
	"author_username" text NOT NULL,
	"subject" text,
	"message" text NOT NULL,
	"visibility" text DEFAULT 'visible' NOT NULL,
	"is_first_post" boolean DEFAULT false NOT NULL,
	"ip_prefix" text,
	"edited_at" timestamp with time zone,
	"edited_by_user_id" integer,
	"edit_reason" text,
	"revision_count" smallint DEFAULT 0 NOT NULL,
	"search_vector" "tsvector",
	"legacy_mybb_pid" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "thread_prefixes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "thread_prefixes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"label" text NOT NULL,
	"token" text,
	"display_order" integer DEFAULT 0 NOT NULL,
	"forum_path_prefix" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "thread_subscriptions" (
	"user_id" integer NOT NULL,
	"thread_id" integer NOT NULL,
	"notify_via" text DEFAULT 'notification' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "threads" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "threads_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"forum_id" integer NOT NULL,
	"title" text NOT NULL,
	"slug" text NOT NULL,
	"prefix_id" integer,
	"author_user_id" integer,
	"author_username" text NOT NULL,
	"visibility" text DEFAULT 'visible' NOT NULL,
	"is_sticky" boolean DEFAULT false NOT NULL,
	"is_locked" boolean DEFAULT false NOT NULL,
	"first_post_id" integer,
	"reply_count" integer DEFAULT 0 NOT NULL,
	"view_count" integer DEFAULT 0 NOT NULL,
	"last_post_id" integer,
	"last_post_user_id" integer,
	"last_post_username" text,
	"last_post_at" timestamp with time zone DEFAULT now() NOT NULL,
	"moved_to_thread_id" integer,
	"legacy_mybb_tid" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "threads_read" (
	"user_id" integer NOT NULL,
	"thread_id" integer NOT NULL,
	"last_read_post_id" integer,
	"read_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "admin_log" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "admin_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer,
	"action" text NOT NULL,
	"detail" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"ip_prefix" text,
	"correlation_id" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cache_versions" (
	"key" text PRIMARY KEY NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"bumped_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "jobs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "jobs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"kind" text NOT NULL,
	"payload" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"idempotency_key" text,
	"run_at" timestamp with time zone DEFAULT now() NOT NULL,
	"attempts" smallint DEFAULT 0 NOT NULL,
	"max_attempts" smallint DEFAULT 5 NOT NULL,
	"locked_until" timestamp with time zone,
	"locked_by" text,
	"last_error" text,
	"correlation_id" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"completed_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "outbox" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "outbox_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"topic" text NOT NULL,
	"payload" jsonb NOT NULL,
	"correlation_id" text,
	"dispatched_at" timestamp with time zone,
	"attempts" smallint DEFAULT 0 NOT NULL,
	"last_error" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "setting_groups" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "setting_groups_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"key" text NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"display_order" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "settings" (
	"key" text PRIMARY KEY NOT NULL,
	"value" text NOT NULL,
	"group_key" text,
	"updated_by_user_id" integer,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "task_log" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "task_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"task_key" text NOT NULL,
	"succeeded" boolean NOT NULL,
	"duration_ms" integer,
	"detail" text,
	"error" text,
	"ran_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "tasks" (
	"key" text PRIMARY KEY NOT NULL,
	"interval_seconds" integer NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"last_run_at" timestamp with time zone,
	"next_run_at" timestamp with time zone DEFAULT now() NOT NULL,
	"locked_until" timestamp with time zone,
	"consecutive_failures" smallint DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "themes" (
	"key" text PRIMARY KEY NOT NULL,
	"title" text NOT NULL,
	"token_overrides" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"branding" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"layout_options" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"custom_css" text,
	"is_default" boolean DEFAULT false NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "ban_filters" ADD CONSTRAINT "ban_filters_created_by_user_id_users_id_fk" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bans" ADD CONSTRAINT "bans_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bans" ADD CONSTRAINT "bans_banned_by_user_id_users_id_fk" FOREIGN KEY ("banned_by_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bans" ADD CONSTRAINT "bans_previous_primary_group_id_usergroups_id_fk" FOREIGN KEY ("previous_primary_group_id") REFERENCES "public"."usergroups"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "credential_tokens" ADD CONSTRAINT "credential_tokens_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "remember_tokens" ADD CONSTRAINT "remember_tokens_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_group_memberships" ADD CONSTRAINT "user_group_memberships_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_group_memberships" ADD CONSTRAINT "user_group_memberships_group_id_usergroups_id_fk" FOREIGN KEY ("group_id") REFERENCES "public"."usergroups"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_group_memberships" ADD CONSTRAINT "user_group_memberships_granted_by_user_id_users_id_fk" FOREIGN KEY ("granted_by_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_primary_group_id_usergroups_id_fk" FOREIGN KEY ("primary_group_id") REFERENCES "public"."usergroups"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_display_group_id_usergroups_id_fk" FOREIGN KEY ("display_group_id") REFERENCES "public"."usergroups"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "forum_moderators" ADD CONSTRAINT "forum_moderators_forum_id_forums_id_fk" FOREIGN KEY ("forum_id") REFERENCES "public"."forums"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "forum_moderators" ADD CONSTRAINT "forum_moderators_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "forum_moderators" ADD CONSTRAINT "forum_moderators_group_id_usergroups_id_fk" FOREIGN KEY ("group_id") REFERENCES "public"."usergroups"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "forum_password_grants" ADD CONSTRAINT "forum_password_grants_forum_id_forums_id_fk" FOREIGN KEY ("forum_id") REFERENCES "public"."forums"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "forum_permissions" ADD CONSTRAINT "forum_permissions_forum_id_forums_id_fk" FOREIGN KEY ("forum_id") REFERENCES "public"."forums"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "forum_permissions" ADD CONSTRAINT "forum_permissions_group_id_usergroups_id_fk" FOREIGN KEY ("group_id") REFERENCES "public"."usergroups"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "forum_subscriptions" ADD CONSTRAINT "forum_subscriptions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "forum_subscriptions" ADD CONSTRAINT "forum_subscriptions_forum_id_forums_id_fk" FOREIGN KEY ("forum_id") REFERENCES "public"."forums"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "forums_read" ADD CONSTRAINT "forums_read_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "forums_read" ADD CONSTRAINT "forums_read_forum_id_forums_id_fk" FOREIGN KEY ("forum_id") REFERENCES "public"."forums"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "post_revisions" ADD CONSTRAINT "post_revisions_post_id_posts_id_fk" FOREIGN KEY ("post_id") REFERENCES "public"."posts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "post_revisions" ADD CONSTRAINT "post_revisions_edited_by_user_id_users_id_fk" FOREIGN KEY ("edited_by_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "posts" ADD CONSTRAINT "posts_thread_id_threads_id_fk" FOREIGN KEY ("thread_id") REFERENCES "public"."threads"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "posts" ADD CONSTRAINT "posts_forum_id_forums_id_fk" FOREIGN KEY ("forum_id") REFERENCES "public"."forums"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "posts" ADD CONSTRAINT "posts_author_user_id_users_id_fk" FOREIGN KEY ("author_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "posts" ADD CONSTRAINT "posts_edited_by_user_id_users_id_fk" FOREIGN KEY ("edited_by_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "thread_subscriptions" ADD CONSTRAINT "thread_subscriptions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "thread_subscriptions" ADD CONSTRAINT "thread_subscriptions_thread_id_threads_id_fk" FOREIGN KEY ("thread_id") REFERENCES "public"."threads"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "threads" ADD CONSTRAINT "threads_forum_id_forums_id_fk" FOREIGN KEY ("forum_id") REFERENCES "public"."forums"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "threads" ADD CONSTRAINT "threads_prefix_id_thread_prefixes_id_fk" FOREIGN KEY ("prefix_id") REFERENCES "public"."thread_prefixes"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "threads" ADD CONSTRAINT "threads_author_user_id_users_id_fk" FOREIGN KEY ("author_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "threads_read" ADD CONSTRAINT "threads_read_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "threads_read" ADD CONSTRAINT "threads_read_thread_id_threads_id_fk" FOREIGN KEY ("thread_id") REFERENCES "public"."threads"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "admin_log" ADD CONSTRAINT "admin_log_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "settings" ADD CONSTRAINT "settings_updated_by_user_id_users_id_fk" FOREIGN KEY ("updated_by_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "ban_filters_type_idx" ON "ban_filters" USING btree ("type");--> statement-breakpoint
CREATE UNIQUE INDEX "ban_filters_type_pattern_key" ON "ban_filters" USING btree ("type","pattern");--> statement-breakpoint
CREATE UNIQUE INDEX "bans_active_user_key" ON "bans" USING btree ("user_id") WHERE "bans"."lifted_at" is null;--> statement-breakpoint
CREATE INDEX "bans_expires_idx" ON "bans" USING btree ("expires_at") WHERE "bans"."lifted_at" is null;--> statement-breakpoint
CREATE UNIQUE INDEX "credential_tokens_hash_key" ON "credential_tokens" USING btree ("token_hash");--> statement-breakpoint
CREATE INDEX "credential_tokens_user_purpose_idx" ON "credential_tokens" USING btree ("user_id","purpose");--> statement-breakpoint
CREATE INDEX "credential_tokens_expires_idx" ON "credential_tokens" USING btree ("expires_at");--> statement-breakpoint
CREATE INDEX "login_attempts_bucket_idx" ON "login_attempts" USING btree ("bucket","occurred_at");--> statement-breakpoint
CREATE UNIQUE INDEX "remember_tokens_hash_key" ON "remember_tokens" USING btree ("token_hash");--> statement-breakpoint
CREATE INDEX "remember_tokens_family_idx" ON "remember_tokens" USING btree ("family_id");--> statement-breakpoint
CREATE INDEX "remember_tokens_user_idx" ON "remember_tokens" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "remember_tokens_expires_idx" ON "remember_tokens" USING btree ("expires_at");--> statement-breakpoint
CREATE UNIQUE INDEX "sessions_token_hash_key" ON "sessions" USING btree ("token_hash");--> statement-breakpoint
CREATE INDEX "sessions_last_seen_idx" ON "sessions" USING btree ("last_seen_at");--> statement-breakpoint
CREATE INDEX "sessions_user_idx" ON "sessions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "sessions_expires_idx" ON "sessions" USING btree ("expires_at");--> statement-breakpoint
CREATE UNIQUE INDEX "user_group_memberships_pkey" ON "user_group_memberships" USING btree ("user_id","group_id");--> statement-breakpoint
CREATE INDEX "user_group_memberships_user_idx" ON "user_group_memberships" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "user_group_memberships_group_idx" ON "user_group_memberships" USING btree ("group_id");--> statement-breakpoint
CREATE UNIQUE INDEX "usergroups_key_key" ON "usergroups" USING btree ("key");--> statement-breakpoint
CREATE INDEX "usergroups_display_order_idx" ON "usergroups" USING btree ("display_order");--> statement-breakpoint
CREATE UNIQUE INDEX "users_username_lower_key" ON "users" USING btree ("username_lower");--> statement-breakpoint
CREATE UNIQUE INDEX "users_email_lower_key" ON "users" USING btree ("email_lower");--> statement-breakpoint
CREATE UNIQUE INDEX "users_legacy_mybb_uid_key" ON "users" USING btree ("legacy_mybb_uid") WHERE "users"."legacy_mybb_uid" is not null;--> statement-breakpoint
CREATE INDEX "users_primary_group_idx" ON "users" USING btree ("primary_group_id");--> statement-breakpoint
CREATE INDEX "users_active_created_idx" ON "users" USING btree ("created_at") WHERE "users"."state" = 'active';--> statement-breakpoint
CREATE INDEX "users_last_active_idx" ON "users" USING btree ("last_active_at");--> statement-breakpoint
CREATE UNIQUE INDEX "forum_moderators_user_key" ON "forum_moderators" USING btree ("forum_id","user_id") WHERE "forum_moderators"."user_id" is not null;--> statement-breakpoint
CREATE UNIQUE INDEX "forum_moderators_group_key" ON "forum_moderators" USING btree ("forum_id","group_id") WHERE "forum_moderators"."group_id" is not null;--> statement-breakpoint
CREATE INDEX "forum_moderators_user_idx" ON "forum_moderators" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "forum_moderators_group_idx" ON "forum_moderators" USING btree ("group_id");--> statement-breakpoint
CREATE UNIQUE INDEX "forum_password_grants_pkey" ON "forum_password_grants" USING btree ("session_id","forum_id");--> statement-breakpoint
CREATE UNIQUE INDEX "forum_permissions_pkey" ON "forum_permissions" USING btree ("forum_id","group_id");--> statement-breakpoint
CREATE INDEX "forum_permissions_group_idx" ON "forum_permissions" USING btree ("group_id");--> statement-breakpoint
CREATE UNIQUE INDEX "forum_subscriptions_pkey" ON "forum_subscriptions" USING btree ("user_id","forum_id");--> statement-breakpoint
CREATE INDEX "forum_subscriptions_forum_idx" ON "forum_subscriptions" USING btree ("forum_id");--> statement-breakpoint
CREATE UNIQUE INDEX "forums_parent_slug_key" ON "forums" USING btree ("parent_id","slug") WHERE "forums"."parent_id" is not null;--> statement-breakpoint
CREATE UNIQUE INDEX "forums_root_slug_key" ON "forums" USING btree ("slug") WHERE "forums"."parent_id" is null;--> statement-breakpoint
CREATE INDEX "forums_parent_order_idx" ON "forums" USING btree ("parent_id","display_order");--> statement-breakpoint
CREATE INDEX "forums_path_idx" ON "forums" USING btree ("path");--> statement-breakpoint
CREATE UNIQUE INDEX "forums_legacy_mybb_fid_key" ON "forums" USING btree ("legacy_mybb_fid") WHERE "forums"."legacy_mybb_fid" is not null;--> statement-breakpoint
CREATE UNIQUE INDEX "forums_read_pkey" ON "forums_read" USING btree ("user_id","forum_id");--> statement-breakpoint
CREATE UNIQUE INDEX "post_revisions_post_revision_key" ON "post_revisions" USING btree ("post_id","revision");--> statement-breakpoint
CREATE INDEX "posts_thread_visible_idx" ON "posts" USING btree ("thread_id","id") WHERE "posts"."visibility" = 'visible';--> statement-breakpoint
CREATE INDEX "posts_thread_all_idx" ON "posts" USING btree ("thread_id","id");--> statement-breakpoint
CREATE INDEX "posts_author_idx" ON "posts" USING btree ("author_user_id","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "posts_forum_visibility_idx" ON "posts" USING btree ("forum_id","created_at" DESC NULLS LAST) WHERE "posts"."visibility" <> 'visible';--> statement-breakpoint
CREATE UNIQUE INDEX "posts_legacy_mybb_pid_key" ON "posts" USING btree ("legacy_mybb_pid") WHERE "posts"."legacy_mybb_pid" is not null;--> statement-breakpoint
CREATE INDEX "posts_search_vector_idx" ON "posts" USING gin ("search_vector");--> statement-breakpoint
CREATE INDEX "thread_prefixes_order_idx" ON "thread_prefixes" USING btree ("display_order");--> statement-breakpoint
CREATE UNIQUE INDEX "thread_subscriptions_pkey" ON "thread_subscriptions" USING btree ("user_id","thread_id");--> statement-breakpoint
CREATE INDEX "thread_subscriptions_thread_idx" ON "thread_subscriptions" USING btree ("thread_id");--> statement-breakpoint
CREATE INDEX "threads_forum_listing_idx" ON "threads" USING btree ("forum_id","is_sticky" DESC NULLS LAST,"last_post_at" DESC NULLS LAST) WHERE "threads"."visibility" = 'visible';--> statement-breakpoint
CREATE INDEX "threads_forum_listing_all_idx" ON "threads" USING btree ("forum_id","is_sticky" DESC NULLS LAST,"last_post_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "threads_author_idx" ON "threads" USING btree ("author_user_id","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE UNIQUE INDEX "threads_legacy_mybb_tid_key" ON "threads" USING btree ("legacy_mybb_tid") WHERE "threads"."legacy_mybb_tid" is not null;--> statement-breakpoint
CREATE UNIQUE INDEX "threads_read_pkey" ON "threads_read" USING btree ("user_id","thread_id");--> statement-breakpoint
CREATE INDEX "threads_read_read_at_idx" ON "threads_read" USING btree ("read_at");--> statement-breakpoint
CREATE INDEX "admin_log_user_idx" ON "admin_log" USING btree ("user_id","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "admin_log_action_idx" ON "admin_log" USING btree ("action","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "jobs_pending_idx" ON "jobs" USING btree ("status","run_at") WHERE "jobs"."status" = 'pending';--> statement-breakpoint
CREATE UNIQUE INDEX "jobs_idempotency_key" ON "jobs" USING btree ("idempotency_key") WHERE "jobs"."idempotency_key" is not null and "jobs"."status" = 'pending';--> statement-breakpoint
CREATE INDEX "jobs_status_idx" ON "jobs" USING btree ("status");--> statement-breakpoint
CREATE INDEX "outbox_pending_idx" ON "outbox" USING btree ("id") WHERE "outbox"."dispatched_at" is null;--> statement-breakpoint
CREATE UNIQUE INDEX "setting_groups_key_key" ON "setting_groups" USING btree ("key");--> statement-breakpoint
CREATE INDEX "settings_group_idx" ON "settings" USING btree ("group_key");--> statement-breakpoint
CREATE INDEX "task_log_key_ran_idx" ON "task_log" USING btree ("task_key","ran_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "tasks_due_idx" ON "tasks" USING btree ("next_run_at") WHERE "tasks"."enabled";--> statement-breakpoint
CREATE UNIQUE INDEX "themes_single_default_key" ON "themes" USING btree ("is_default") WHERE "themes"."is_default";
