-- F24 — automatic group promotions.
--
-- R3.1 lists `group_promotions`; the initial schema never created it. Added
-- here rather than by editing 0000, because migrations are forward-only (D28)
-- and an applied migration is history.
--
-- Criteria columns are all NULLABLE and mean "no constraint" when null, which
-- is what lets a rule express "everyone in Awaiting Activation becomes
-- Registered" without inventing sentinel thresholds like 0 or -1 that then have
-- to be special-cased at every read.

CREATE TABLE "group_promotions" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  "title" text NOT NULL,
  "enabled" boolean NOT NULL DEFAULT true,
  -- Evaluation order. The first matching rule wins, so this is meaningful
  -- policy rather than presentation.
  "display_order" integer NOT NULL DEFAULT 0,

  "min_post_count" integer,
  "min_reputation" integer,
  "min_days_registered" integer,

  -- NULL = any group. Powerful, which is why the domain layer refuses to demote
  -- or to touch a banned user regardless of what a rule says.
  "from_primary_group_id" integer REFERENCES "usergroups"("id") ON DELETE cascade,
  "to_primary_group_id" integer NOT NULL REFERENCES "usergroups"("id") ON DELETE cascade,

  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp with time zone NOT NULL DEFAULT now()
);
--> statement-breakpoint

CREATE INDEX "group_promotions_order_idx" ON "group_promotions" ("display_order", "id");
--> statement-breakpoint

-- The candidate scan pages by user id and filters on the columns a rule tests.
-- Without this, every promotion run is a full table scan of `users`.
CREATE INDEX IF NOT EXISTS "users_promotion_scan_idx"
  ON "users" ("id")
  INCLUDE ("primary_group_id", "post_count", "reputation", "created_at");
