CREATE TABLE "group_promotions" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  "title" text NOT NULL,
  "enabled" boolean NOT NULL DEFAULT true,
  "display_order" integer NOT NULL DEFAULT 0,

  "min_post_count" integer,
  "min_reputation" integer,
  "min_days_registered" integer,

  "from_primary_group_id" integer REFERENCES "usergroups"("id") ON DELETE cascade,
  "to_primary_group_id" integer NOT NULL REFERENCES "usergroups"("id") ON DELETE cascade,

  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp with time zone NOT NULL DEFAULT now()
);
--> statement-breakpoint

CREATE INDEX "group_promotions_order_idx" ON "group_promotions" ("display_order", "id");
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "users_promotion_scan_idx"
  ON "users" ("id")
  INCLUDE ("primary_group_id", "post_count", "reputation", "created_at");
