-- F49 — reports.
--
-- A report is a member saying "a moderator should look at this". Two tables,
-- because a report has a *current state* and a *history*, and collapsing them
-- loses the second: "who assigned this to me and when" is the question a
-- moderator picking up somebody else's work actually asks.
--
-- What is deliberately absent: private messages as a target (F60 has no tables
-- yet) and notifications on state changes (F55). Omitted rather than stubbed —
-- a `pm` kind nothing can produce is a column that lies about what the board
-- supports.

CREATE TABLE "reports" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  -- 'post' | 'thread' | 'user'. Text rather than an enum for the same reason
  -- `visibility` is: adding a kind must not need a type migration.
  "target_kind" text NOT NULL,
  "target_id" integer NOT NULL,

  -- Denormalised from the target, and null for a user report. This is what
  -- scopes the moderator list by `moderatedCommunityIds` without joining three
  -- tables per row — and it is what keeps a report readable after its target
  -- is hard-deleted.
  "community_id" integer REFERENCES "communities"("id") ON DELETE SET NULL,
  -- Likewise: the thread a post report is in, so the list can link to it.
  "thread_id" integer REFERENCES "threads"("id") ON DELETE SET NULL,
  -- A label captured at report time. The target may be edited or removed
  -- afterwards, and a moderator needs to know what was complained about.
  "target_label" text NOT NULL DEFAULT '',

  "reporter_user_id" integer REFERENCES "users"("id") ON DELETE SET NULL,
  "reason" text NOT NULL,

  -- 'open' | 'resolved' | 'rejected'. Assignment is a separate column rather
  -- than a status, because an assigned report is still open — modelling it as a
  -- state means "show me everything outstanding" has to list two of them.
  "status" text NOT NULL DEFAULT 'open',
  "assigned_to_user_id" integer REFERENCES "users"("id") ON DELETE SET NULL,

  "resolved_by_user_id" integer REFERENCES "users"("id") ON DELETE SET NULL,
  "resolved_at" timestamp with time zone,

  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp with time zone NOT NULL DEFAULT now()
);
--> statement-breakpoint

-- The history, and the only place a private moderator note lives.
--
-- Notes are on the *event*, not the report, so "resolved because X" stays
-- attached to the resolution rather than being overwritten by the next one.
-- Nothing in this table is ever shown to the reporter.
CREATE TABLE "report_events" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "report_id" integer NOT NULL REFERENCES "reports"("id") ON DELETE cascade,
  "actor_user_id" integer REFERENCES "users"("id") ON DELETE SET NULL,
  -- 'opened' | 'assigned' | 'unassigned' | 'resolved' | 'rejected' | 'note'
  "kind" text NOT NULL,
  "note" text,
  "created_at" timestamp with time zone NOT NULL DEFAULT now()
);
--> statement-breakpoint

-- The moderator list: outstanding reports in a set of communities, oldest first.
CREATE INDEX IF NOT EXISTS "reports_open_idx"
  ON "reports" ("community_id", "created_at")
  WHERE "status" = 'open';
--> statement-breakpoint

-- User reports have no community, so they need their own path to the same list.
CREATE INDEX IF NOT EXISTS "reports_open_global_idx"
  ON "reports" ("created_at")
  WHERE "status" = 'open' AND "community_id" IS NULL;
--> statement-breakpoint

-- One open report per person per target.
--
-- Not a nicety: without it, "report" is a button that adds a row to the
-- moderation queue on every click, which makes it the cheapest denial-of-
-- service on the board. Partial, so the same person may report the same post
-- again after a previous report was closed — circumstances change.
CREATE UNIQUE INDEX IF NOT EXISTS "reports_one_open_per_reporter_key"
  ON "reports" ("reporter_user_id", "target_kind", "target_id")
  WHERE "status" = 'open' AND "reporter_user_id" IS NOT NULL;
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "report_events_report_idx"
  ON "report_events" ("report_id", "created_at");
