CREATE TABLE "reports" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  "target_kind" text NOT NULL,
  "target_id" integer NOT NULL,

  "forum_id" integer REFERENCES "forums"("id") ON DELETE SET NULL,
  "thread_id" integer REFERENCES "threads"("id") ON DELETE SET NULL,
  "target_label" text NOT NULL DEFAULT '',

  "reporter_user_id" integer REFERENCES "users"("id") ON DELETE SET NULL,
  "reason" text NOT NULL,

  "status" text NOT NULL DEFAULT 'open',
  "assigned_to_user_id" integer REFERENCES "users"("id") ON DELETE SET NULL,

  "resolved_by_user_id" integer REFERENCES "users"("id") ON DELETE SET NULL,
  "resolved_at" timestamp with time zone,

  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp with time zone NOT NULL DEFAULT now()
);
--> statement-breakpoint

CREATE TABLE "report_events" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "report_id" integer NOT NULL REFERENCES "reports"("id") ON DELETE cascade,
  "actor_user_id" integer REFERENCES "users"("id") ON DELETE SET NULL,
  "kind" text NOT NULL,
  "note" text,
  "created_at" timestamp with time zone NOT NULL DEFAULT now()
);
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "reports_open_idx"
  ON "reports" ("forum_id", "created_at")
  WHERE "status" = 'open';
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "reports_open_global_idx"
  ON "reports" ("created_at")
  WHERE "status" = 'open' AND "forum_id" IS NULL;
--> statement-breakpoint

CREATE UNIQUE INDEX IF NOT EXISTS "reports_one_open_per_reporter_key"
  ON "reports" ("reporter_user_id", "target_kind", "target_id")
  WHERE "status" = 'open' AND "reporter_user_id" IS NOT NULL;
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "report_events_report_idx"
  ON "report_events" ("report_id", "created_at");
