CREATE TABLE "warning_types" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "title" text NOT NULL,
  "points" smallint NOT NULL DEFAULT 1,
  "expiry_days" integer,
  "is_active" boolean NOT NULL DEFAULT true,
  "display_order" integer NOT NULL DEFAULT 0,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp with time zone NOT NULL DEFAULT now()
);
--> statement-breakpoint

CREATE TABLE "warning_levels" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "points" smallint NOT NULL,
  "action" text NOT NULL,
  "duration_days" integer,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "warning_levels_points_unique" UNIQUE ("points")
);
--> statement-breakpoint

CREATE TABLE "warnings" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  "user_id" integer NOT NULL REFERENCES "users"("id") ON DELETE cascade,
  "issued_by_user_id" integer REFERENCES "users"("id") ON DELETE SET NULL,

  "type_id" integer REFERENCES "warning_types"("id") ON DELETE SET NULL,
  "title" text NOT NULL,
  "points" smallint NOT NULL,
  "reason" text NOT NULL DEFAULT '',

  "post_id" integer REFERENCES "posts"("id") ON DELETE SET NULL,
  "report_id" integer REFERENCES "reports"("id") ON DELETE SET NULL,

  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "expires_at" timestamp with time zone,

  "revoked_at" timestamp with time zone,
  "revoked_by_user_id" integer REFERENCES "users"("id") ON DELETE SET NULL,
  "revoke_reason" text
);
--> statement-breakpoint

CREATE INDEX "warnings_user_idx" ON "warnings" ("user_id", "created_at" DESC, "id" DESC);
--> statement-breakpoint

CREATE INDEX "warnings_live_idx"
  ON "warnings" ("user_id")
  INCLUDE ("points", "expires_at")
  WHERE "revoked_at" IS NULL;
--> statement-breakpoint

CREATE INDEX "warnings_expiry_idx"
  ON "warnings" ("expires_at")
  WHERE "revoked_at" IS NULL AND "expires_at" IS NOT NULL;
--> statement-breakpoint

ALTER TABLE "users" ADD COLUMN "suspended_posting_until" timestamp with time zone;
--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "moderated_posting_until" timestamp with time zone;
--> statement-breakpoint

INSERT INTO "warning_types" ("id", "title", "points", "expiry_days", "display_order") VALUES
  (1, 'Spamming', 2, 90, 10),
  (2, 'Advertising', 3, 180, 20),
  (3, 'Offensive language', 2, 90, 30),
  (4, 'Trolling or flaming', 2, 90, 40),
  (5, 'Posting in the wrong forum', 1, 30, 50),
  (6, 'Ignoring a moderator', 3, 180, 60);
--> statement-breakpoint

SELECT setval(
  pg_get_serial_sequence('warning_types', 'id'),
  (SELECT max(id) FROM "warning_types")
);
--> statement-breakpoint

INSERT INTO "warning_levels" ("points", "action", "duration_days") VALUES
  (4, 'moderate_posting', 30),
  (7, 'suspend_posting', 14),
  (10, 'ban', NULL);
--> statement-breakpoint

ALTER TABLE "usergroups"
  ADD COLUMN "can_warn_users" boolean NOT NULL DEFAULT false;
--> statement-breakpoint

UPDATE "usergroups" SET "can_warn_users" = true
 WHERE "key" IN ('administrators', 'super_moderators', 'moderators');
