-- F53 — warnings.
--
-- `users.warning_points` has existed since 0000 with nothing that writes it.
-- This is what writes it, and the shape follows from one decision: **the column
-- is a cache of the live warnings, never the record itself.**
--
-- A points *total* that is incremented and decremented cannot survive a
-- revocation. Revoking a three-point warning issued four months ago has to
-- subtract three from a number that has since been decremented by two expiries
-- and incremented by a fourth warning, and if any one of those steps was missed
-- the total is wrong with nothing to compare it against. So the total is
-- recomputed from `warnings` — where every issue, expiry and revocation is a
-- row — after anything changes it. That is the same argument F38 makes for
-- `PostgresCounterRecount`, applied to a counter small enough to recompute
-- every time rather than on a schedule.
--
-- What is deliberately absent: notifying the warned member (F55 has no
-- notification path), and any admin surface for editing types or levels (F66's
-- screen). Omitted rather than stubbed, per D32.

-- The reusable reasons a moderator picks from.
--
-- A warning may also be free-text, which is why `warnings.type_id` is nullable:
-- a board that has not configured any types must still be able to warn somebody,
-- or the feature does not exist until an administrator visits a screen that
-- does not exist yet either.
CREATE TABLE "warning_types" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "title" text NOT NULL,
  "points" smallint NOT NULL DEFAULT 1,
  -- NULL = never expires. Not 0, which would be indistinguishable from
  -- "expires immediately" and is the sentinel D-for-promotions already refused.
  "expiry_days" integer,
  "is_active" boolean NOT NULL DEFAULT true,
  "display_order" integer NOT NULL DEFAULT 0,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp with time zone NOT NULL DEFAULT now()
);
--> statement-breakpoint

-- What happens when a member's total reaches a threshold.
--
-- Levels are *thresholds*, not steps: the level that applies is the
-- highest-pointed one the member has reached, so removing a level or inserting
-- one between two others changes future evaluations and never leaves a member
-- stranded at a level that no longer exists. Re-evaluated from the recomputed
-- total after every change, which is what makes a revocation actually lift a
-- restriction rather than only lowering a number.
CREATE TABLE "warning_levels" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "points" smallint NOT NULL,
  -- 'suspend_posting' | 'moderate_posting' | 'ban'. Text rather than an enum,
  -- for the reason `visibility` is: adding an action must not need a type
  -- migration.
  "action" text NOT NULL,
  -- NULL = for as long as the member is at this level. A duration makes the
  -- restriction outlive the points; without one it lifts when they do.
  "duration_days" integer,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "warning_levels_points_unique" UNIQUE ("points")
);
--> statement-breakpoint

-- One issued warning. The record; `users.warning_points` is the cache of it.
CREATE TABLE "warnings" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  "user_id" integer NOT NULL REFERENCES "users"("id") ON DELETE cascade,
  "issued_by_user_id" integer REFERENCES "users"("id") ON DELETE SET NULL,

  -- The type it came from, and the values *as they were at the time*. A type
  -- whose points are edited from 3 to 1 next year must not silently rewrite
  -- every warning ever issued under it — a member's history is a record of what
  -- they were told, not a view over current configuration.
  "type_id" integer REFERENCES "warning_types"("id") ON DELETE SET NULL,
  "title" text NOT NULL,
  "points" smallint NOT NULL,
  "reason" text NOT NULL DEFAULT '',

  -- What it was about, when it was about something. Both nullable: a warning
  -- can be issued for conduct with no single artefact behind it.
  "post_id" integer REFERENCES "posts"("id") ON DELETE SET NULL,
  "report_id" integer REFERENCES "reports"("id") ON DELETE SET NULL,

  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  -- NULL = never expires.
  "expires_at" timestamp with time zone,

  -- Revocation is a column pair rather than a deletion, because "this warning
  -- was withdrawn" is information a member is entitled to and a moderator needs.
  -- A deleted row cannot say a mistake was corrected.
  "revoked_at" timestamp with time zone,
  "revoked_by_user_id" integer REFERENCES "users"("id") ON DELETE SET NULL,
  "revoke_reason" text
);
--> statement-breakpoint

-- The history read: one member's warnings, newest first.
CREATE INDEX "warnings_user_idx" ON "warnings" ("user_id", "created_at" DESC, "id" DESC);
--> statement-breakpoint

-- The recalculation read, and the only one that runs on a hot path. Partial,
-- because a board's warnings are overwhelmingly expired or revoked and only the
-- live ones are ever summed.
CREATE INDEX "warnings_live_idx"
  ON "warnings" ("user_id")
  INCLUDE ("points", "expires_at")
  WHERE "revoked_at" IS NULL;
--> statement-breakpoint

-- The expiry sweep: warnings past their date that still count. Acts on
-- outstanding state rather than "what expired since the last run", which is
-- what makes a skipped tick cost a delay and nothing else (F06).
CREATE INDEX "warnings_expiry_idx"
  ON "warnings" ("expires_at")
  WHERE "revoked_at" IS NULL AND "expires_at" IS NOT NULL;
--> statement-breakpoint

-- The two restrictions a warning level can impose, on the row the posting path
-- already reads.
--
-- Columns rather than a `user_restrictions` table because there is at most one
-- of each per member and the posting path needs both on every post: a join for
-- a row that is almost always absent is a join on the board's hottest write.
-- NULL means no restriction; a timestamp in the past is one that has lapsed and
-- is treated as absent, so nothing has to be swept for correctness.
ALTER TABLE "users" ADD COLUMN "suspended_posting_until" timestamp with time zone;
--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "moderated_posting_until" timestamp with time zone;
--> statement-breakpoint

-- Seed the ladder MyBB ships with, expressed in points rather than percentages.
--
-- Percentages need a configured maximum to be meaningful, and a board that has
-- never opened the admin screen would have every member permanently at 0% of
-- nothing. Points are absolute and readable on their own.
INSERT INTO "warning_types" ("id", "title", "points", "expiry_days", "display_order") VALUES
  (1, 'Spamming', 2, 90, 10),
  (2, 'Advertising', 3, 180, 20),
  (3, 'Offensive language', 2, 90, 30),
  (4, 'Trolling or flaming', 2, 90, 40),
  (5, 'Posting in the wrong community', 1, 30, 50),
  (6, 'Ignoring a moderator', 3, 180, 60);
--> statement-breakpoint

SELECT setval(
  pg_get_serial_sequence('warning_types', 'id'),
  (SELECT max(id) FROM "warning_types")
);
--> statement-breakpoint

INSERT INTO "warning_levels" ("points", "action", "duration_days") VALUES
  -- Held for review before the board sees it. The first level is deliberately
  -- reversible and invisible to everyone but the member and the moderators.
  (4, 'moderate_posting', 30),
  -- Cannot post at all, for a stated fortnight.
  (7, 'suspend_posting', 14),
  -- Banned, with no automatic end: a permanent ban is a human decision to
  -- review, and `duration_days` NULL is what says nobody set a date.
  (10, 'ban', NULL);
--> statement-breakpoint

-- F53's permission column.
--
-- Global rather than per-community: a warning is aimed at a person and its points
-- follow them across the whole board, so a per-community grant would have to answer
-- "warned where?" about a total that has no community. MyBB's `canwarnusers` is
-- global for the same reason.
--
-- Generated into the drizzle schema from `PERMISSION_FIELDS`, so this statement
-- is the only place the database has to be told.
ALTER TABLE "usergroups"
  ADD COLUMN "can_warn_users" boolean NOT NULL DEFAULT false;
--> statement-breakpoint

-- The staff ladder gets it. Moderators included: warning somebody is the
-- proportionate response to most of what a moderator finds, and a moderator who
-- can only delete posts has one tool for every problem.
UPDATE "usergroups" SET "can_warn_users" = true
 WHERE "key" IN ('administrators', 'super_moderators', 'moderators');
