CREATE TABLE "notifications" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  "user_id" integer NOT NULL REFERENCES "users"("id") ON DELETE cascade,

  "kind" text NOT NULL,

  "data" jsonb NOT NULL DEFAULT '{}'::jsonb,

  "href" text,

  "dedupe_key" text,
  "occurrences" integer NOT NULL DEFAULT 1,

  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp with time zone NOT NULL DEFAULT now(),

  "read_at" timestamp with time zone,

  "email_sent_at" timestamp with time zone
);
--> statement-breakpoint

CREATE INDEX "notifications_user_idx"
  ON "notifications" ("user_id", "created_at" DESC NULLS LAST, "id" DESC NULLS LAST);
--> statement-breakpoint

CREATE INDEX "notifications_unread_idx"
  ON "notifications" ("user_id")
  WHERE "read_at" IS NULL;
--> statement-breakpoint

CREATE UNIQUE INDEX "notifications_dedupe_idx"
  ON "notifications" ("user_id", "dedupe_key")
  WHERE "read_at" IS NULL AND "dedupe_key" IS NOT NULL;
--> statement-breakpoint

CREATE TABLE "notification_preferences" (
  "user_id" integer NOT NULL REFERENCES "users"("id") ON DELETE cascade,
  "kind" text NOT NULL,
  "email" boolean NOT NULL,
  "updated_at" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "notification_preferences_pkey" PRIMARY KEY ("user_id", "kind")
);
