-- F55 — notifications and their e-mail preferences.
--
-- Three finished features have been waiting on this table: a failing scheduled
-- task logs and raises nothing (F06), a report is filed and closed with nobody
-- told (F49), and a warned member finds out by trying to post and being refused
-- (F53). What they were all waiting for is a place to put "somebody needs to be
-- told something" that survives the request that noticed it.
--
-- Two decisions produce this shape.
--
-- **A notification stores captured facts, not pointers.** `data` is a small
-- JSON object written at raise time — a title, a points total, a task id — and
-- the sentence around it is applied when the notification is read. The
-- alternative, storing a post id and reading the post back, fails in exactly
-- the case notifications exist for: the post that caused it is frequently the
-- post a moderator has since deleted, and the warning behind one may have been
-- revoked. A record that changes when its subject changes is not a record.
--
-- **The unread row is the unit of coalescing.** A task failing every minute
-- would otherwise write 1,440 rows a day per administrator. A partial unique
-- index on the dedupe key *while unread* turns that into one row and a count —
-- and because the index only covers unread rows, an administrator who reads and
-- clears it is told again the next time it happens rather than never again.
-- That is F49's trick (a partial unique index rather than a prior read), used
-- for the same reason: two raises arriving together would both pass a check.

CREATE TABLE "notifications" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  "user_id" integer NOT NULL REFERENCES "users"("id") ON DELETE cascade,

  -- A registry id from `@forum/notifications`. Text rather than an enum, for
  -- the reason `visibility` and `warning_levels.action` are: adding a kind must
  -- not need a type migration, and a kind removed in a later deploy has to
  -- still render as *something* rather than break the read.
  "kind" text NOT NULL,

  -- The captured facts. Deliberately small and deliberately flat: this is not a
  -- place to query, it is a place to remember what was true.
  "data" jsonb NOT NULL DEFAULT '{}'::jsonb,

  -- Board-relative path. Nullable, because a system notification points at
  -- nothing a member can open.
  "href" text,

  -- Coalescing identity. NULL means "never coalesce": every warning is its own
  -- record even when two arrive in a minute, because they are two different
  -- things that happened.
  "dedupe_key" text,
  "occurrences" integer NOT NULL DEFAULT 1,

  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  -- Bumped when a raise coalesces into this row. Equal to `created_at` until
  -- one does, so "when did this last happen" is answerable without a history
  -- table nobody would read.
  "updated_at" timestamp with time zone NOT NULL DEFAULT now(),

  "read_at" timestamp with time zone,

  -- Set after a message goes out, so the ordinary queue retry does not send a
  -- second one. Not a claim taken *before* sending: that trades a rare
  -- duplicate for a lost message, which is the wrong way round for something a
  -- member is meant to read.
  "email_sent_at" timestamp with time zone
);
--> statement-breakpoint

-- The centre's read: one member's notifications, newest first.
CREATE INDEX "notifications_user_idx"
  ON "notifications" ("user_id", "created_at" DESC NULLS LAST, "id" DESC NULLS LAST);
--> statement-breakpoint

-- The unread count, which renders in the user panel on **every page** for a
-- logged-in member. Partial, so it holds only the rows that can contribute:
-- on a settled board almost every notification is read, and the count must not
-- pay for the history.
CREATE INDEX "notifications_unread_idx"
  ON "notifications" ("user_id")
  WHERE "read_at" IS NULL;
--> statement-breakpoint

-- The coalescing rule, enforced rather than checked. Partial on unread *and* on
-- a non-null key: a read notification no longer blocks a fresh one, and rows
-- that opt out of coalescing (`dedupe_key IS NULL`) are not constrained at all.
CREATE UNIQUE INDEX "notifications_dedupe_idx"
  ON "notifications" ("user_id", "dedupe_key")
  WHERE "read_at" IS NULL AND "dedupe_key" IS NOT NULL;
--> statement-breakpoint

-- Which kinds a member wants by e-mail.
--
-- Overrides only, exactly like `settings`: a row here is a member's answer, and
-- its absence means the registry default applies. That is what lets a kind
-- added in a later deploy arrive switched on for everybody rather than switched
-- off for everybody who ever opened this screen.
--
-- There is no on-site column, and its absence is the decision: every kind is
-- delivered to the notification centre. The centre is the board's record of
-- what a member was told, and a member who can switch the record off can later
-- say they were never warned — with the board's own data agreeing.
CREATE TABLE "notification_preferences" (
  "user_id" integer NOT NULL REFERENCES "users"("id") ON DELETE cascade,
  "kind" text NOT NULL,
  "email" boolean NOT NULL,
  "updated_at" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "notification_preferences_pkey" PRIMARY KEY ("user_id", "kind")
);
