CREATE TABLE "profile_fields" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  "key" text NOT NULL,
  "label" text NOT NULL,
  "description" text,

  "type" text NOT NULL DEFAULT 'text',

  "options" jsonb NOT NULL DEFAULT '[]'::jsonb,

  "max_length" integer,

  "display_order" integer NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,

  "required_at_registration" boolean NOT NULL DEFAULT false,

  "default_visible" boolean NOT NULL DEFAULT true,
  "default_editable" boolean NOT NULL DEFAULT true,

  "show_in_postbit" boolean NOT NULL DEFAULT false,

  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp with time zone NOT NULL DEFAULT now(),

  CONSTRAINT "profile_fields_key_unique" UNIQUE ("key")
);
--> statement-breakpoint

CREATE INDEX "profile_fields_order_idx"
  ON "profile_fields" ("display_order", "id");
--> statement-breakpoint

CREATE TABLE "profile_field_groups" (
  "field_id" integer NOT NULL REFERENCES "profile_fields"("id") ON DELETE cascade,
  "group_id" integer NOT NULL REFERENCES "usergroups"("id") ON DELETE cascade,
  "can_view" boolean,
  "can_edit" boolean,
  CONSTRAINT "profile_field_groups_pkey" PRIMARY KEY ("field_id", "group_id")
);
--> statement-breakpoint

CREATE TABLE "profile_field_values" (
  "user_id" integer NOT NULL REFERENCES "users"("id") ON DELETE cascade,
  "field_id" integer NOT NULL REFERENCES "profile_fields"("id") ON DELETE cascade,
  "value" text NOT NULL DEFAULT '',
  "updated_at" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "profile_field_values_pkey" PRIMARY KEY ("user_id", "field_id")
);
--> statement-breakpoint

CREATE INDEX "profile_field_values_user_idx" ON "profile_field_values" ("user_id");
