-- F59 — custom profile fields.
--
-- F57 gave a member three fields the board decided on: location, website, about.
-- This is the same idea handed to the operator — "Steam ID", "pronouns",
-- "which console", whatever the board is about — with three things F57's fixed
-- trio did not need: a **type**, a **per-group answer** to who may see and edit
-- each one, and a way to **ask at registration**.
--
-- Three tables, and the split follows what changes when.
--
-- `profile_fields` is configuration: it changes when an operator changes it.
-- `profile_field_groups` is the per-group override, shaped exactly like F21's
-- `community_permissions` — a row per (field, group) with **nullable** columns,
-- where NULL means "inherit the field's default". That shape is not a
-- coincidence: it is the one this board already resolves, and reusing it means
-- the mental model for "who can see this" is the same everywhere.
-- `profile_field_values` is member data, one row per member per answered field.

CREATE TABLE "profile_fields" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  -- The stable machine name. Migrations, imports and the operator CLI key off
  -- this rather than the label, so renaming "Location" to "Where are you?"
  -- keeps every stored answer attached to it.
  "key" text NOT NULL,
  "label" text NOT NULL,
  "description" text,

  -- 'text' | 'textarea' | 'select' | 'checkbox' | 'url' | 'number'.
  --
  -- Text rather than an enum, for the reason `visibility` and
  -- `warning_levels.action` are: adding a type must not need a type migration,
  -- and a type this build does not know has to degrade to a plain input rather
  -- than break the profile screen.
  "type" text NOT NULL DEFAULT 'text',

  -- The choices, for `select`. A JSON array of strings; empty for every other
  -- type. Not a `profile_field_options` table, because the options are read
  -- with the field on every render and never queried on their own — the same
  -- argument F55's `data` column makes.
  "options" jsonb NOT NULL DEFAULT '[]'::jsonb,

  -- NULL = the type's own default. A per-field limit exists because "pronouns"
  -- and "about my setup" want very different ones.
  "max_length" integer,

  "display_order" integer NOT NULL DEFAULT 0,
  -- Inactive keeps the values. A field an operator switches off is one they may
  -- switch back on, and deleting the row would take every member's answer with
  -- it — which is not what "hide this for now" means.
  "is_active" boolean NOT NULL DEFAULT true,

  -- Asked on the registration form, and refused if left empty (F18).
  "required_at_registration" boolean NOT NULL DEFAULT false,

  -- What applies when no group row says otherwise. Two booleans rather than a
  -- three-state visibility word: "who may see it" and "who may change it" are
  -- genuinely independent — a board can show a member's join reason to everyone
  -- while letting only staff write it.
  "default_visible" boolean NOT NULL DEFAULT true,
  "default_editable" boolean NOT NULL DEFAULT true,

  -- Shown beside every post as well as on the profile. Off by default: the
  -- postbit renders once per post on the board's heaviest page, and a field
  -- there is a decision rather than a convenience.
  "show_in_postbit" boolean NOT NULL DEFAULT false,

  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp with time zone NOT NULL DEFAULT now(),

  CONSTRAINT "profile_fields_key_unique" UNIQUE ("key")
);
--> statement-breakpoint

-- Every read of this table is "the whole list, in order": the profile screen,
-- the UserCP and the postbit all want all of it.
CREATE INDEX "profile_fields_order_idx"
  ON "profile_fields" ("display_order", "id");
--> statement-breakpoint

-- The per-group override, in F21's shape.
--
-- NULL means inherit, which is what makes "staff may edit this" one row rather
-- than a row per group with the other answer copied into it. The resolution is
-- R4.2's: any group granting is a grant.
CREATE TABLE "profile_field_groups" (
  "field_id" integer NOT NULL REFERENCES "profile_fields"("id") ON DELETE cascade,
  "group_id" integer NOT NULL REFERENCES "usergroups"("id") ON DELETE cascade,
  "can_view" boolean,
  "can_edit" boolean,
  CONSTRAINT "profile_field_groups_pkey" PRIMARY KEY ("field_id", "group_id")
);
--> statement-breakpoint

-- One member's answer to one field.
--
-- A row exists only once somebody answers, so an unanswered field costs
-- nothing — which matters when a board with twelve fields has ten thousand
-- members who filled in two.
CREATE TABLE "profile_field_values" (
  "user_id" integer NOT NULL REFERENCES "users"("id") ON DELETE cascade,
  "field_id" integer NOT NULL REFERENCES "profile_fields"("id") ON DELETE cascade,
  "value" text NOT NULL DEFAULT '',
  "updated_at" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "profile_field_values_pkey" PRIMARY KEY ("user_id", "field_id")
);
--> statement-breakpoint

-- The profile read: one member's answers. The postbit read is the same shape
-- for one author at a time.
CREATE INDEX "profile_field_values_user_idx" ON "profile_field_values" ("user_id");
