CREATE TABLE "private_messages" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  "author_user_id" integer REFERENCES "users"("id") ON DELETE SET NULL,
  "author_username" text NOT NULL DEFAULT '',

  "subject" text NOT NULL,

  "message" text NOT NULL,
  "message_html" text,
  "render_version" smallint NOT NULL DEFAULT 0,

  "reply_to_id" integer REFERENCES "private_messages"("id") ON DELETE SET NULL,

  "receipt_requested" boolean NOT NULL DEFAULT false,

  "sent_at" timestamp with time zone NOT NULL DEFAULT now()
);
--> statement-breakpoint

CREATE TABLE "private_message_copies" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "message_id" integer NOT NULL REFERENCES "private_messages"("id") ON DELETE cascade,
  "owner_user_id" integer NOT NULL REFERENCES "users"("id") ON DELETE cascade,

  "folder" text NOT NULL DEFAULT 'inbox',

  "role" text NOT NULL DEFAULT 'to',

  "read_at" timestamp with time zone,

  "created_at" timestamp with time zone NOT NULL DEFAULT now(),

  CONSTRAINT "private_message_copies_unique" UNIQUE ("message_id", "owner_user_id")
);
--> statement-breakpoint

CREATE INDEX "private_message_copies_folder_idx"
  ON "private_message_copies" ("owner_user_id", "folder", "id" DESC);
--> statement-breakpoint

CREATE INDEX "private_message_copies_unread_idx"
  ON "private_message_copies" ("owner_user_id")
  WHERE "read_at" IS NULL AND "folder" = 'inbox';
--> statement-breakpoint

CREATE INDEX "private_message_copies_message_idx"
  ON "private_message_copies" ("message_id");
--> statement-breakpoint

CREATE INDEX "private_messages_render_version_idx"
  ON "private_messages" ("render_version", "id");
--> statement-breakpoint

ALTER TABLE "usergroups" ADD COLUMN "private_message_quota" integer DEFAULT 0 NOT NULL;
--> statement-breakpoint

UPDATE "usergroups" SET "private_message_quota" = 100 WHERE "key" = 'registered';
--> statement-breakpoint
UPDATE "usergroups" SET "private_message_quota" = 100 WHERE "key" = 'awaiting_activation';
--> statement-breakpoint
UPDATE "usergroups" SET "private_message_quota" = 0
 WHERE "key" IN ('administrators', 'super_moderators', 'moderators');
