-- F60 — private messages.
--
-- Two tables, and the split is the one decision everything else follows from:
-- **the message is stored once, and each participant owns a *copy* of it.**
--
-- MyBB stores a row per copy — sender's Sent Items and every recipient's Inbox
-- each hold the full subject and body — so a message to twenty people is twenty
-- copies of the text, and editing or re-rendering one is twenty writes. Here
-- `private_messages` holds the content and `private_message_copies` holds one
-- small row per person: which folder they filed it in, whether they have read
-- it, and when. Quota then counts *copies*, which is the thing a member can
-- actually delete.
--
-- The cost is a join on every listing, which is what the two indexes at the
-- bottom exist for.

CREATE TABLE "private_messages" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  -- SET NULL rather than cascade: deleting an account must not silently delete
  -- messages other people still hold. The username is captured alongside for
  -- the same reason F49 captures a target label — the row has to stay readable.
  "author_user_id" integer REFERENCES "users"("id") ON DELETE SET NULL,
  "author_username" text NOT NULL DEFAULT '',

  "subject" text NOT NULL,

  -- Raw BBCode and F36's render cache, exactly as `posts` carries them. A PM
  -- body is the same kind of thing a post body is, rendered by the same
  -- renderer at the same version, so a security fix to the renderer takes
  -- effect here on the next page load like it does everywhere else.
  "message" text NOT NULL,
  "message_html" text,
  "render_version" smallint NOT NULL DEFAULT 0,

  -- The message this one answers, so a reply can show what it replied to.
  -- SET NULL: the parent may be deleted by everybody who held a copy.
  "reply_to_id" integer REFERENCES "private_messages"("id") ON DELETE SET NULL,

  -- The sender asked to be told when it is read (F60's read receipt). The
  -- *tracking* half needs no flag — `read_at` below is recorded either way —
  -- so this column only decides whether a notification is raised.
  "receipt_requested" boolean NOT NULL DEFAULT false,

  "sent_at" timestamp with time zone NOT NULL DEFAULT now()
);
--> statement-breakpoint

-- One person's copy of one message.
--
-- `folder` is a system folder rather than a foreign key to a user-defined one.
-- Custom folders need a management screen and a move-to picker with an
-- unbounded list; the three below are what makes the feature work, and the
-- fourth state MyBB has (drafts) belongs to F44, which has no table.
CREATE TABLE "private_message_copies" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "message_id" integer NOT NULL REFERENCES "private_messages"("id") ON DELETE cascade,
  "owner_user_id" integer NOT NULL REFERENCES "users"("id") ON DELETE cascade,

  -- 'inbox' | 'sent' | 'trash'. Text rather than an enum, like every other
  -- state column on this board: adding a folder must not need a type migration.
  "folder" text NOT NULL DEFAULT 'inbox',

  -- 'author' | 'to' | 'bcc'. What this copy records, which is not the same
  -- question as which folder it is in — a sender who trashes their Sent copy
  -- is still the author.
  "role" text NOT NULL DEFAULT 'to',

  -- NULL means unread. A timestamp rather than a boolean because the sender's
  -- tracking screen wants *when*, and "read" is `read_at IS NOT NULL`.
  "read_at" timestamp with time zone,

  "created_at" timestamp with time zone NOT NULL DEFAULT now(),

  -- One copy per person per message. This is also the dedupe for a sender who
  -- names the same recipient twice, and the reason sending to yourself is
  -- refused in the service rather than handled with a second row.
  CONSTRAINT "private_message_copies_unique" UNIQUE ("message_id", "owner_user_id")
);
--> statement-breakpoint

-- The folder listing: one member's copies in one folder, newest first.
--
-- `id` breaks the tie because two messages can share a second, and a listing
-- whose order is not total pages inconsistently — the same argument F40's
-- keyset cursor makes.
CREATE INDEX "private_message_copies_folder_idx"
  ON "private_message_copies" ("owner_user_id", "folder", "id" DESC);
--> statement-breakpoint

-- The unread badge, and the count on the folder tabs. Partial, because unread
-- is the small set and the index should not carry a board's whole history of
-- read mail to answer "how many are new".
CREATE INDEX "private_message_copies_unread_idx"
  ON "private_message_copies" ("owner_user_id")
  WHERE "read_at" IS NULL AND "folder" = 'inbox';
--> statement-breakpoint

-- The sender's tracking view: every copy of one message.
CREATE INDEX "private_message_copies_message_idx"
  ON "private_message_copies" ("message_id");
--> statement-breakpoint

-- F36's backfill predicate, for the same reason `posts` has one: a stale render
-- is a live render, and the task rewrites them in bounded batches.
CREATE INDEX "private_messages_render_version_idx"
  ON "private_messages" ("render_version", "id");
--> statement-breakpoint

-- How many messages a member may *keep* (F60).
--
-- Distinct from `max_private_messages_per_day`, which has existed since `0000`
-- and is a send *rate*. This one is storage, and it is what a full inbox means.
-- 0 = unlimited, like every other numeric permission, so the default here is
-- the deny-by-default fallback in name only: the seed below gives the real
-- per-group values.
ALTER TABLE "usergroups" ADD COLUMN "private_message_quota" integer DEFAULT 0 NOT NULL;
--> statement-breakpoint

-- The ladder, matching `0001`'s shape: members get a bounded box, staff do not.
-- A guest cannot hold a message at all, and its 0 is unreachable rather than
-- generous — `can_use_private_messages` is false for that group.
UPDATE "usergroups" SET "private_message_quota" = 100 WHERE "key" = 'registered';
--> statement-breakpoint
UPDATE "usergroups" SET "private_message_quota" = 100 WHERE "key" = 'awaiting_activation';
--> statement-breakpoint
UPDATE "usergroups" SET "private_message_quota" = 0
 WHERE "key" IN ('administrators', 'super_moderators', 'moderators');
