-- F62 — reputation.
--
-- One table, and the interesting part is that **the two rate limits are two
-- different mechanisms, because they are two different shapes.**
--
--   * "One rating per person per target" is a *uniqueness* rule, and it is
--     enforced by a unique index — the same trick F49's duplicate-report guard
--     uses (D48). A check-then-insert would let two clicks arriving together
--     both pass, and a reputation button that adds a row on every click is the
--     cheapest way to inflate a total.
--   * "At most N a day" is a *window*, which no index can express. It is a
--     count inside the writing transaction, and its residual race is stated
--     rather than hidden: two concurrent inserts can both see N-1 and both
--     commit, so the real ceiling is N+1 for somebody scripting it. That is a
--     rate limit, not a permission, and being one over is not a security event.
--
-- `users.reputation` has existed since `0000` with **no writer**. It gets one
-- here, and it is **derived, never incremented** — recomputed from the live
-- rows in the same transaction as anything that changes them, exactly as F53
-- does with `warning_points`. An incremented total cannot survive a rating
-- being revised or withdrawn, and drifts silently when it does.

CREATE TABLE "reputation" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  -- Who it is about.
  "user_id" integer NOT NULL REFERENCES "users"("id") ON DELETE cascade,

  -- Who gave it. SET NULL rather than cascade: removing an account must not
  -- silently rewrite everybody else's totals, and the recount below treats a
  -- null giver as a rating that still counts. Somebody's reputation is a record
  -- of what the board thought, not a list of currently-active accounts.
  "given_by_user_id" integer REFERENCES "users"("id") ON DELETE SET NULL,

  -- The post it is about, or NULL for a rating left on the profile. Two shapes
  -- with two uniqueness rules; see the indexes below.
  "post_id" integer REFERENCES "posts"("id") ON DELETE cascade,

  -- Bounded by the service, not by the column: a board that later allows ±2
  -- should not need a migration. smallint because the value is single digits
  -- and the *total* is the integer column on `users`.
  "points" smallint NOT NULL DEFAULT 1,

  -- Why. Required or optional by board setting; stored as plain text and
  -- rendered as plain text — a reputation comment is short, is shown on a
  -- profile every member can visit, and has no reason to carry markup.
  "comment" text NOT NULL DEFAULT '',

  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp with time zone NOT NULL DEFAULT now()
);
--> statement-breakpoint

-- One profile rating per pair, ever.
--
-- Partial, because a member may also rate any number of that person's *posts*.
-- Re-rating somebody updates this row rather than adding a second, which is
-- what makes "change your mind" a supported act instead of a way to stack
-- points.
CREATE UNIQUE INDEX "reputation_profile_unique"
  ON "reputation" ("given_by_user_id", "user_id")
  WHERE "post_id" IS NULL;
--> statement-breakpoint

-- One rating per person per post.
CREATE UNIQUE INDEX "reputation_post_unique"
  ON "reputation" ("given_by_user_id", "post_id")
  WHERE "post_id" IS NOT NULL;
--> statement-breakpoint

-- The history screen: everything about one member, newest first.
CREATE INDEX "reputation_user_idx" ON "reputation" ("user_id", "id" DESC);
--> statement-breakpoint

-- The daily cap's count, and "what have I given" on somebody's own screen.
CREATE INDEX "reputation_given_idx"
  ON "reputation" ("given_by_user_id", "created_at" DESC);
--> statement-breakpoint

-- Per-group limits (F62).
--
-- Two fields, both global: reputation is a board-wide capability, so neither
-- belongs in F22's forum matrix — the same argument `canReportContent` and
-- `canWarnUsers` make.
ALTER TABLE "usergroups" ADD COLUMN "can_give_reputation" boolean DEFAULT false NOT NULL;
--> statement-breakpoint
ALTER TABLE "usergroups" ADD COLUMN "max_reputation_per_day" integer DEFAULT 0 NOT NULL;
--> statement-breakpoint

-- The ladder, matching `0001`'s shape: members may rate with a daily cap, staff
-- are uncapped (0 = unlimited, like every numeric permission). Guests and
-- awaiting-activation cannot rate at all — reputation from an account nobody
-- has confirmed is the first thing a spammer reaches for.
UPDATE "usergroups" SET "can_give_reputation" = true, "max_reputation_per_day" = 10
 WHERE "key" = 'registered';
--> statement-breakpoint
UPDATE "usergroups" SET "can_give_reputation" = true, "max_reputation_per_day" = 0
 WHERE "key" IN ('administrators', 'super_moderators', 'moderators');
