CREATE TABLE "reputation" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  "user_id" integer NOT NULL REFERENCES "users"("id") ON DELETE cascade,

  "given_by_user_id" integer REFERENCES "users"("id") ON DELETE SET NULL,

  "post_id" integer REFERENCES "posts"("id") ON DELETE cascade,

  "points" smallint NOT NULL DEFAULT 1,

  "comment" text NOT NULL DEFAULT '',

  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp with time zone NOT NULL DEFAULT now()
);
--> statement-breakpoint

CREATE UNIQUE INDEX "reputation_profile_unique"
  ON "reputation" ("given_by_user_id", "user_id")
  WHERE "post_id" IS NULL;
--> statement-breakpoint

CREATE UNIQUE INDEX "reputation_post_unique"
  ON "reputation" ("given_by_user_id", "post_id")
  WHERE "post_id" IS NOT NULL;
--> statement-breakpoint

CREATE INDEX "reputation_user_idx" ON "reputation" ("user_id", "id" DESC);
--> statement-breakpoint

CREATE INDEX "reputation_given_idx"
  ON "reputation" ("given_by_user_id", "created_at" DESC);
--> statement-breakpoint

ALTER TABLE "usergroups" ADD COLUMN "can_give_reputation" boolean DEFAULT false NOT NULL;
--> statement-breakpoint
ALTER TABLE "usergroups" ADD COLUMN "max_reputation_per_day" integer DEFAULT 0 NOT NULL;
--> statement-breakpoint

UPDATE "usergroups" SET "can_give_reputation" = true, "max_reputation_per_day" = 10
 WHERE "key" = 'registered';
--> statement-breakpoint
UPDATE "usergroups" SET "can_give_reputation" = true, "max_reputation_per_day" = 0
 WHERE "key" IN ('administrators', 'super_moderators', 'moderators');
