CREATE TABLE "admin_sessions" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL REFERENCES "users"("id") ON DELETE cascade,

  "token_hash" text NOT NULL,

  "ip_prefix" text,

  "authenticated_at" timestamp with time zone NOT NULL DEFAULT now(),
  "last_seen_at" timestamp with time zone NOT NULL DEFAULT now(),

  "expires_at" timestamp with time zone NOT NULL,
  "revoked_at" timestamp with time zone,
  "created_at" timestamp with time zone NOT NULL DEFAULT now()
);
--> statement-breakpoint

CREATE UNIQUE INDEX "admin_sessions_token_hash_key"
  ON "admin_sessions" ("token_hash");
--> statement-breakpoint

CREATE INDEX "admin_sessions_user_idx" ON "admin_sessions" ("user_id");
--> statement-breakpoint
CREATE INDEX "admin_sessions_expiry_idx" ON "admin_sessions" ("expires_at");
