-- F63 — the admin control panel's own authentication.
--
-- **A second session, not a second account.** An administrator signs in to the
-- board as themselves; entering the ACP asks for their password *again* and
-- mints a separate, short-lived session. The board session stays untouched.
--
-- Why the separation is worth a table:
--
--   * An unattended browser is the realistic threat. A board session lasts
--     days by design (F17's remember-me is thirty); an ACP session that
--     inherited that would mean a laptop left open in a café is a board
--     takeover rather than an embarrassment.
--   * The ACP's idle timeout can therefore be minutes without making the board
--     unusable, because expiring it logs somebody out of `/admin` and nothing
--     else.
--   * `authenticated_at` is a *separate* clock from `last_seen_at`, and it is
--     what "re-authenticate before this destructive operation" reads. Activity
--     extends the session; only re-entering the password moves the proof.
--
-- The token is stored as a hash, exactly as `sessions` and `credential_tokens`
-- do it: a database read must not hand somebody a live session.

CREATE TABLE "admin_sessions" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL REFERENCES "users"("id") ON DELETE cascade,

  -- SHA-256 of the cookie value. Never the value itself.
  "token_hash" text NOT NULL,

  -- Truncated per F09 — never a full address. Recorded so the log can say
  -- *where from*, which is the question asked after something goes wrong.
  "ip_prefix" text,

  -- When the password was last proved. Moved only by a re-authentication,
  -- never by activity — that is the whole point of it being separate.
  "authenticated_at" timestamp with time zone NOT NULL DEFAULT now(),
  -- Moved by activity, on the same conditional-UPDATE throttle F61 uses.
  "last_seen_at" timestamp with time zone NOT NULL DEFAULT now(),

  "expires_at" timestamp with time zone NOT NULL,
  "revoked_at" timestamp with time zone,
  "created_at" timestamp with time zone NOT NULL DEFAULT now()
);
--> statement-breakpoint

-- The lookup on every ACP request: one hash, one row.
CREATE UNIQUE INDEX "admin_sessions_token_hash_key"
  ON "admin_sessions" ("token_hash");
--> statement-breakpoint

-- "Sign me out of the ACP everywhere", and the sweep of expired rows.
CREATE INDEX "admin_sessions_user_idx" ON "admin_sessions" ("user_id");
--> statement-breakpoint
CREATE INDEX "admin_sessions_expiry_idx" ON "admin_sessions" ("expires_at");
