-- F42 — attachments.
--
-- One table. What is worth reading is the *lifecycle*, because it is what makes
-- an upload safe rather than merely validated.
--
-- **The bytes a member uploads are never the bytes the board serves.** An
-- upload lands as `pending` with its original object written under
-- `source_key`; a queued job decodes it, re-encodes it from raw pixels, writes
-- the result under `storage_key`, and only then is the row `ready`. Nothing is
-- downloadable before that. See ADR 0003: validation tells you a file *claims*
-- to be a PNG, and re-encoding is what makes it one — a ZIP appended after the
-- IEND chunk survives every check and does not survive a decode/encode.
--
-- Consequences of the two keys:
--
--   * `source_key` is dropped once processing succeeds, so the hostile bytes do
--     not outlive the job that read them. A row with both keys set is a job
--     that died half-way, and the sweep collects it.
--   * A file the board cannot re-encode (a PDF, a ZIP) has no source phase at
--     all: it is stored once and is `ready` immediately, because there is no
--     transformation to wait for. It is served with `Content-Disposition:
--     attachment` and `nosniff`, which is the whole of what can be promised
--     about a format we do not parse.
--
-- `post_id` is NOT NULL and the row is written *after* its post. The alternative
-- — a draft attachment waiting for a post that may never come — needs an
-- upload token, a composer round trip, and a sweep for abandoned drafts. This
-- board submits a reply and its files in one form post (no JavaScript
-- required), so the row can simply reference a post that already exists.
--
-- What *can* be orphaned is an object in the file store: it is written before
-- the post, so a failure in between leaves bytes with no row. `attachment_orphans`
-- records every key at the moment it is written and is cleared when the row
-- that owns it commits, which turns "find files with no row" — impossible to
-- ask a bucket cheaply — into an indexed query on a small table.

CREATE TABLE "attachments" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  "post_id" integer NOT NULL REFERENCES "posts"("id") ON DELETE cascade,
  -- Denormalised from the post so a download can be authorised with one read.
  -- The permission is community-scoped, and joining posts->threads->communities on every
  -- attachment fetch to learn a value that cannot change would be a join per
  -- image on every thread page.
  "community_id" integer NOT NULL REFERENCES "communities"("id") ON DELETE cascade,
  "uploader_user_id" integer REFERENCES "users"("id") ON DELETE set null,

  -- The member's filename, sanitised. Display only: it never reaches a path.
  "filename" text NOT NULL,
  -- The *sniffed* type, never the browser's claim.
  "content_type" text NOT NULL,
  "size_bytes" integer NOT NULL,

  -- What the board serves. NULL until processing succeeds.
  "storage_key" text,
  -- What the member uploaded. NULL once it does.
  "source_key" text,
  -- The generated thumbnail, for images larger than the inline limit.
  "thumbnail_key" text,

  "width" integer,
  "height" integer,

  -- pending | ready | failed
  "status" text NOT NULL DEFAULT 'pending',
  -- Shown to the uploader, not just logged: "your image could not be
  -- processed" with no reason is a bug report nobody can act on.
  "failure_reason" text,

  "download_count" integer NOT NULL DEFAULT 0,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "ready_at" timestamp with time zone
);
--> statement-breakpoint

-- The postbit's read: every attachment on the posts of one page.
CREATE INDEX "attachments_post_idx" ON "attachments" ("post_id");
--> statement-breakpoint

-- The uploader's own total, for a per-member quota and for the ACP later.
CREATE INDEX "attachments_uploader_idx" ON "attachments" ("uploader_user_id");
--> statement-breakpoint

-- The processing sweep: rows a job never finished. Partial, because on a
-- settled board almost every row is `ready` and this index should be tiny.
CREATE INDEX "attachments_pending_idx" ON "attachments" ("created_at")
  WHERE "status" = 'pending';
--> statement-breakpoint

-- Two objects can never share a key, which is what makes deleting one row's
-- object safe without checking whether another row points at it.
CREATE UNIQUE INDEX "attachments_storage_key_key" ON "attachments" ("storage_key")
  WHERE "storage_key" IS NOT NULL;
--> statement-breakpoint
CREATE UNIQUE INDEX "attachments_source_key_key" ON "attachments" ("source_key")
  WHERE "source_key" IS NOT NULL;
--> statement-breakpoint

-- Every object written to the store, from the moment it is written.
--
-- A row is inserted *before* the `put`, and deleted when an `attachments` row
-- takes ownership of the key or when the object is deleted. What is left is
-- exactly the set of keys that may exist in the bucket with nothing pointing at
-- them: a crash between the put and the insert, a post that failed validation
-- after its files were stored, a processing job that died between writing the
-- re-encoded object and updating the row.
--
-- The alternative is listing the bucket and diffing it against the table, which
-- costs a full scan of both and is wrong the moment an upload is in flight.
CREATE TABLE "attachment_orphans" (
  "storage_key" text PRIMARY KEY,
  "created_at" timestamp with time zone NOT NULL DEFAULT now()
);
--> statement-breakpoint

-- The sweep, oldest first, with a grace period so an in-flight upload is never
-- collected out from under itself.
CREATE INDEX "attachment_orphans_age_idx" ON "attachment_orphans" ("created_at");
