CREATE TABLE "attachments" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  "post_id" integer NOT NULL REFERENCES "posts"("id") ON DELETE cascade,
  "forum_id" integer NOT NULL REFERENCES "forums"("id") ON DELETE cascade,
  "uploader_user_id" integer REFERENCES "users"("id") ON DELETE set null,

  "filename" text NOT NULL,
  "content_type" text NOT NULL,
  "size_bytes" integer NOT NULL,

  "storage_key" text,
  "source_key" text,
  "thumbnail_key" text,

  "width" integer,
  "height" integer,

  "status" text NOT NULL DEFAULT 'pending',
  "failure_reason" text,

  "download_count" integer NOT NULL DEFAULT 0,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "ready_at" timestamp with time zone
);
--> statement-breakpoint

CREATE INDEX "attachments_post_idx" ON "attachments" ("post_id");
--> statement-breakpoint

CREATE INDEX "attachments_uploader_idx" ON "attachments" ("uploader_user_id");
--> statement-breakpoint

CREATE INDEX "attachments_pending_idx" ON "attachments" ("created_at")
  WHERE "status" = 'pending';
--> statement-breakpoint

CREATE UNIQUE INDEX "attachments_storage_key_key" ON "attachments" ("storage_key")
  WHERE "storage_key" IS NOT NULL;
--> statement-breakpoint
CREATE UNIQUE INDEX "attachments_source_key_key" ON "attachments" ("source_key")
  WHERE "source_key" IS NOT NULL;
--> statement-breakpoint

CREATE TABLE "attachment_orphans" (
  "storage_key" text PRIMARY KEY,
  "created_at" timestamp with time zone NOT NULL DEFAULT now()
);
--> statement-breakpoint

CREATE INDEX "attachment_orphans_age_idx" ON "attachment_orphans" ("created_at");
