-- F67 — mass mail.
--
-- A row per *campaign*, not per recipient. The body is stored once here and the
-- queued jobs carry `{ massMailId, userId }` — a payload holding the body would
-- put a copy of it in the queue for every member on the board, which on a board
-- with twenty thousand members is the same text twenty thousand times, in the
-- table the worker scans on every tick.
--
-- `last_user_id` is the resume point. Sending is chunked and keyset-paged like
-- every other bulk operation in the panel, because a run that stops half way
-- has to be *continued* rather than restarted: restarting a mass mail is not a
-- neutral act, it is mailing everybody twice.
--
-- What is deliberately not here:
--
--   * **No recipient ledger.** Who was mailed is the queue's business — each
--     job is one member, and the queue already records attempts, failures and
--     dead-letters. A second table saying the same thing would need to agree
--     with it forever.
--   * **No scheduling.** A mass mail sends when an operator presses the button.
--     A "send at" column with nothing reading it is the stub D32 refuses.
--
-- The eligibility rule lives in the query rather than here, and is worth
-- stating: mass mail goes only to members whose address the board has
-- *verified*. An unverified address is as likely to be a typo — or somebody
-- else's mailbox — as it is to be the member's, and a board that mails
-- thousands of them is a board whose domain stops being delivered anywhere.

CREATE TABLE "mass_mails" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "mass_mails_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"subject" text NOT NULL,
	"body" text NOT NULL,
	"target_group_id" integer,
	"last_user_id" integer DEFAULT 0 NOT NULL,
	"queued_count" integer DEFAULT 0 NOT NULL,
	"status" text DEFAULT 'sending' NOT NULL,
	"created_by_user_id" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"finished_at" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "mass_mails" ADD CONSTRAINT "mass_mails_target_group_id_usergroups_id_fk" FOREIGN KEY ("target_group_id") REFERENCES "public"."usergroups"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "mass_mails" ADD CONSTRAINT "mass_mails_created_by_user_id_users_id_fk" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
