-- F71 — word filters.
--
-- Applied when a post is **rendered**, never when it is saved. That one choice
-- is the whole feature:
--
--   * turning a filter off restores the word everywhere, on the next render;
--   * a badly chosen pattern can be corrected with no lasting damage;
--   * a filter added today applies to everything ever written, not only to what
--     is posted after it.
--
-- Boards that rewrite the stored text on save have none of those, because the
-- original is gone the moment the first post is filtered. The cost is a pass
-- over the rendered HTML on the render path, which is why the set is expected
-- to stay small and is compiled once per render rather than once per post.
--
-- `pattern` is matched as **literal text**, never as a regular expression: a
-- pattern typed into an admin form runs on every post body the board renders,
-- and a catastrophically backtracking one would be a board that stops
-- rendering. `whole_word` defaults to true for the reason the Scunthorpe
-- problem is named after — a substring filter silently mangles place names and
-- surnames, and the member it happens to has no idea why their post looks wrong.

CREATE TABLE "word_filters" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "word_filters_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"pattern" text NOT NULL,
	"replacement" text DEFAULT '' NOT NULL,
	"whole_word" boolean DEFAULT true NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

