-- F73 — stored searches.
--
-- A search is a row so that paging, sorting and "search within results" refer
-- to something the board already knows, rather than to a query string carrying
-- every filter through every link. It stores the **query**, never a frozen list
-- of hits, and that is the whole design:
--
--   * a frozen list goes stale — it would keep offering posts that have since
--     been deleted, moved into a private community, or hidden by a moderator;
--   * a frozen list is a permission snapshot. Re-resolving means the *current*
--     viewer's scope applies on every page, so somebody who loses access to a
--     community stops seeing its hits immediately rather than for as long as the
--     stored set lives.
--
-- Re-running is cheap because F72's GiN index is doing the work; storing the
-- answer would trade a fast query for a correctness problem.
--
-- `token` is unguessable because it appears in a URL a member may bookmark, and
-- the row is **owned**: only the member — or the guest session — that ran a
-- search may open it. Not because the results would leak, since they are
-- re-resolved against whoever is asking, but because *the terms themselves* are
-- private. What somebody searched for is often more revealing than what they
-- found.
--
-- `session_key` is a **hash** of the guest's session token, never the token.
-- Guests need an identity here for two things — paging their own results, and
-- being rate-limited individually rather than as one shared bucket, which would
-- let one visitor lock out the rest — and both work on an opaque key. Storing
-- the token itself would put a live credential in a table that exists to be
-- pruned and read by operators.
--
-- `created_at` doubles as the flood-control clock. The newest row for a member
-- is when they last searched, so rate limiting needs no second table and no
-- read-then-write race: the insert itself is conditional.

CREATE TABLE "searches" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "searches_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"token" text NOT NULL,
	"user_id" integer,
	"session_key" text,
	"terms" text NOT NULL,
	"filters" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"hit_count" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "searches" ADD CONSTRAINT "searches_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "searches_token_key" ON "searches" USING btree ("token");--> statement-breakpoint
CREATE INDEX "searches_user_recent_idx" ON "searches" USING btree ("user_id","created_at");--> statement-breakpoint
CREATE INDEX "searches_session_recent_idx" ON "searches" USING btree ("session_key","created_at");
