CREATE TABLE "searches" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "searches_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"token" text NOT NULL,
	"user_id" integer,
	"session_key" text,
	"terms" text NOT NULL,
	"filters" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"hit_count" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "searches" ADD CONSTRAINT "searches_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "searches_token_key" ON "searches" USING btree ("token");--> statement-breakpoint
CREATE INDEX "searches_user_recent_idx" ON "searches" USING btree ("user_id","created_at");--> statement-breakpoint
CREATE INDEX "searches_session_recent_idx" ON "searches" USING btree ("session_key","created_at");
