-- F81 — the public REST API and outbound webhooks.
--
-- Four tables. Every one of them holds something an operator can leak, so the
-- column choices are mostly about what is *not* stored.

-- A token is a restriction on an actor, never a grant to one: `user_id` is who
-- it acts as, and every request still resolves that actor and asks the
-- Authorizer. Deleting the member deletes their tokens with them.
CREATE TABLE "api_tokens" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"user_id" integer NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
	"name" text NOT NULL,
	-- The clear half. Indexed, and short: authenticating a request must not mean
	-- hashing the candidate against every token on the board.
	"lookup" text NOT NULL,
	-- SHA-256 of the secret. The plaintext is shown once at creation and is not
	-- recoverable — a board that could show you your token again is a board whose
	-- database dump is a list of live credentials.
	"secret_hash" text NOT NULL,
	"scopes" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"expires_at" timestamp with time zone,
	"revoked_at" timestamp with time zone,
	-- Throttled in the WHERE clause like every other touch on this board, so an
	-- API under load is not also a write per request.
	"last_used_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX "api_tokens_lookup_idx" ON "api_tokens" ("lookup");
--> statement-breakpoint
CREATE INDEX "api_tokens_user_idx" ON "api_tokens" ("user_id");
--> statement-breakpoint

-- One row per token per window. The check *is* the write: an upsert that
-- returns the total after incrementing, so check and increment cannot
-- interleave — and API traffic is exactly the traffic that arrives twenty
-- requests at once.
CREATE TABLE "api_rate_limits" (
	"token_id" integer NOT NULL REFERENCES "api_tokens"("id") ON DELETE CASCADE,
	"window_start" timestamp with time zone NOT NULL,
	"used" integer DEFAULT 0 NOT NULL,
	PRIMARY KEY ("token_id", "window_start")
);
--> statement-breakpoint
-- The prune reads this; the primary key cannot serve it because the leading
-- column is the token.
CREATE INDEX "api_rate_limits_window_idx" ON "api_rate_limits" ("window_start");
--> statement-breakpoint

CREATE TABLE "webhooks" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"url" text NOT NULL,
	-- Stored in the clear, and it has to be: the board computes an HMAC with it
	-- on every delivery, so there is no hashed form that would work. It is the
	-- reason this table is administrator-only and never reaches a view model.
	"secret" text NOT NULL,
	"topics" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"created_by" integer REFERENCES "users"("id") ON DELETE SET NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint

-- The dead letter, and the delivery log that makes one possible.
--
-- `delivery_id` is stable across retries, because it is what a receiver
-- de-duplicates on: a new id per attempt turns "we retried" into "we sent two
-- events".
CREATE TABLE "webhook_deliveries" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"webhook_id" integer NOT NULL REFERENCES "webhooks"("id") ON DELETE CASCADE,
	"delivery_id" text NOT NULL,
	"topic" text NOT NULL,
	"payload" jsonb NOT NULL,
	-- pending | delivered | dead
	"status" text DEFAULT 'pending' NOT NULL,
	"attempts" smallint DEFAULT 0 NOT NULL,
	"next_attempt_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_status_code" smallint,
	"last_error" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"completed_at" timestamp with time zone
);
--> statement-breakpoint
CREATE UNIQUE INDEX "webhook_deliveries_delivery_idx" ON "webhook_deliveries" ("webhook_id", "delivery_id");
--> statement-breakpoint
-- The claim query: pending work that is due, oldest first. Partial, because a
-- delivered row is never read by the worker again and a board that has sent a
-- million of them should not be paging past them.
CREATE INDEX "webhook_deliveries_due_idx" ON "webhook_deliveries" ("next_attempt_at")
	WHERE "status" = 'pending';
