CREATE TABLE "api_tokens" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"user_id" integer NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
	"name" text NOT NULL,
	"lookup" text NOT NULL,
	"secret_hash" text NOT NULL,
	"scopes" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"expires_at" timestamp with time zone,
	"revoked_at" timestamp with time zone,
	"last_used_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX "api_tokens_lookup_idx" ON "api_tokens" ("lookup");
--> statement-breakpoint
CREATE INDEX "api_tokens_user_idx" ON "api_tokens" ("user_id");
--> statement-breakpoint

CREATE TABLE "api_rate_limits" (
	"token_id" integer NOT NULL REFERENCES "api_tokens"("id") ON DELETE CASCADE,
	"window_start" timestamp with time zone NOT NULL,
	"used" integer DEFAULT 0 NOT NULL,
	PRIMARY KEY ("token_id", "window_start")
);
--> statement-breakpoint
CREATE INDEX "api_rate_limits_window_idx" ON "api_rate_limits" ("window_start");
--> statement-breakpoint

CREATE TABLE "webhooks" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"url" text NOT NULL,
	"secret" text NOT NULL,
	"topics" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"created_by" integer REFERENCES "users"("id") ON DELETE SET NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint

CREATE TABLE "webhook_deliveries" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"webhook_id" integer NOT NULL REFERENCES "webhooks"("id") ON DELETE CASCADE,
	"delivery_id" text NOT NULL,
	"topic" text NOT NULL,
	"payload" jsonb NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"attempts" smallint DEFAULT 0 NOT NULL,
	"next_attempt_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_status_code" smallint,
	"last_error" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"completed_at" timestamp with time zone
);
--> statement-breakpoint
CREATE UNIQUE INDEX "webhook_deliveries_delivery_idx" ON "webhook_deliveries" ("webhook_id", "delivery_id");
--> statement-breakpoint
CREATE INDEX "webhook_deliveries_due_idx" ON "webhook_deliveries" ("next_attempt_at")
	WHERE "status" = 'pending';
