-- F85 — the MyBB import's two tables.
--
-- `legacy_ids` is the one F86 depends on: every old URL contains a MyBB id, so
-- redirecting `/showthread.php?tid=91` means knowing which thread that became.
-- Without it an import is a one-way door that breaks every inbound link a board
-- has accumulated — which for a community is most of its traffic.
CREATE TABLE "legacy_ids" (
	-- 'user' | 'community' | 'thread' | 'post'
	"kind" text NOT NULL,
	"legacy_id" integer NOT NULL,
	"new_id" integer NOT NULL,
	"imported_at" timestamp with time zone DEFAULT now() NOT NULL,
	PRIMARY KEY ("kind", "legacy_id")
);
--> statement-breakpoint
-- The reverse lookup: "what was this thread called on the old board". Used by
-- the import report and by anything that has to explain where a row came from.
CREATE INDEX "legacy_ids_new_idx" ON "legacy_ids" ("kind", "new_id");
--> statement-breakpoint

-- One row per import, holding the cursors.
--
-- The cursors are *legacy ids*, which is what makes a run resumable across
-- processes: an offset would mean something different on the next run, because
-- the source board is usually still being posted to during a migration.
CREATE TABLE "import_runs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"source" text DEFAULT 'mybb' NOT NULL,
	-- { users, communities, threads, posts } — a legacy id per kind.
	"cursors" jsonb DEFAULT '{}'::jsonb NOT NULL,
	-- running | finished | failed
	"status" text DEFAULT 'running' NOT NULL,
	"rows_read" integer DEFAULT 0 NOT NULL,
	"report" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"last_error" text,
	"started_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
-- One import at a time. A second concurrent run would interleave two cursor
-- sets over one destination, and the failure — rows imported twice under
-- different ids — is exactly what the idempotency was meant to prevent.
CREATE UNIQUE INDEX "import_runs_one_running_idx" ON "import_runs" ("source")
	WHERE "status" = 'running';
