CREATE TABLE "legacy_ids" (
	"kind" text NOT NULL,
	"legacy_id" integer NOT NULL,
	"new_id" integer NOT NULL,
	"imported_at" timestamp with time zone DEFAULT now() NOT NULL,
	PRIMARY KEY ("kind", "legacy_id")
);
--> statement-breakpoint
CREATE INDEX "legacy_ids_new_idx" ON "legacy_ids" ("kind", "new_id");
--> statement-breakpoint

CREATE TABLE "import_runs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"source" text DEFAULT 'mybb' NOT NULL,
	"cursors" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"status" text DEFAULT 'running' NOT NULL,
	"rows_read" integer DEFAULT 0 NOT NULL,
	"report" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"last_error" text,
	"started_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX "import_runs_one_running_idx" ON "import_runs" ("source")
	WHERE "status" = 'running';
