ALTER TABLE "threads" ADD COLUMN "rating_total" integer NOT NULL DEFAULT 0;
--> statement-breakpoint
ALTER TABLE "threads" ADD COLUMN "rating_count" integer NOT NULL DEFAULT 0;
--> statement-breakpoint

CREATE TABLE "polls" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "thread_id" integer NOT NULL UNIQUE REFERENCES "threads"("id") ON DELETE CASCADE,
  "question" text NOT NULL,
  "closes_at" timestamp with time zone,
  "created_at" timestamp with time zone NOT NULL DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "poll_options" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "poll_id" integer NOT NULL REFERENCES "polls"("id") ON DELETE CASCADE,
  "label" text NOT NULL,
  "display_order" integer NOT NULL,
  "vote_count" integer NOT NULL DEFAULT 0,
  UNIQUE ("poll_id", "id")
);
--> statement-breakpoint
CREATE INDEX "poll_options_poll_order_idx" ON "poll_options" ("poll_id", "display_order", "id");
--> statement-breakpoint
CREATE TABLE "poll_votes" (
  "poll_id" integer NOT NULL REFERENCES "polls"("id") ON DELETE CASCADE,
  "user_id" integer NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "option_id" integer NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  PRIMARY KEY ("poll_id", "user_id"),
  FOREIGN KEY ("poll_id", "option_id") REFERENCES "poll_options"("poll_id", "id") ON DELETE CASCADE
);
--> statement-breakpoint
CREATE TABLE "thread_ratings" (
  "thread_id" integer NOT NULL REFERENCES "threads"("id") ON DELETE CASCADE,
  "user_id" integer NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "rating" smallint NOT NULL CHECK ("rating" BETWEEN 1 AND 5),
  "updated_at" timestamp with time zone NOT NULL DEFAULT now(),
  PRIMARY KEY ("thread_id", "user_id")
);
