CREATE TABLE "smilies" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "smilies_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"code" text NOT NULL,
	"src" text NOT NULL,
	"alt" text,
	"enabled" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX "smilies_code_key" ON "smilies" ("code");
--> statement-breakpoint

CREATE TABLE "custom_bbcode" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "custom_bbcode_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"block" boolean DEFAULT false NOT NULL,
	"description" text,
	"enabled" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX "custom_bbcode_name_key" ON "custom_bbcode" ("name");
--> statement-breakpoint

ALTER TABLE "posts" ADD COLUMN "vocab_version" smallint DEFAULT 0 NOT NULL;
--> statement-breakpoint
ALTER TABLE "private_messages" ADD COLUMN "vocab_version" smallint DEFAULT 0 NOT NULL;
--> statement-breakpoint

CREATE INDEX "posts_vocab_version_idx" ON "posts" ("vocab_version", "id");
--> statement-breakpoint
CREATE INDEX "private_messages_vocab_version_idx" ON "private_messages" ("vocab_version", "id");
