-- F71 — the board's BBCode vocabulary: smilies and custom tags.
--
-- F37 built the safe primitives for both and deliberately left the persistence
-- to this feature. Neither table stores markup, a template, a pattern or a
-- renderer, and that is the whole safety argument: a custom tag chooses only
-- its **name** and whether it is inline or block, and the HTML it produces is
-- constructed by `@meith/bbcode` from a fixed shape. An ACP field that could
-- choose output markup would be a second markup language and a permanent XSS
-- surface, which is the mistake every board that has "custom MyCode with a
-- replacement regex" has made.
--
-- ## Why this needs a column on `posts`, when the word filter needed none
--
-- The word filter runs over *rendered HTML* and is therefore free to change:
-- the stored render is untouched, so removing a filter restores the word on
-- the next page load. The vocabulary is not like that. A smiley is expanded
-- from a **text node** and a custom tag changes how the source **parses**, so
-- both are baked into `posts.message_html` by whoever wrote the post.
--
-- That makes the board's vocabulary part of *what the renderer is*, exactly as
-- `RENDER_VERSION` is — and it gets the same treatment. `vocab_version` records
-- which vocabulary produced a stored render; `cache_versions['bbcode_vocabulary']`
-- is bumped whenever an operator changes one; and a row whose stamp is stale is
-- rendered live and rewritten behind the read path by F36's existing backfill.
--
-- The alternative was re-implementing smilies as a second pass over rendered
-- HTML, like the word filter. It was rejected: that pass would have to
-- re-derive "am I inside a `[code]` body" from markup and re-derive the
-- escaping, which is two guarantees F37 already provides for free by working on
-- the tree instead. A second implementation of a feature, with weaker rules
-- than the first, is not a saving.
--
-- Adding a NOT NULL column with a constant default is metadata-only on the
-- Postgres versions this board targets, so this does not rewrite `posts`.

CREATE TABLE "smilies" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "smilies_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	-- Literal source text such as `:)`. Never a pattern: see `compileSmilies`.
	"code" text NOT NULL,
	-- A board-controlled URL, put through the same image policy as `[img]`.
	"src" text NOT NULL,
	-- Shown to somebody who cannot see images. Defaults to the code itself.
	"alt" text,
	"enabled" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
-- Two smilies with the same code is a compile error at render time, which would
-- take the board's thread pages down. Refused at the source instead.
CREATE UNIQUE INDEX "smilies_code_key" ON "smilies" ("code");
--> statement-breakpoint

CREATE TABLE "custom_bbcode" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "custom_bbcode_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	-- 1–16 letters or digits, starting with a letter. Lower-cased on the way in,
	-- because `[Spoiler]` and `[spoiler]` are the same tag to the tokeniser and
	-- storing both would be two rows the registry refuses to build from.
	"name" text NOT NULL,
	-- Block tags render as a `div`, inline as a `span`. That is the only choice.
	"block" boolean DEFAULT false NOT NULL,
	-- For the operator, never rendered. A note about what the tag is for.
	"description" text,
	"enabled" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX "custom_bbcode_name_key" ON "custom_bbcode" ("name");
--> statement-breakpoint

-- Which vocabulary produced the stored render beside it. Compared against
-- `cache_versions['bbcode_vocabulary']`; a mismatch means render live.
ALTER TABLE "posts" ADD COLUMN "vocab_version" smallint DEFAULT 0 NOT NULL;
--> statement-breakpoint
ALTER TABLE "private_messages" ADD COLUMN "vocab_version" smallint DEFAULT 0 NOT NULL;
--> statement-breakpoint

-- F36's backfill asks "the next N rows not on the current renderer", which is
-- now two columns. Its own index, so the OR can be a bitmap of two scans rather
-- than a sequential pass over the largest table on the board.
CREATE INDEX "posts_vocab_version_idx" ON "posts" ("vocab_version", "id");
--> statement-breakpoint
CREATE INDEX "private_messages_vocab_version_idx" ON "private_messages" ("vocab_version", "id");
