-- F71 — announcements.
--
-- The last thing on this board with no model at all. An announcement is a
-- short, dated notice an administrator writes: board-wide, or attached to one
-- community.
--
-- ## It is not a thread, and the difference is the reason it exists
--
-- A sticky thread is content: members reply to it, it ages down the list, it
-- belongs to whoever wrote it, and moderating it is moderating a conversation.
-- An announcement is *chrome*. It appears above the communities, nobody can reply to
-- it, it disappears on its own date, and removing it removes nothing anybody
-- said. Boards that implement announcements as pinned threads end up with a
-- three-year-old rules post at the top of every community because taking it down
-- would delete the discussion attached to it.
--
-- ## No stored render, deliberately
--
-- `posts.message_html` exists because a thread page renders fifty bodies and a
-- board has two million of them. A board has a handful of announcements and
-- shows at most a few per page, so storing a render would buy a few
-- microseconds and cost a third `render_version` column, a third staleness
-- predicate and a third backfill — including for F71's own vocabulary, which
-- would otherwise have to invalidate this table too. Rendered live, from
-- source, with whatever vocabulary is current.
--
-- ## `community_id NULL` means the whole board
--
-- Not a separate `scope` column, because the two would be able to disagree — a
-- row saying `scope = 'community'` with no community, or the reverse, is a state the
-- reader would have to invent a rule for. NULL says it once.
--
-- Visibility is the community's own: an announcement on a community a viewer cannot see
-- is one they are not shown, resolved through F47 like every other read. A
-- board-wide one is visible to anybody who can see the board, which is what
-- "board-wide" means.

CREATE TABLE "announcements" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "announcements_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	-- NULL is board-wide. Cascades, because an announcement about a community that
	-- no longer exists is one nobody can act on and nothing can link to.
	"community_id" integer REFERENCES "communities"("id") ON DELETE CASCADE,
	"title" text NOT NULL,
	-- BBCode source, rendered on read. There is no `message_html` here; see above.
	"message" text NOT NULL,
	"author_user_id" integer REFERENCES "users"("id") ON DELETE SET NULL,
	-- Captured, so a deleted administrator's announcement still says who wrote it.
	"author_username" text DEFAULT '' NOT NULL,
	"starts_at" timestamp with time zone DEFAULT now() NOT NULL,
	-- NULL never expires. An announcement an operator has to remember to remove
	-- is one that is still up in two years, which is the failure this column is
	-- for — but "until further notice" is a real thing to want, so it is allowed
	-- rather than forced.
	"ends_at" timestamp with time zone,
	-- Separate from the window: switching one off to redraft it should not mean
	-- losing the dates it was scheduled for.
	"enabled" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
-- The read is "what is live right now, for these communities". Ordered newest first,
-- so the index carries `starts_at` descending and the predicate keeps the
-- switched-off rows out of it entirely.
CREATE INDEX "announcements_live_idx" ON "announcements" ("starts_at" DESC) WHERE "enabled";
--> statement-breakpoint
CREATE INDEX "announcements_community_idx" ON "announcements" ("community_id");
