CREATE TABLE "announcements" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "announcements_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"forum_id" integer REFERENCES "forums"("id") ON DELETE CASCADE,
	"title" text NOT NULL,
	"message" text NOT NULL,
	"author_user_id" integer REFERENCES "users"("id") ON DELETE SET NULL,
	"author_username" text DEFAULT '' NOT NULL,
	"starts_at" timestamp with time zone DEFAULT now() NOT NULL,
	"ends_at" timestamp with time zone,
	"enabled" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE INDEX "announcements_live_idx" ON "announcements" ("starts_at" DESC) WHERE "enabled";
--> statement-breakpoint
CREATE INDEX "announcements_forum_idx" ON "announcements" ("forum_id");
