-- F46 — anti-spam: rate-limit counters and captcha questions.
--
-- ## `rate_limits` is a counter table, and the shape is the whole point
--
-- One row per (scope, subject, window), incremented by an insert-on-conflict
-- that returns the new total. **That single statement is the feature.** A
-- read-then-write would let ten requests arriving together each see nine and
-- each decide it was fine — and under an attack that interleaving is not rare,
-- it is the expected one, because flooding is exactly the traffic that arrives
-- in parallel. Postgres serialises the conflicting upserts for us; nothing in
-- application code can.
--
-- It is also why the limit is *multi-instance* in the sense the roadmap asks
-- for: the counter is a row rather than process state, so ten serverless
-- instances share one allowance instead of ten.
--
-- Fixed windows rather than a sliding log. A sliding window needs a row per
-- action and a scan to answer a question; this needs one row per subject per
-- window and answers by primary key. The cost is the boundary — a full
-- allowance at 10:59 and another at 11:00 — which for spam control is an
-- acceptable failure, because the attacker's reward is one extra window rather
-- than an unbounded one. Closing it would make the anti-spam feature the
-- board's largest table.
--
-- `subject` is text rather than a user id because a guest has no id: it holds
-- `u:<id>` for a member and `ip:<prefix>` for a guest, built in one place
-- (`subjectFor`). The prefix is F09's already-truncated address — enough to
-- group by, not enough to identify somebody by.
--
-- No foreign key to `users`, deliberately. A limit row is not a fact about a
-- member worth keeping, and a cascade on account deletion would be a write
-- amplification on a table that is otherwise pure append-and-prune.

CREATE TABLE "rate_limits" (
	-- One of the five F46 names: post, search, message, report, upload.
	"scope" text NOT NULL,
	"subject" text NOT NULL,
	"window_start" timestamp with time zone NOT NULL,
	"used" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "rate_limits_pkey" PRIMARY KEY ("scope", "subject", "window_start")
);
--> statement-breakpoint
-- The prune (F06's tick) asks "every window older than X", across all scopes.
-- The primary key leads with `scope`, so it cannot answer that without a scan.
CREATE INDEX "rate_limits_window_idx" ON "rate_limits" ("window_start");
--> statement-breakpoint

-- ## `captcha_questions`
--
-- Admin-defined question-and-answer challenges. Answers are stored as text and
-- compared case-insensitively after trimming and collapsing internal spaces —
-- an operator writing "Blue" and a visitor typing "blue " is not a failed
-- challenge, and treating it as one teaches people the form is broken.
--
-- The answers are **not** hashed. They are not secrets: the question is shown
-- to everybody, an attacker can read the answer by registering once, and the
-- control is aimed at scripts rather than at people. Hashing them would cost
-- the ACP the ability to show an operator what they configured, in exchange for
-- protecting a value that is public by construction.
CREATE TABLE "captcha_questions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "captcha_questions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"question" text NOT NULL,
	-- One per line, as the operator typed them. Any one satisfies the challenge.
	"answers" text NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
