-- Themes become something a board turns on and off, and a member chooses between.
--
-- `themes` has carried `is_default` since the initial schema with nothing that
-- reads or writes it: which theme a board rendered was a build-time fact, so a
-- column saying "this is the default one" had no question to answer. It has one
-- now — a member picks from the enabled themes, and the default is what a member
-- who has picked nothing gets — so the column is finally wired to something, and
-- `enabled` joins it.
--
-- ## Why the default is true
--
-- A theme registered in `forum.config.ts` is a theme somebody deliberately
-- installed. The state that needs a row is "turned *off*", which is a decision
-- an administrator made, not the absence of one — and defaulting the other way
-- would take every board that upgrades and hide every theme it had until
-- somebody found this screen.
--
-- It also keeps the rule the rest of this table already follows: **an absent row
-- means the theme is exactly as it ships**. Nothing is seeded here, no
-- backfill runs, and a board that has never opened the theme screen has an empty
-- table and an enabled, uncustomised set of themes — which is what it had before
-- this migration, described the same way.

ALTER TABLE "themes" ADD COLUMN "enabled" boolean DEFAULT true NOT NULL;
