CREATE TABLE "navigation_item_groups" (
	"item_id" integer NOT NULL,
	"group_id" integer NOT NULL,
	CONSTRAINT "navigation_item_groups_item_id_group_id_pk" PRIMARY KEY("item_id","group_id")
);
--> statement-breakpoint
CREATE TABLE "navigation_items" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "navigation_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"key" text,
	"label" text DEFAULT '' NOT NULL,
	"href" text NOT NULL,
	"display_order" integer DEFAULT 0 NOT NULL,
	"audience" text DEFAULT 'all' NOT NULL,
	"new_tab" boolean DEFAULT false NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "navigation_items_audience_check" CHECK ("navigation_items"."audience" in ('all', 'guests', 'members', 'staff'))
);
--> statement-breakpoint
ALTER TABLE "navigation_item_groups" ADD CONSTRAINT "navigation_item_groups_item_id_navigation_items_id_fk" FOREIGN KEY ("item_id") REFERENCES "public"."navigation_items"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "navigation_item_groups" ADD CONSTRAINT "navigation_item_groups_group_id_usergroups_id_fk" FOREIGN KEY ("group_id") REFERENCES "public"."usergroups"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "navigation_item_groups_group_idx" ON "navigation_item_groups" USING btree ("group_id");--> statement-breakpoint
CREATE UNIQUE INDEX "navigation_items_key_key" ON "navigation_items" USING btree ("key") WHERE "navigation_items"."key" is not null;--> statement-breakpoint
CREATE INDEX "navigation_items_order_idx" ON "navigation_items" USING btree ("display_order","id");--> statement-breakpoint

INSERT INTO "navigation_items" ("key", "href", "display_order", "audience")
VALUES ('home', '/', 0, 'all'),
  ('new-posts', '/discover/new', 10, 'all'),
  ('unanswered', '/discover/unanswered', 20, 'all'),
  ('my-posts', '/discover/participated', 30, 'members'),
  ('search', '/search', 40, 'all'),
  ('online', '/online', 50, 'all');
