CREATE TABLE "admin_undo_operations" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "admin_undo_operations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"token_hash" text NOT NULL,
	"actor_user_id" integer NOT NULL,
	"operation" text NOT NULL,
	"snapshot" jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"consumed_at" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "admin_undo_operations" ADD CONSTRAINT "admin_undo_operations_actor_user_id_users_id_fk" FOREIGN KEY ("actor_user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "admin_undo_operations_token_key" ON "admin_undo_operations" USING btree ("token_hash");--> statement-breakpoint
CREATE INDEX "admin_undo_operations_live_idx" ON "admin_undo_operations" USING btree ("actor_user_id","expires_at");