CREATE TABLE "backup_runs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "backup_runs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"trigger" text NOT NULL,
	"status" text DEFAULT 'queued' NOT NULL,
	"requested_by_user_id" integer,
	"requested_at" timestamp with time zone DEFAULT now() NOT NULL,
	"started_at" timestamp with time zone,
	"finished_at" timestamp with time zone,
	"heartbeat_at" timestamp with time zone,
	"bundle_name" text,
	"size_bytes" bigint,
	"uploads" text,
	"shipped" boolean DEFAULT false NOT NULL,
	"skipped_keys" integer DEFAULT 0 NOT NULL,
	"error" text,
	CONSTRAINT "backup_runs_trigger_check" CHECK ("backup_runs"."trigger" in ('manual', 'schedule', 'upgrade', 'cli')),
	CONSTRAINT "backup_runs_status_check" CHECK ("backup_runs"."status" in ('queued', 'running', 'done', 'incomplete', 'failed'))
);
--> statement-breakpoint
ALTER TABLE "backup_runs" ADD CONSTRAINT "backup_runs_requested_by_user_id_users_id_fk" FOREIGN KEY ("requested_by_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "backup_runs_status_idx" ON "backup_runs" USING btree ("status","id");--> statement-breakpoint
CREATE INDEX "backup_runs_recent_idx" ON "backup_runs" USING btree ("requested_at" DESC NULLS LAST);