import type { Translator } from '@meith/i18n'

import { adminSharedCopy } from './admin-copy'
import { copyFor, patternCopy } from './copy'
import { untranslated } from './time'

export function groupAdminCopy(t: Translator = untranslated()): Readonly<Record<string, string>> {
  return {
    ...adminSharedCopy(t),
    ...copyFor(
      [
        'adminGroup.select.placeholder',
        'adminGroup.title',
        'adminGroup.description',
        'adminGroup.displayOrder',
        'adminGroup.nameColour',
        'adminGroup.nameColourHint',
        'adminGroup.light',
        'adminGroup.dark',
        'adminGroup.nameColour.describesLight',
        'adminGroup.nameColour.describesDark',
        'adminGroup.sampleMember',
        'adminGroup.staffGroup',
        'adminGroup.pluginGrantable',
        'adminGroup.pluginGrantableHint',
        'adminGroup.saveGroup',
        'adminGroup.perm.tickedRestricted',
        'adminGroup.perm.forumDefault',
        'adminGroup.savePermissions',
        'adminGroup.key',
        'adminGroup.keyHint',
        'adminGroup.copyPermissionsFrom',
        'adminGroup.copyPermissionsFromHint',
        'adminGroup.createGroup',
        'adminGroup.deleted',
        'adminGroup.moveMembersTo',
        'adminGroup.moveMembersToHint',
        'adminGroup.deleteGroup',
        'adminGroup.deleteNote',
        'adminGroup.move.from',
        'adminGroup.move.to',
        'adminGroup.move.nextBatch',
        'adminGroup.move.start',
        'adminGroup.move.note',
        'adminGroup.rule.anyGroup',
        'adminGroup.rule.titlePlaceholder',
        'adminGroup.rule.titleHint',
        'adminGroup.rule.displayOrderHint',
        'adminGroup.rule.promoteFrom',
        'adminGroup.rule.promoteFromHint',
        'adminGroup.rule.promoteInto',
        'adminGroup.rule.promoteIntoHint',
        'adminGroup.rule.thresholds',
        'adminGroup.rule.thresholdsHint',
        'adminGroup.rule.posts',
        'adminGroup.rule.reputation',
        'adminGroup.rule.daysRegistered',
        'adminGroup.rule.enabledNotice',
        'adminGroup.rule.disabledNotice',
        'adminGroup.rule.save',
        'adminGroup.rule.enable',
        'adminGroup.rule.disable',
        'adminGroup.rule.removeNote',
        'adminGroup.rule.added',
        'adminGroup.rule.add',
        'adminGroup.apply.note',
      ],
      t,
    ),
    ...patternCopy(
      [
        'adminGroup.move.finished',
        'adminGroup.move.moreSoFar',
        'adminGroup.apply.done',
        'adminGroup.apply.promote',
      ],
      t,
    ),
  }
}
