import type { Translator } from '@meith/i18n'

import { copyFor, patternCopy, splitAround } from './copy'
import { untranslated } from './time'

export function installFormCopy(
  reservedUsernames: readonly string[],
  t: Translator = untranslated(),
): Readonly<Record<string, string>> {
  const [urlFromEnvLead, urlFromEnvTail] = splitAround(t, 'install.urlFromEnv', 'name')
  const [mailFromEnvLead, mailFromEnvTail] = splitAround(t, 'install.mailFromEnv', 'name')
  const [testNoteLead, testNoteTail] = splitAround(t, 'install.mail.testNote', 'before')
  return {
    ...copyFor(
      [
        'install.board.title',
        'install.board.hint',
        'install.boardName.label',
        'install.boardName.hint',
        'install.boardUrl.label',
        'install.boardUrl.hint',
        'install.account.title',
        'install.account.hint',
        'install.username.label',
        'install.email.label',
        'install.email.hint',
        'install.password.label',
        'install.password.hint',
        'install.mail.title',
        'install.mail.envHint',
        'install.mail.optionalHint',
        'install.mail.testNoteBefore',
        'install.mail.how',
        'install.mail.skip',
        'install.mail.needs',
        'install.mail.serverDetails',
        'install.mailFrom.label',
        'install.mailFrom.hint',
        'install.mailUsername.label',
        'install.mailUsername.hint',
        'install.mailSecret.label',
        'install.mailSecret.hint',
        'install.mailHost.label',
        'install.mailHost.hint',
        'install.mailPort.label',
        'install.mailSecurity.label',
        'install.mailSecurity.default',
        'install.mailSecurity.starttls',
        'install.mailSecurity.tls',
        'install.mailSecurity.none',
        'install.mailEndpoint.label',
        'install.mailEndpoint.hint',
        'install.submit.installing',
        'install.submit.tryAgain',
        'install.submit.install',
        'install.submit.pendingNote',
        'install.submit.idleNote',
        'install.steps.howFar',
        'install.steps.what',
        'install.steps.done',
        'install.steps.failed',
        'install.steps.notRun',
        'install.outcome.oneAnswer',
        'install.outcome.passwords',
        'install.field.boardName',
        'install.field.boardUrl',
        'install.field.username',
        'install.field.email',
        'install.field.password',
        'install.field.mailPreset',
        'install.field.mailFrom',
        'install.field.mailUsername',
        'install.field.mailSecret',
        'install.field.mailHost',
        'install.field.mailPort',
        'install.field.mailSecurity',
        'install.field.mailEndpoint',
      ],
      t,
    ),
    ...patternCopy(
      ['install.steps.count', 'install.outcome.didNotFinish', 'install.outcome.answers'],
      t,
    ),
    'install.username.hint': t.t('install.username.hint', {
      names: reservedUsernames.join(', '),
    }),
    'install.urlFromEnvLead': urlFromEnvLead,
    'install.urlFromEnvTail': urlFromEnvTail,
    'install.mailFromEnvLead': mailFromEnvLead,
    'install.mailFromEnvTail': mailFromEnvTail,
    'install.mail.testNoteLead': testNoteLead,
    'install.mail.testNoteTail': testNoteTail,
  }
}
