export const SEARCH_LANGUAGES = [
  'simple',
  'arabic',
  'armenian',
  'basque',
  'catalan',
  'danish',
  'dutch',
  'english',
  'estonian',
  'finnish',
  'french',
  'german',
  'greek',
  'hindi',
  'hungarian',
  'indonesian',
  'irish',
  'italian',
  'lithuanian',
  'nepali',
  'norwegian',
  'portuguese',
  'romanian',
  'russian',
  'serbian',
  'spanish',
  'swedish',
  'tamil',
  'turkish',
  'yiddish',
] as const

export type SearchLanguage = (typeof SEARCH_LANGUAGES)[number]

export const DEFAULT_SEARCH_LANGUAGE: SearchLanguage = 'english'

export const SEARCH_LANGUAGE_OPTIONS: readonly {
  readonly value: SearchLanguage
  readonly label: string
}[] = [
  { value: 'simple', label: 'No stemming (exact words)' },
  { value: 'arabic', label: 'Arabic' },
  { value: 'armenian', label: 'Armenian' },
  { value: 'basque', label: 'Basque' },
  { value: 'catalan', label: 'Catalan' },
  { value: 'danish', label: 'Danish' },
  { value: 'dutch', label: 'Dutch' },
  { value: 'english', label: 'English' },
  { value: 'estonian', label: 'Estonian' },
  { value: 'finnish', label: 'Finnish' },
  { value: 'french', label: 'French' },
  { value: 'german', label: 'German' },
  { value: 'greek', label: 'Greek' },
  { value: 'hindi', label: 'Hindi' },
  { value: 'hungarian', label: 'Hungarian' },
  { value: 'indonesian', label: 'Indonesian' },
  { value: 'irish', label: 'Irish' },
  { value: 'italian', label: 'Italian' },
  { value: 'lithuanian', label: 'Lithuanian' },
  { value: 'nepali', label: 'Nepali' },
  { value: 'norwegian', label: 'Norwegian' },
  { value: 'portuguese', label: 'Portuguese' },
  { value: 'romanian', label: 'Romanian' },
  { value: 'russian', label: 'Russian' },
  { value: 'serbian', label: 'Serbian' },
  { value: 'spanish', label: 'Spanish' },
  { value: 'swedish', label: 'Swedish' },
  { value: 'tamil', label: 'Tamil' },
  { value: 'turkish', label: 'Turkish' },
  { value: 'yiddish', label: 'Yiddish' },
]
