#!/usr/bin/env node

import { readdir, readFile, writeFile } from 'node:fs/promises'
import { join, relative } from 'node:path'

const ROOT = new URL('..', import.meta.url).pathname.replace(/\/$/, '')
const DOCS = join(ROOT, 'docs')
const MANIFEST = 'apps/web/content/docs.manifest.json'
const README = 'README.md'

const START = '<!-- docs:table start — generated by pnpm site:docs; edit the manifest instead -->'
const END = '<!-- docs:table end -->'

const check = process.argv.includes('--check')
const problems = []

async function markdownFiles(dir = DOCS) {
  const entries = await readdir(dir, { withFileTypes: true })
  const found = []

  for (const entry of entries) {
    const full = join(dir, entry.name)
    if (entry.isDirectory()) found.push(...(await markdownFiles(full)))
    else if (entry.name.endsWith('.md')) found.push(relative(DOCS, full))
  }

  return found.sort()
}

const manifest = JSON.parse(await readFile(join(ROOT, MANIFEST), 'utf8'))
const files = await markdownFiles()

const published = new Map(manifest.documents.map((doc) => [doc.file, doc]))
const internal = new Map(manifest.internal.map((doc) => [doc.file, doc]))
const sections = new Map(manifest.sections.map((section) => [section.id, section]))

for (const file of files) {
  if (published.has(file) || internal.has(file)) continue
  problems.push(
    `docs/${file} is neither published nor listed as internal in ${MANIFEST}.\n` +
      '    Add it to `documents` (with a slug, section, title and blurb) so the site\n' +
      '    publishes it, or to `internal` with the reason it stays in the repository.',
  )
}

for (const [file, doc] of published) {
  if (!files.includes(file)) {
    problems.push(`${MANIFEST} publishes docs/${file} as "${doc.slug}", and that file does not exist.`)
  }
}
for (const file of internal.keys()) {
  if (!files.includes(file)) {
    problems.push(`${MANIFEST} lists docs/${file} as internal, and that file does not exist.`)
  }
}
for (const file of published.keys()) {
  if (internal.has(file)) {
    problems.push(`${MANIFEST} both publishes and hides docs/${file}. It can only be one.`)
  }
}

const slugs = new Set()
for (const doc of manifest.documents) {
  if (slugs.has(doc.slug)) problems.push(`${MANIFEST} uses the slug "${doc.slug}" twice.`)
  slugs.add(doc.slug)

  if (!sections.has(doc.section)) {
    problems.push(`${MANIFEST}: "${doc.slug}" is in section "${doc.section}", which is not declared.`)
  }
  for (const field of ['title', 'blurb']) {
    if (typeof doc[field] !== 'string' || doc[field].trim() === '') {
      problems.push(`${MANIFEST}: "${doc.slug}" has no ${field}.`)
    }
  }
}

for (const section of manifest.sections) {
  const inSection = manifest.documents.filter((doc) => doc.section === section.id)
  const primaries = inSection.filter((doc) => doc.primary)

  if (inSection.length === 0) {
    problems.push(`${MANIFEST}: section "${section.id}" has no documents.`)
  } else if (primaries.length !== 1) {
    problems.push(
      `${MANIFEST}: section "${section.id}" has ${primaries.length} primary documents, and needs exactly 1.`,
    )
  }
}

function renderTable() {
  const rows = manifest.sections.flatMap((section) =>
    manifest.documents
      .filter((doc) => doc.section === section.id)
      .map((doc) => {
        const mark = doc.generated ? ' *(generated)*' : ''
        return `| ${section.title} | [\`${doc.file}\`](./docs/${doc.file}) | ${doc.blurb}${mark} |`
      }),
  )

  return [
    START,
    '',
    '| Section | Document | What it answers |',
    '|---|---|---|',
    ...rows,
    '',
    END,
  ].join('\n')
}

const readme = await readFile(join(ROOT, README), 'utf8')
const startAt = readme.indexOf(START)
const endAt = readme.indexOf(END)

if (startAt === -1 || endAt === -1 || endAt < startAt) {
  problems.push(
    `${README} has no generated documentation table.\n` +
      `    Add the markers "${START}" and "${END}" where it should go.`,
  )
} else {
  const current = readme.slice(startAt, endAt + END.length)
  const wanted = renderTable()

  if (current !== wanted) {
    if (check) {
      problems.push(
        `${README}'s documentation table is out of date with ${MANIFEST}.\n` +
          '    Run `pnpm site:docs` to rewrite it. Do not edit it by hand — the manifest\n' +
          '    is where a document is described, and this table is a view of it.',
      )
    } else {
      await writeFile(join(ROOT, README), readme.replace(current, wanted))
      console.log(`${README}: documentation table rewritten from ${MANIFEST}.`)
    }
  }
}

if (problems.length > 0) {
  console.error(`\n✖ the published documentation set is out of step.\n`)
  for (const problem of problems) console.error(`  - ${problem}\n`)
  process.exit(1)
}

console.log(
  `✓ documentation: ${published.size} published, ${internal.size} kept in the repository, ` +
    `${files.length} files under docs/ all accounted for`,
)
