#!/usr/bin/env node
/**
 * The documentation is published from one copy, and this is what keeps it so.
 *
 * `apps/web` renders `docs/*.md` directly — it holds no copy of any document,
 * only a manifest saying which ones exist, what they are called and where they
 * belong. That arrangement has exactly one way to rot, and it is silent: a
 * document is added to `docs/`, nobody names it in the manifest, and the site
 * simply never mentions it. Nothing fails. The newest document — the one most
 * likely to matter — is the one that goes missing, which is the same failure
 * `scripts/docs-index.mjs` exists to prevent for `docs/README.md`.
 *
 * So three things are checked, and one is generated:
 *
 *   1. Every `.md` under `docs/` is either published by the manifest or listed
 *      in its `internal` array with a reason. Silence is not an option.
 *   2. Every manifest entry points at a file that exists.
 *   3. Slugs are unique, sections resolve, and each section has exactly one
 *      primary document — the one the site sends a new reader to first.
 *   4. The table in `README.md` is written from the manifest, between markers,
 *      so the repository's front page cannot drift from what the site publishes.
 *
 * Run: pnpm site:docs        (rewrites README.md)
 *      pnpm site:docs:check  (fails instead, and is what verify and CI run)
 */

import { readdir, readFile, writeFile } from 'node:fs/promises'
import { join, relative } from 'node:path'

const ROOT = new URL('..', import.meta.url).pathname.replace(/\/$/, '')
const DOCS = join(ROOT, 'docs')
const MANIFEST = 'apps/web/content/docs.manifest.json'
const README = 'README.md'

const START = '<!-- docs:table start — generated by pnpm site:docs; edit the manifest instead -->'
const END = '<!-- docs:table end -->'

const check = process.argv.includes('--check')
const problems = []

/** Every Markdown file under docs/, recursively, relative to docs/. */
async function markdownFiles(dir = DOCS) {
  const entries = await readdir(dir, { withFileTypes: true })
  const found = []

  for (const entry of entries) {
    const full = join(dir, entry.name)
    if (entry.isDirectory()) found.push(...(await markdownFiles(full)))
    else if (entry.name.endsWith('.md')) found.push(relative(DOCS, full))
  }

  return found.sort()
}

const manifest = JSON.parse(await readFile(join(ROOT, MANIFEST), 'utf8'))
const files = await markdownFiles()

const published = new Map(manifest.documents.map((doc) => [doc.file, doc]))
const internal = new Map(manifest.internal.map((doc) => [doc.file, doc]))
const sections = new Map(manifest.sections.map((section) => [section.id, section]))

/* 1. Nothing under docs/ is unaccounted for. */
for (const file of files) {
  if (published.has(file) || internal.has(file)) continue
  problems.push(
    `docs/${file} is neither published nor listed as internal in ${MANIFEST}.\n` +
      '    Add it to `documents` (with a slug, section, title and blurb) so the site\n' +
      '    publishes it, or to `internal` with the reason it stays in the repository.',
  )
}

/* 2. Nothing in the manifest points at a file that is not there. */
for (const [file, doc] of published) {
  if (!files.includes(file)) {
    problems.push(`${MANIFEST} publishes docs/${file} as "${doc.slug}", and that file does not exist.`)
  }
}
for (const file of internal.keys()) {
  if (!files.includes(file)) {
    problems.push(`${MANIFEST} lists docs/${file} as internal, and that file does not exist.`)
  }
}
for (const file of published.keys()) {
  if (internal.has(file)) {
    problems.push(`${MANIFEST} both publishes and hides docs/${file}. It can only be one.`)
  }
}

/* 3. The manifest is internally consistent. */
const slugs = new Set()
for (const doc of manifest.documents) {
  if (slugs.has(doc.slug)) problems.push(`${MANIFEST} uses the slug "${doc.slug}" twice.`)
  slugs.add(doc.slug)

  if (!sections.has(doc.section)) {
    problems.push(`${MANIFEST}: "${doc.slug}" is in section "${doc.section}", which is not declared.`)
  }
  for (const field of ['title', 'blurb']) {
    if (typeof doc[field] !== 'string' || doc[field].trim() === '') {
      problems.push(`${MANIFEST}: "${doc.slug}" has no ${field}.`)
    }
  }
}

for (const section of manifest.sections) {
  const inSection = manifest.documents.filter((doc) => doc.section === section.id)
  const primaries = inSection.filter((doc) => doc.primary)

  if (inSection.length === 0) {
    problems.push(`${MANIFEST}: section "${section.id}" has no documents.`)
  } else if (primaries.length !== 1) {
    /*
     * The site sends a reader to a section's primary document from the landing
     * page and the footer. Two primaries means one of those links silently picks
     * whichever came first in the file; none means the link disappears.
     */
    problems.push(
      `${MANIFEST}: section "${section.id}" has ${primaries.length} primary documents, and needs exactly 1.`,
    )
  }
}

/* 4. README's table, written from the manifest. */
function renderTable() {
  const rows = manifest.sections.flatMap((section) =>
    manifest.documents
      .filter((doc) => doc.section === section.id)
      .map((doc) => {
        const mark = doc.generated ? ' *(generated)*' : ''
        return `| ${section.title} | [\`${doc.file}\`](./docs/${doc.file}) | ${doc.blurb}${mark} |`
      }),
  )

  return [
    START,
    '',
    '| Section | Document | What it answers |',
    '|---|---|---|',
    ...rows,
    '',
    END,
  ].join('\n')
}

const readme = await readFile(join(ROOT, README), 'utf8')
const startAt = readme.indexOf(START)
const endAt = readme.indexOf(END)

if (startAt === -1 || endAt === -1 || endAt < startAt) {
  problems.push(
    `${README} has no generated documentation table.\n` +
      `    Add the markers "${START}" and "${END}" where it should go.`,
  )
} else {
  const current = readme.slice(startAt, endAt + END.length)
  const wanted = renderTable()

  if (current !== wanted) {
    if (check) {
      problems.push(
        `${README}'s documentation table is out of date with ${MANIFEST}.\n` +
          '    Run `pnpm site:docs` to rewrite it. Do not edit it by hand — the manifest\n' +
          '    is where a document is described, and this table is a view of it.',
      )
    } else {
      await writeFile(join(ROOT, README), readme.replace(current, wanted))
      console.log(`${README}: documentation table rewritten from ${MANIFEST}.`)
    }
  }
}

if (problems.length > 0) {
  console.error(`\n✖ the published documentation set is out of step.\n`)
  for (const problem of problems) console.error(`  - ${problem}\n`)
  process.exit(1)
}

console.log(
  `✓ documentation: ${published.size} published, ${internal.size} kept in the repository, ` +
    `${files.length} files under docs/ all accounted for`,
)
