import type { PluginMigration } from '@meith/plugin-kit'

export const AWARDS_MIGRATIONS: readonly PluginMigration[] = [
  {
    id: '0001_awards',
    statements: [
      `create table plugin_awards_award (
      id bigint generated by default as identity primary key,
      name text not null, description text not null default '',
      icon_kind text not null default 'emoji', icon text not null default '🏆',
      display_order int not null default 0, allow_multiple bool not null default false,
      listed bool not null default true, archived_at timestamptz,
      created_at timestamptz not null default now(), updated_at timestamptz not null default now()
    )`,
      `create table plugin_awards_rule (
      id bigint generated by default as identity primary key,
      award_id bigint not null references plugin_awards_award(id) on delete cascade,
      title text not null, enabled bool not null default true,
      min_post_count int, min_thread_count int, min_reputation int, min_days_registered int,
      created_at timestamptz not null default now(), updated_at timestamptz not null default now()
    )`,
      `create table plugin_awards_grant (
      id bigint generated by default as identity primary key,
      award_id bigint not null references plugin_awards_award(id) on delete cascade,
      user_id int not null, rule_id bigint, granted_by_user_id int,
      reason text not null default '', granted_at timestamptz not null default now()
    )`,
      `create index plugin_awards_grant_user on plugin_awards_grant (user_id, granted_at desc)`,
      `create index plugin_awards_grant_award on plugin_awards_grant (award_id, granted_at desc)`,
      `create unique index plugin_awards_grant_rule_user on plugin_awards_grant (rule_id, user_id) where rule_id is not null`,
      `create table plugin_awards_dirty (user_id int primary key, queued_at timestamptz not null default now())`,
      `create table plugin_awards_scan (
      id smallint primary key default 1 check (id = 1), cursor int not null default 0, completed_at timestamptz
    )`,
      `insert into plugin_awards_scan (id) values (1)`,
    ],
  },
]
